"""Build the worst-case artifact the budgets permit.

Sampling real companies is not a test of a fixed-canvas layout: it tells you
whether THOSE companies fit. Every fixture used so far sat comfortably below
the caps, so the suite reported clean while a live ETN run -- whose prose ran to
the caps in almost every field -- clipped in seven places.

This fills every prose field with far more text than allowed and then runs the
enforcer, which trims each one to exactly its budget. The result is the largest
artifact the budgets can produce. If that renders without clipping, no real run
can clip, because the enforcer guarantees every field is at or under these
lengths. That is a proof rather than a sample.
"""
import copy, json, re, sys

sys.path.insert(0, '.')
import deepdive

# Filler has to match the WIDTH of real financial prose, not just its word
# count, because the caps are counted in words but boxes overflow in pixels.
# An early version averaged 10.9 characters per word against 6.3 for the Deere
# reference and 7.4 for a live Cigna run -- half again too wide, which would
# have driven the caps far tighter than the layout actually requires. This mix
# averages ~7.5: a shade above the widest real sample, so the worst case stays
# conservative without being fictional.
_SHORT = 'the and for with from into over at by on in to a of is as'.split()
_MID = ('growth margin orders backlog revenue segment demand pricing capacity '
        'utility scale volume outlook target profit mix cycle').split()
_LONG = ('management guidance sequential expansion infrastructure acceleration '
         'electrification distribution manufacturing consolidated '
         '$13.40-13.60 +103% 27.5%').split()
WORDS = (_SHORT * 0 + _MID * 5 + _LONG * 3) * 40
FILLER = ' '.join(WORDS)


def looks_like_a_value(text):
    """Short strings carrying figures are data, not prose; leave them alone."""
    t = str(text).strip()
    return len(t) <= 28 and bool(re.search(r'[\d$%x×]', t))


def inflate(node):
    if isinstance(node, str):
        return node if looks_like_a_value(node) else FILLER
    if isinstance(node, list):
        return [inflate(x) for x in node]
    if isinstance(node, dict):
        return {k: (v if k in ('icon', 'kind', 'period', 'case') else inflate(v))
                for k, v in node.items()}
    return node


if __name__ == '__main__':
    base = json.load(open(sys.argv[1] if len(sys.argv) > 1
                          else 'fixtures/deepdive_ci_sample.json'))
    out = {'master': inflate(copy.deepcopy(base['master'])),
           'onepager': inflate(copy.deepcopy(base['onepager']))}
    # Keep the numeric series: the chart needs real numbers to plot.
    out['master']['earnings_history'] = copy.deepcopy(base['master'].get('earnings_history'))
    out['onepager']['earnings_history'] = copy.deepcopy(base['onepager'].get('earnings_history'))
    out['master']['at_glance'] = copy.deepcopy(base['master'].get('at_glance'))
    out['master'], _ = deepdive.enforce_master_budgets(out['master'])
    out['onepager'], _ = deepdive.enforce_budgets(out['onepager'])
    out['_note'] = ('Every prose field at its budget maximum. Generated by '
                    'tools/make_max_fixture.py; do not hand-edit.')
    json.dump(out, open('fixtures/deepdive_max.json', 'w'), indent=1)
    m = out['master']
    print('max fixture written')
    print('  thesis.summary words     :', len(str(m['investment_thesis']['summary']).split()))
    print('  signpost why words       :', [len(str(s.get('why_it_matters','')).split())
                                           for s in m.get('signposts', [])][:3], '...')
    print('  opportunity detail words :', [len(str(o.get('detail','')).split())
                                           for o in m.get('opportunities', [])][:3], '...')
