import * as React from 'react';
import {activityRows,activityAge,macConnected} from './activity-model.mjs';
export function ActivityWorkspace({api,onNavigate,compact=false}) {
 const [data,setData]=React.useState(null),[error,setError]=React.useState(''),[filter,setFilter]=React.useState('active'),[query,setQuery]=React.useState('');
 const [loading,setLoading]=React.useState(false);const mounted=React.useRef(false),pending=React.useRef(false),controller=React.useRef(null);
 const load=async()=>{if(pending.current)return;pending.current=true;setLoading(true);const c=new AbortController();controller.current=c;const timeout=setTimeout(()=>c.abort(),15000);
  try{const r=await fetch(`${api}/api/activity`,{signal:c.signal});if(!r.ok)throw new Error('Activity could not be refreshed.');const d=await r.json();if(mounted.current){setData(d);setError('');}}
  catch(e){if(mounted.current)setError('Activity could not be refreshed. Displayed information may be out of date.');}
  finally{clearTimeout(timeout);pending.current=false;if(mounted.current)setLoading(false);}};
 React.useEffect(()=>{mounted.current=true;load();const timer=setInterval(()=>{if(!document.hidden)load();},15000);const visible=()=>{if(!document.hidden)load();};document.addEventListener('visibilitychange',visible);return()=>{mounted.current=false;clearInterval(timer);controller.current?.abort();document.removeEventListener('visibilitychange',visible);};},[api]);
 const rows=compact?(data?.items||[]).filter(r=>r.bucket!=='recent').slice(0,4):activityRows(data,filter,query);
 const counts=data?.counts||{};
 return <section className={compact?'workspace-panel activity-compact':'workspace-page activity-page'} aria-label={compact?'Work in progress':'Activity'}>
  <div className="workspace-section-heading activity-heading"><div><p className="workspace-eyebrow">ACROSS YOUR RESEARCH</p>{compact?<h2>Work in progress</h2>:<h1>Activity.</h1>}<p>{compact?'Your active jobs and anything needing attention.':'See what Charlie is working on, what is waiting, and what is ready to review.'}</p></div><button onClick={compact?()=>onNavigate('activity'):load} disabled={!compact&&loading}>{compact?'View all activity ↗':loading?'Refreshing…':'Refresh'}</button></div>
  {error&&<p role="alert" className="activity-warning">{error}</p>}
  {!!data?.unavailable?.length&&<p role="alert" className="activity-warning">Some activity is unavailable: {data.unavailable.join(', ')}. This is a partial snapshot.</p>}
  {!!data?.truncated?.length&&<p className="activity-warning">Showing the first 200 unfinished jobs in {data.truncated.join(', ')}. Open that workspace for more.</p>}
  {!compact&&<><div className="activity-counters" aria-label="Activity filters">{[['active','In progress'],['attention','Needs attention'],['recent','Recently finished']].map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}><strong>{data?counts[key]:'—'}</strong><span>{label}</span></button>)}</div><div className="activity-toolbar"><label>Find work <input aria-label="Find work" placeholder="Ticker or workflow" value={query} onChange={e=>setQuery(e.target.value)}/></label><p><span className={'activity-dot '+(macConnected(data?.agentLastSeen)?'connected':'')}/>{macConnected(data?.agentLastSeen)?'Mac connected':'Mac not reporting'} · {activityAge(data?.agentLastSeen)}</p></div></>}
  {!data&&!error&&<p role="status">Loading activity…</p>}
  {data&&!rows.length&&<p className="workspace-empty">{query?'No matching work.':compact?'No unfinished work in the available job records.':filter==='active'?'No work currently in progress.':filter==='attention'?'No jobs currently need attention.':'No recently finished work in the last 24 hours.'}</p>}
  <div className="activity-list">{rows.map(r=><article className={'activity-row activity-'+r.bucket} key={r.id}><div className="activity-company"><strong>{r.ticker||'GENERAL'}</strong><small>{r.title}</small></div><div className="activity-detail"><div className="activity-row-title"><strong>{r.step}</strong><span className="activity-status">{r.bucket==='attention'?'Needs attention':r.status.replaceAll('_',' ')}</span></div>{r.stages!=null&&<p>{r.stages}/12 research stages saved</p>}{r.warning&&<p className="activity-warning">{r.warning}</p>}{r.error&&<p className="activity-warning">{r.error}</p>}{r.stale&&<p className="activity-warning">No saved progress for {r.quietMinutes==null?'an unknown period':r.quietMinutes+' minutes'}. Open the job to inspect what is waiting.</p>}<small>Updated {activityAge(r.updatedAt)} · Started {activityAge(r.createdAt)}</small></div><button className="activity-open" onClick={()=>onNavigate(r.view,r.ticker)}>Open work ↗<span className="sr-only"> {r.ticker} {r.title}</span></button></article>)}</div>
  {data&&<p className="activity-foot">Snapshot {activityAge(data.asOf)} · Refreshes every 15 seconds while visible.{!compact&&<> {data.scope} Mac collection report: {activityAge(data.collectionLastSeen)}.</>}</p>}
 </section>;
}
