import * as React from 'react';
export function AssignmentWorkspace({api,id,onNavigate,onSection}) {
 const [open,setOpen]=React.useState(false),[data,setData]=React.useState(null),[error,setError]=React.useState('');
 React.useEffect(()=>{if(!open)return;let active=true;const load=async()=>{try{const r=await fetch(api+'/api/research/assignments/'+id,{signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Assignment unavailable');if(active){setData(d);setError('');}}catch(e){if(active)setError(e.message);}};load();const timer=setInterval(load,10000);return()=>{active=false;clearInterval(timer);};},[open,id,api]);
 return <div className="assignment-workspace"><button onClick={()=>setOpen(!open)}>{open?'Close assignment workspace':'Inspect assignment →'}</button>{open&&<section aria-label="Assignment workspace">{error&&<p role="alert">{error}</p>}{data&&<><h3>{data.command.ticker} · Assignment workspace</h3><details className="assignment-brief"><summary>Full assignment and focus areas</summary><p>{data.assignment.instruction}</p></details><p>{data.assignment.since} through {data.assignment.until}</p><ol><li>Command: {data.command.status}</li><li>Collection: {data.sourceReuse?'Verified saved sources · no new search':data.collection?.status||'awaiting Mac snapshot'}</li><li>Preparation: {data.preparation?.status||'not started'} · {data.preparation?.stage||'waiting for verified sources'}</li></ol>{(data.collection?.issue||data.preparation?.error||data.command.error)&&<p role="alert">{data.collection?.issue||data.preparation?.error||data.command.error}</p>}
 {data.collection?.sourceProgress&&<details open><summary>Collection progress</summary><p>{(data.collection.sourceProgress.documents.handed_off||0)+(data.collection.sourceProgress.documents.duplicate||0)} originals saved to iCloud · {data.collection.sourceProgress.documents.staged||0} awaiting handoff · {data.collection.sourceProgress.documents.held||0} held</p>{data.collection.sourceProgress.tasks.map(t=><p key={t.kind}>{t.kind.replaceAll('-',' ')} · {t.status.replaceAll('_',' ')}{t.expected!=null?` · ${t.expected} selected`:''}</p>)}<p>Meeting originals appear below after collection and the analyst brief finish.</p></details>}
 {data.selection&&<details><summary>Selected sources and decisions</summary>{data.selection.candidates.map(c=><p key={c.url}><strong>{c.decision}</strong> · {c.publisher} · {c.title}<br/>{c.reason}</p>)}</details>}
 <details><summary>{data.documents.length} meeting originals · {data.preparation?.cachedSources||0} analyses reused</summary>{data.documents.map(d=><p key={d.filename}>{d.filename}</p>)}</details>
 <details><summary>{data.versions.length} saved meeting versions</summary>{data.versions.map(v=><p key={v.id}>Version {v.version} · {v.status} · {new Date(v.created_at).toLocaleString()} · {v.generation_model}</p>)}</details>
 {data.assignment.sourcePolicy&&<details><summary>Frozen source preferences</summary><p>Mode: {data.assignment.sourcePolicy.mode}</p>{data.assignment.sourcePolicy.rules.map((r,i)=><p key={i}>{r.name} · {r.analyst||'all analysts'} · {r.ticker||r.subsector||'all companies'} · {r.disposition}</p>)}</details>}
 {data.meetingId&&<button onClick={()=>{window.dispatchEvent(new CustomEvent('charlie-open-meeting',{detail:{id:Number(data.meetingId)}}));onNavigate('meetingprep');}}>Open questions and supporting passages →</button>}<button onClick={()=>onSection('collection')}>Collection controls</button><button onClick={()=>onNavigate('analysts')}>Open analyst inbox</button></>}</section>}</div>;
}
