import * as React from 'react';
import {defaultRules,pressure,retention,falsification,variant,divergence} from './case-signals-model.mjs';
const today=()=>new Date().toISOString().slice(0,10);
const blank=()=>({observations:[],tests:[],variants:[],position:{conviction:'unknown'}});
const fmt=n=>n==null?'—':Number(n).toLocaleString(undefined,{maximumFractionDigits:2});
export function CaseSignals({api,body,disabled,onChange,onSave,message}){
 const s={...blank(),...body.signals},assumptions=body.assumptions||[];
 const [framework,setFramework]=React.useState(null),[error,setError]=React.useState('');
 React.useEffect(()=>{let live=true;const load=async()=>{try{const r=await fetch(api+'/api/research/investor-framework',{signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Doctrine unavailable');if(live){setFramework(d);setError('');}}catch(e){if(live)setError(e.message);}};load();window.addEventListener('charlie-framework-saved',load);return()=>{live=false;window.removeEventListener('charlie-framework-saved',load);};},[api]);
 const rules=framework?.body?.decayRules||defaultRules;
 const pillars=pressure(assumptions,s.observations,rules),position=divergence(s.position,pillars);
 const update=next=>onChange({...body,signals:next});
 const rowEdit=(key,id,field,value)=>update({...s,[key]:s[key].map(r=>r.id===id?{...r,[field]:value}:r)});
 const remove=(key,id)=>update({...s,[key]:s[key].filter(r=>r.id!==id)});
 const add=(key,extra={})=>update({...s,[key]:[...s[key],{id:crypto.randomUUID(),assumptionId:assumptions[0]?.id||'',...extra}]});
 const input=(label,value,change,type='text')=><label>{label}<input type={type} step={type==='number'?'any':undefined} value={value??''} onChange={e=>change(e.target.value)}/></label>;
 const select=(label,value,change,options)=><label>{label}<select value={value||''} onChange={e=>change(e.target.value)}>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>;
 const editor=(key,r)=>({field:(k,label,type='text')=>input(label,r[k],v=>rowEdit(key,r.id,k,v),type),choice:(k,label,options)=>select(label,r[k],v=>rowEdit(key,r.id,k,v),options)});
 const assumptionSelect=(key,r)=>select('Linked pillar',r.assumptionId,v=>rowEdit(key,r.id,'assumptionId',v),assumptions.map(a=>[a.id,a.claim]));
 return <section className="case-signals" aria-label="Case signals"><header><p className="workspace-eyebrow">CASE SIGNALS / EVIDENCE & JUDGMENT</p><h2>Where does the case need attention?</h2><p>Transparent diagnostics from your classified evidence and dated inputs. Save these annotations as an investment-case revision. No trades or weight recommendations.</p></header><nav className="signals-jump" aria-label="Case signal sections">{['Pillar pressure','Evidence half-life','Falsification','Variant view','Position alignment'].map((label,i)=><a href={'#case-signal-'+i} key={label} onClick={e=>{e.preventDefault();document.getElementById('case-signal-'+i)?.scrollIntoView({behavior:'smooth',block:'start'});}}>{label}</a>)}</nav>
 {!assumptions.length&&<p role="status">Add and save a thesis assumption first.</p>}
 {error&&<p role="alert">{error}. Decay calculations below use the labeled defaults until doctrine loads.</p>}
 <section className="signals-section" id="case-signal-0"><h3>1. Pillar pressure map</h3><p>Each active observation contributes one evidence unit, adjusted for age. Counts are not independent corroboration or a probability. Repeated reports of the same development should be one observation.</p>
 <div className="signals-grid">{pillars.map(p=><article key={p.id} className="signal-card"><h4>{p.claim}</h4><div className="signal-totals"><span>Support <strong>{fmt(p.support)}</strong></span><span>Challenge <strong>{fmt(p.challenge)}</strong></span></div><div className="signal-bar" aria-label={`${fmt(p.support)} supporting and ${fmt(p.challenge)} challenging retained units`}><span style={{width:`${p.support+p.challenge?p.support/(p.support+p.challenge)*100:0}%`}}/></div><p>{p.rows.length?`${p.unresolved} active challenging observation(s). Aging does not resolve them.`:'No observations assessed. Pressure is unknown.'}</p><ul>{p.targets.map(t=><li key={t.type}>{t.type}: {t.support} supporting / {t.challenge} challenging</li>)}</ul></article>)}</div>
 <details><summary>Assess evidence · {s.observations.length} observations</summary><fieldset disabled={disabled||!assumptions.length}>{(body.evidenceLinks||[]).length>0&&<details><summary>Start from accepted source passages</summary>{body.evidenceLinks.map((link,i)=><button key={i} disabled={s.observations.length>=200||!assumptions.some(a=>a.id===link.assumptionId)} onClick={()=>{const refs=link.evidence||[];add('observations',{assumptionId:link.assumptionId,statement:refs.map(e=>e.excerpt).join('\n'),source:refs.map(e=>e.source?.filename||e.sourceId).join('; '),asOf:'',targetType:'pillar',targetLabel:'',direction:'neutral',kind:'event',status:'active'});}}>Assess accepted passage {i+1}</button>)}<p>Enter the source observation date and your assessment. A saved citation is not automatically supporting or challenging.</p></details>}
 {s.observations.map((r,i)=>{const e=editor('observations',r);return <article key={r.id} className="signal-editor"><h4>Observation {i+1}</h4>{assumptionSelect('observations',r)}<div className="signals-grid">{e.choice('targetType','What is affected?',[['pillar','Pillar'],['signpost','Signpost'],['estimate','Estimate'],['risk','Risk']])}{e.field('targetLabel','Specific signpost, estimate or risk')}{e.choice('direction','Your assessment',[['neutral','Neutral / unresolved'],['support','Supports the case'],['challenge','Challenges the case']])}{e.choice('kind','Evidence lifetime',[['event','Time-sensitive event'],['cyclical','Cyclical development'],['structural','Structural evidence']])}{e.field('asOf','Observation date','date')}{e.choice('status','Status',[['active','Active'],['retired','Resolved / superseded — retain history']])}</div><label>Source statement / assessment<textarea value={r.statement||''} onChange={ev=>rowEdit('observations',r.id,'statement',ev.target.value)}/></label>{e.field('source','Source reference · original, page / passage')}<button onClick={()=>remove('observations',r.id)}>Remove observation from this version</button></article>;})}
 <button disabled={s.observations.length>=200} onClick={()=>add('observations',{targetType:'pillar',direction:'neutral',kind:'event',status:'active',asOf:today()})}>Add evidence assessment</button></fieldset></details></section>
 <section className="signals-section" id="case-signal-1"><h3>2. Evidence half-life</h3><p>{framework?.body?.decayRules?`Analyst Doctrine / framework v${framework.revision}`:'Preview defaults · save explicit rules in My investment framework / Analyst Doctrine above'}: event {rules.event} days; cyclical {rules.cyclical} days; structural evidence persists until retired. Retention = ½ ^ (age ÷ half-life). This measures relevance under your policy, not truth or confidence.</p><ul>{s.observations.map((r,i)=><li key={r.id}><strong>Observation {i+1}</strong> · {r.kind} · {r.status==='retired'?'Retired':`${fmt(retention(r,rules)*100)}% retained`} · {r.statement?.slice(0,160)||'Draft assessment'}{!r.asOf?' · Observation date required':''}</li>)}</ul></section>
 <section className="signals-section" id="case-signal-2"><h3>3. Falsification dashboard</h3><p>State what would disprove each pillar. Distance is in the entered unit; it is not a forecast or standardized risk score. A stale observation does not establish a current threshold breach.</p><fieldset disabled={disabled||!assumptions.length}>{s.tests.map(r=>{const e=editor('tests',r),v=falsification(r);return <article className="signal-editor" key={r.id}>{assumptionSelect('tests',r)}{e.field('question','What would prove this wrong?')}<p className="signal-result"><strong>{v.status}</strong>{v.distance!==null&&<> · {fmt(Math.abs(v.distance))} {r.unit} {v.distance<=0?'beyond / at threshold':'remaining to threshold'}</>}</p><details><summary>Observation, threshold and evidence needed</summary><div className="signals-grid">{e.field('metric','Metric')}{e.field('unit','Unit · e.g. %, USD/share')}{e.field('period','Comparable fiscal period / basis')}{e.field('current','Current observed value','number')}{e.choice('operator','Disprove if observation is',[['lte','At or below threshold'],['gte','At or above threshold']])}{e.field('threshold','Threshold','number')}{e.field('asOf','Observation as of','date')}{e.field('source','Original source reference')}</div>{e.field('needed','Evidence needed to resolve uncertainty')}<button onClick={()=>remove('tests',r.id)}>Remove test from this version</button></details></article>;})}<button disabled={s.tests.length>=60} onClick={()=>add('tests',{operator:'lte'})}>Add falsification test</button></fieldset></section>
 <section className="signals-section" id="case-signal-3"><h3>4. Variant-perception tracker</h3><p>Separate a positive business view from a view the market may not reflect. Estimate gaps do not establish mispricing. Pricing status below is your explicit interpretation; broker baselines are labeled separately from consensus.</p><fieldset disabled={disabled||!assumptions.length}>{s.variants.map(r=>{const e=editor('variants',r),v=variant(r);return <article className="signal-editor" key={r.id}>{assumptionSelect('variants',r)}<div className="signals-grid">{e.field('metric','Metric')}{e.field('unit','Unit')}{e.field('period','Same forecast period / accounting basis')}{e.field('view','My estimate','number')}{e.field('market','Stated market / broker estimate','number')}{e.choice('baselineType','Baseline type',[['unknown','Not established'],['consensus','Documented consensus aggregation'],['broker','Single broker — not consensus'],['implied','Explicit market-implied calculation']])}{e.field('asOf','Baseline as of','date')}{e.field('source','Baseline source / calculation reference')}{e.choice('pricing','My pricing assessment',[['unknown','Not established'],['reflected','Already reflected'],['not_reflected','Not reflected — my interpretation']])}</div><p className="signal-result">{v.status}{v.delta!==null&&<> · My estimate minus baseline: {fmt(v.delta)} {r.unit}{v.percent!==null?` (${fmt(v.percent)}%)`:''}</>}</p><label>Why I think it is / is not reflected<textarea value={r.rationale||''} onChange={ev=>rowEdit('variants',r.id,'rationale',ev.target.value)}/></label><button onClick={()=>remove('variants',r.id)}>Remove comparison from this version</button></article>;})}<button disabled={s.variants.length>=60} onClick={()=>add('variants',{baselineType:'unknown',pricing:'unknown'})}>Add variant comparison</button></fieldset></section>
 <section className="signals-section" id="case-signal-4"><h3>5. Position–conviction divergence</h3><p>User-entered position snapshot; no live holdings feed. Weights are percentages, active weight is percentage points. Holdings older than 30 days require refresh.</p><fieldset disabled={disabled}><div className="signals-grid">{[['portfolio','Portfolio / mandate','text'],['benchmark','Benchmark','text'],['weight','Portfolio weight %','number'],['benchmarkWeight','Benchmark weight %','number'],['asOf','Weights as of','date']].map(([k,l,t])=><React.Fragment key={k}>{input(l,s.position[k],v=>update({...s,position:{...s.position,[k]:v}}),t)}</React.Fragment>)}{select('Case conviction · your assessment',s.position.conviction,v=>update({...s,position:{...s.position,conviction:v}}),[['unknown','Not assessed'],['low','Low'],['medium','Medium'],['high','High']])}</div><p>Active weight: <strong>{fmt(position.active)} pp</strong></p><ul>{position.questions.map(q=><li key={q}>{q}</li>)}</ul><label>Position rationale / constraints<textarea value={s.position.rationale||''} onChange={e=>update({...s,position:{...s.position,rationale:e.target.value}})}/></label></fieldset></section>
 <div className="signal-save"><button className="workspace-primary" disabled={disabled||!assumptions.length} onClick={()=>onSave()}>Save signals with investment case</button><p role="status">{message||'Annotations remain a draft until saved. Previous versions are retained in case history.'}</p></div>
 </section>;
}
