import * as React from 'react';
import {parseTickers} from './research-desk-model.mjs';
export function CatalystWatch({api,policies}) {
  const [data,setData]=React.useState(null),[error,setError]=React.useState(''),[message,setMessage]=React.useState(''),[busy,setBusy]=React.useState(false);
  const [enabled,setEnabled]=React.useState(false),[automatic,setAutomatic]=React.useState(false),[tickers,setTickers]=React.useState(''),[limit,setLimit]=React.useState(10);
  const dirty=React.useRef(false),lock=React.useRef(false),alive=React.useRef(true);
  const json=async options=>{const r=await fetch(`${api}/api/research/catalyst-watch`,{...options,signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||`Catalyst detection unavailable (${r.status})`);return d;};
  const refresh=async()=>{try{const d=await json();if(!alive.current)return;setData(d);setError('');if(!dirty.current){setEnabled(d.config.enabled);setAutomatic(d.config.automatic);setTickers(d.config.tickers.join(', '));setLimit(d.config.dailyLimit);}}catch(e){if(alive.current)setError(e.message);}};
  React.useEffect(()=>{alive.current=true;refresh();const timer=setInterval(()=>{if(!document.hidden)refresh();},30000);return()=>{alive.current=false;clearInterval(timer);};},[api]);
  const parsed=parseTickers(tickers);
  const edit=fn=>{dirty.current=true;fn();};
  const save=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{const d=await json({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled,automatic,tickers:parsed.tickers,dailyLimit:limit})});if(alive.current){setData(d);dirty.current=false;setMessage('Catalyst watch settings saved. New signals appear below as the Mac checks each company.');}}catch(e){if(alive.current)setMessage(`Save not confirmed: ${e.message}. Refresh status before retrying.`);}finally{lock.current=false;if(alive.current)setBusy(false);}};
  return <details className="workspace-panel"><summary>Event-driven research · catalyst watch</summary><h3>Investigate new developments as they appear.</h3><p>Company-news headlines are screened for clinical results, regulatory decisions, guidance and corporate transactions. Matches are potential catalysts, not verified investment conclusions. Primary-source confirmation happens in the subsequent research.</p>{error&&<p className="workspace-error" role="alert">{error}</p>}
    {data&&<><p>{data.scope}</p>{!data.hasNewsKey&&<p className="workspace-error">Set the Finnhub key in Settings to enable news detection.</p>}{data.config.lastIssue&&<p role="status">{data.config.lastIssue}</p>}<fieldset disabled={busy} className="desk-form"><label><input type="checkbox" checked={enabled} onChange={e=>edit(()=>setEnabled(e.target.checked))}/>Monitor new events</label><label><input type="checkbox" checked={automatic} onChange={e=>edit(()=>setAutomatic(e.target.checked))}/>Automatically queue AlphaSense collection and an analyst recap draft</label><label>Watched tickers<textarea rows={3} value={tickers} onChange={e=>edit(()=>setTickers(e.target.value))}/></label><button onClick={()=>edit(()=>setTickers(policies.filter(p=>p.enabled).map(p=>p.ticker).join(', ')))}>Use active collection coverage</button><label>Maximum automatic event requests per UTC day<input type="number" min="1" max="30" value={limit} onChange={e=>edit(()=>setLimit(Number(e.target.value)))}/></label><p>{parsed.tickers.length} watched companies · {data.config.used||0} event requests counted on {data.config.day||'no day yet'}. Signals above the limit remain visible for manual research; they are not silently backfilled.</p><button className="workspace-primary" disabled={!parsed.tickers.length||!!parsed.invalid.length||parsed.tickers.length>100} onClick={save}>Save catalyst watch</button></fieldset><p role="status">{message}</p><button onClick={refresh}>Refresh detection status</button><p>Last lookup: {data.config.lastTicker||'None'} · {data.config.lastCheck?new Date(data.config.lastCheck*1000).toLocaleString():'Not checked yet'}</p>
    {(data.events||[]).map(e=><article className="amendment-card" key={e.id}><strong>{e.ticker} · {e.status.replaceAll('_',' ')}</strong><p>{e.input?.title}</p><p>{e.input?.reason}</p>{typeof e.input?.url==='string'&&e.input.url.startsWith('https://')&&<a href={e.input.url} target="_blank" rel="noopener noreferrer">Read original news →</a>}<p>{e.result?.reason||`Collection command: ${e.result?.commandId||'Not queued'}`}</p></article>)}{!data.events?.length&&<p>No new qualifying signals have been recorded since monitoring was enabled.</p>}</>}
  </details>;
}
