import {AssignmentWorkspace} from './assignment-workspace';
import {SourcePreferences} from './source-preferences';
import {MeetingCommand} from './meeting-command';
import * as React from 'react';
import {ThesisAmendments} from './thesis-amendments';
const kinds=[['filing','8-K and reaction'],['earnings','Earnings review'],['event','Event investigation']];
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
function ResearchCommand({api,onNavigate,onSection,sourcePolicy}) {
  const [ticker,setTicker]=React.useState(''),[date,setDate]=React.useState(today),[kind,setKind]=React.useState('filing'),[days,setDays]=React.useState(1),[coordinated,setCoordinated]=React.useState(true),[autoProposal,setAutoProposal]=React.useState(false),[instruction,setInstruction]=React.useState('');
  const [fav,setFav]=React.useState({favorites:[],revision:''}),[favId,setFavId]=React.useState(''),[name,setName]=React.useState(''),[jobs,setJobs]=React.useState([]);
  const [error,setError]=React.useState(''),[favoriteError,setFavoriteError]=React.useState(''),[macDate,setMacDate]=React.useState(null),[message,setMessage]=React.useState(''),[busy,setBusy]=React.useState(false),[uncertain,setUncertain]=React.useState(false);
  const [comparison,setComparison]=React.useState(null),[comparisonError,setComparisonError]=React.useState('');
  const comparisonSequence=React.useRef(0),comparisonPanel=React.useRef(null);
  React.useEffect(()=>{if(comparison){comparisonPanel.current?.scrollIntoView({behavior:'smooth',block:'start'});comparisonPanel.current?.focus();}},[comparison]);
  const alive=React.useRef(true),lock=React.useRef(false),pending=React.useRef(null);
  const json=async(path,options={})=>{const r=await fetch(`${api}${path}`,{...options,signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok){const e=Error(d.error||`Request failed (${r.status})`);e.status=r.status;throw e;}return d;};
  const openComparison=async j=>{const seq=++comparisonSequence.current;setComparison(null);setComparisonError('Loading command sources…');try{const context=await json(`/api/research/commands/${j.id}/thesis-context`);if(alive.current&&seq===comparisonSequence.current){setComparison({id:j.id,context});setComparisonError('');}}catch(e){if(alive.current&&seq===comparisonSequence.current)setComparisonError(e.message);}};
  const refresh=async()=>{try{const d=await json('/api/research/commands');if(alive.current){setJobs(d.jobs);setMacDate(d.macReportedAt);setError('');if(pending.current&&d.jobs.some(j=>j.id===pending.current.requestId)){pending.current=null;setUncertain(false);setMessage('Task recorded. Follow its progress below.');}}}catch(e){if(alive.current)setError(e.message);}};
  React.useEffect(()=>{alive.current=true;refresh();json('/api/research/command-favorites').then(d=>{if(alive.current)setFav(d);}).catch(e=>{if(alive.current)setFavoriteError(e.message);});const timer=setInterval(()=>{if(!document.hidden)refresh();},10000);return()=>{alive.current=false;clearInterval(timer);};},[api]);
  const pick=f=>{setFavId(f.id);setName(f.name);setInstruction(f.instruction);setKind(f.kind);setDays(f.days);setCoordinated(f.coordinated===true);setAutoProposal(f.autoProposal===true);};
  const run=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('Submitting task…');const body=pending.current||{requestId:crypto.randomUUID(),ticker:ticker.trim().toUpperCase(),date,kind,days,instruction,coordinated,autoProposal,sourcePolicy};pending.current=body;
    try{const d=await json('/api/research/commands',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});pending.current=null;setUncertain(false);setMessage(`Task queued for ${d.plan.ticker}: ${d.plan.since} through ${d.plan.until}. You can close this page and return to its saved status.`);await refresh();}
    catch(e){setMessage(`Submission not confirmed: ${e.message}`);if(e.status)pending.current=null;else setUncertain(true);await refresh();}finally{lock.current=false;if(alive.current)setBusy(false);}};
  const save=async remove=>{if(lock.current)return;lock.current=true;setBusy(true);try{const row={id:favId||crypto.randomUUID(),name,instruction,kind,days,coordinated,autoProposal};const values=remove?fav.favorites.filter(f=>f.id!==favId):[...fav.favorites.filter(f=>f.id!==row.id),row];const d=await json('/api/research/command-favorites',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:fav.revision,favorites:values})});setFav(d);setFavId(remove?'':row.id);setMessage(remove?'Favorite removed.':'Favorite saved across your devices.');}catch(e){setMessage(e.message);if(e.status===409)setFav(await json('/api/research/command-favorites'));}finally{lock.current=false;setBusy(false);}};
  return <section className="workspace-panel command-charlie"><p className="workspace-eyebrow">COMMAND CHARLIE</p><h2>Give the team a research assignment.</h2><p className="desk-explainer">Start with a repeatable workflow or write your own instructions. The ticker, event date and collection window below define the task. Collection starts when the Mac browser worker picks it up; research drafts remain subject to review.</p>
    <div className="command-favorites">{fav.favorites.map(f=><button key={f.id} aria-pressed={favId===f.id} disabled={busy||uncertain} onClick={()=>pick(f)}><strong>{f.name}</strong><small>{kinds.find(k=>k[0]===f.kind)?.[1]} · {f.days} day{f.days===1?'':'s'}</small></button>)}</div>
    <fieldset disabled={busy||uncertain} className="desk-form"><div className="desk-filter"><label>Ticker<input value={ticker} maxLength={20} onChange={e=>setTicker(e.target.value.toUpperCase())} placeholder="UNH"/></label><label>Event date (New York)<input type="date" value={date} max={today()} onChange={e=>setDate(e.target.value)}/></label><label>Lookback days<input type="number" min="1" max="90" value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label>Research workflow<select value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label></div>
    <label>Your assignment<textarea rows={5} maxLength={3000} value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="Review UNH’s 8-K today and sell-side reaction. Explain what changed and propose updates to my thesis."/></label>
    {instruction&&<p><strong>Assignment preview:</strong> {instruction.replace(/\{ticker\}/g,ticker.trim()||'[choose ticker]').replace(/\{date\}/g,date||'[choose date]')}</p>}
    <p>SEC EDGAR filings + AlphaSense press releases, broker research and transcripts → CATALYSTS event folder → covering analyst recap. Missing sources and retrieval failures are reported explicitly. Thesis changes are proposed for your review, not automatically applied.</p>
    <label className="command-team-option"><input type="checkbox" checked={coordinated} onChange={e=>setCoordinated(e.target.checked)}/><span>Include independent challenge and editorial revision <small>Up to two additional model passes. Final selected-claim source review follows.</small></span></label>
    <label className="command-team-option"><input type="checkbox" checked={autoProposal} onChange={e=>setAutoProposal(e.target.checked)}/><span>Prepare thesis updates automatically after the recap <small>Uses model credits for a source-checked proposal from up to 10 verified originals. You still choose which edits to apply. Requires the Mac heartbeat and a server research key.</small></span></label>
    <button className="workspace-primary" disabled={!sourcePolicy||!ticker.trim()||!instruction.trim()} onClick={run}>Run research task ↗</button>
    <details><summary>Save or edit a repeatable favorite</summary><p>Use {'{ticker}'} and {'{date}'} in the instruction to reuse it for another company or event date.</p><label>Favorite name<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><button disabled={!name.trim()||!instruction.trim()} onClick={()=>save(false)}>Save favorite</button><button onClick={()=>{setFavId('');setName('');}}>Start a new favorite</button>{favId&&<button disabled={fav.favorites.length<=1} onClick={()=>save(true)}>Remove selected favorite</button>}</details></fieldset>
    {uncertain&&<button disabled={busy} onClick={run}>Retry same task request</button>}{favoriteError&&<p role="alert" className="workspace-error">Favorites: {favoriteError}</p>}{error&&<p role="alert" className="workspace-error">{error}</p>}{message&&<p role="status">{message}</p>}
    {comparisonError&&<p role="status">{comparisonError}</p>}{comparison&&<div ref={comparisonPanel} tabIndex={-1} aria-label="Command thesis comparison"><button onClick={()=>{comparisonSequence.current++;setComparison(null);}}>Close thesis comparison</button><ThesisAmendments key={comparison.id} api={api} ticker={comparison.context.bridge.ticker} context={comparison.context} onApplied={refresh}/></div>}
    <div className="workspace-section-heading"><h3>Task history</h3><button onClick={refresh}>Refresh tasks</button></div><p>Mac last reported: {macDate?new Date(macDate).toLocaleString():'not yet available'}. Tasks wait for an available, signed-in browser worker.</p>{!jobs.length&&<p>{error?'Task history is unavailable. Retry when the connection returns.':'No research assignments have been submitted yet.'}</p>}
    {jobs.map(j=><article className="amendment-card" key={j.id}><AssignmentWorkspace api={api} id={j.id} onNavigate={onNavigate} onSection={onSection}/><div className="workspace-section-heading"><h3>{j.ticker} · {j.input.payload.kind} research</h3><span className="desk-status">{j.collection?.status||j.status}</span></div><p>{j.input.payload.instruction}</p><p>{j.input.payload.since} through {j.input.payload.until}</p><p>Mac command: {j.status}{j.collection?` · Browser collection: ${j.collection.status}`:j.status==='applied'?' · Browser status absent from the latest Mac snapshot':' · Awaiting Mac acknowledgement'}</p>{j.collection?.result?.research&&typeof j.collection.result.research==='string'&&<p>{j.collection.result.research}</p>}{j.error&&<p className="workspace-error">{j.error}</p>}{j.collection?.issue&&<p className="workspace-error">{j.collection.issue}</p>}<p>{j.reports?.length?j.reports.map(r=>`${r.has_report?'Recap available':r.status} (${r.id.slice(0,8)})${r.recovery_attempts?` · Recovery ${r.recovery_attempts}/2`:''}${!r.has_report&&r.current_step?` · ${r.current_step}`:''}`).join(' · '):'No linked analyst recap is available yet.'}</p>{j.reports?.some(r=>r.roles?.length)&&<p>Team stages: {j.reports.flatMap(r=>r.roles||[]).map(r=>`${r.role}: ${r.status.replaceAll('_',' ')}`).join(' · ')}</p>}{j.input.payload.autoProposal&&<p role="status">Thesis proposal: {j.proposal?j.proposal.status.replaceAll('_',' '):j.proposalAutomation?.result?.message||'Waiting for completed research and verified sources.'}{j.proposal?.error?` · ${j.proposal.error}`:''}</p>}<details><summary>Execution plan and limits</summary><ol>{j.input.payload.steps.map(s=><li key={s}>{s}</li>)}</ol>{j.input.payload.limitations.map(s=><p key={s}>{s}</p>)}</details>{j.reports?.some(r=>r.has_report)&&<button className="workspace-primary" onClick={()=>openComparison(j)}>Compare command sources with thesis →</button>}<button onClick={()=>onSection('collection')}>Collection and recovery controls →</button><button onClick={()=>onNavigate('analysts')}>Open Analyst inbox →</button></article>)}
  </section>;
}

export function CommandCharlie(props) {
  const [sourcePolicy,setSourcePolicy]=React.useState(null);
  const [intent,setIntent]=React.useState('meeting');
  return <><SourcePreferences api={props.api} onChange={setSourcePolicy}/><div className="command-intents" aria-label="Choose an assignment"><button aria-pressed={intent==='meeting'} onClick={()=>setIntent('meeting')}><strong>Prepare for a meeting</strong><span>One company or a conference list · guided setup</span></button><button aria-pressed={intent==='research'} onClick={()=>setIntent('research')}><strong>Investigate & update research</strong><span>Filings, earnings, catalysts and saved favorites</span></button></div>{intent==='meeting'?<MeetingCommand {...props} sourcePolicy={sourcePolicy}/>:<ResearchCommand {...props} sourcePolicy={sourcePolicy}/>}</>;
}
