import * as React from 'react';
import {companySnapshot,compareSnapshots,snapshotDocument} from './company-snapshot-model.mjs';

export function CompanySnapshot({ticker,versions,revision,disabled,onEdit,onUpdate,onModel}) {
 const [selected,setSelected]=React.useState(''),[baseline,setBaseline]=React.useState('');
 const version=versions.find(v=>String(v.revision)===(selected||String(revision)));
 const snapshot=companySnapshot(ticker,version);
 const earlier=versions.find(v=>String(v.revision)===baseline);
 const changes=earlier?compareSnapshots(companySnapshot(ticker,earlier),snapshot):[];
 const download=()=>{const url=URL.createObjectURL(new Blob([snapshotDocument(snapshot)],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${ticker}-investment-map-r${snapshot.revision}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section aria-label="Company snapshot" className="company-snapshot" style={{fontFamily:'Calibri, sans-serif',color:'#000'}}>
 <style>{`.company-snapshot{background:#fff;padding:20px;border-radius:12px}.company-snapshot *{color:#000!important;overflow-wrap:anywhere}.company-snapshot select,.company-snapshot button,.company-snapshot .workspace-panel{background:#f6f6f2!important;color:#000!important;max-width:100%}.company-snapshot select{width:100%}.company-snapshot label{min-width:0;max-width:100%}.company-snapshot .snapshot-actions{display:flex;flex-wrap:wrap;gap:12px;margin:20px 0;align-items:end}.company-snapshot .snapshot-actions label{flex:1 1 240px}.company-snapshot button{border:1px solid #aaa;padding:10px 14px;border-radius:6px}.company-snapshot button:disabled{opacity:.5}.company-snapshot h3{font-size:28px;margin:12px 0}.company-snapshot header{margin-bottom:20px}.company-snapshot>p{margin:16px 0}.company-snapshot>h4{margin-top:24px}.company-snapshot article,.company-snapshot aside{margin-bottom:16px}.company-snapshot h4{font-weight:700;margin-bottom:12px}.company-snapshot h5{font-weight:700;margin-top:16px}`}</style>
 <header><p className="workspace-eyebrow">SAVED RESEARCH / COMPANY SNAPSHOT</p><h3>The case, at a glance.</h3><p>A concise view of your saved working assumptions. Opening this view does not launch research.</p></header>
 {!version?<div className="workspace-panel"><h4>{revision?'Saved revision unavailable':'Start with your investment case'}</h4><p>{revision?'Reload the company to refresh its saved history.':'Create a case or load your existing thesis as a draft, then review and save it.'}</p><button disabled={disabled} onClick={onEdit}>Open current thesis</button></div>:<>
 <div className="snapshot-actions"><label>Saved version<select aria-label="Saved version" value={selected||String(revision)} onChange={e=>{setSelected(e.target.value);setBaseline('');}}>{versions.map(v=><option key={v.revision} value={v.revision}>Revision {v.revision} · {v.created_at?new Date(v.created_at).toLocaleString():'Date unavailable · refresh history'}</option>)}</select></label><button onClick={download}>Download investment map</button><button disabled={disabled} onClick={onEdit}>Edit current thesis</button><button disabled={disabled} onClick={onUpdate}>Update thesis · review new evidence</button></div>
 <p>Viewing revision {snapshot.revision}{snapshot.revision!==revision?' · historical snapshot':''}. Updates assess the latest saved case, revision {revision}, after you select sources. Downloaded maps retain the version shown here.</p>
 {disabled&&<p role="status">Unsaved edits or a save in progress: this Snapshot continues to show saved content. Save before preparing an update.</p>}
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,280px),1fr))',gap:16}}>{[['Investment thesis',snapshot.thesis],['Market expectations · investor recorded',snapshot.marketBaseline],['Where my view differs',snapshot.variantView],['What would change my mind',snapshot.changeConditions]].map(([label,text])=><article className="workspace-panel" key={label}><h4>{label}</h4><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{text||'Not recorded'}</p></article>)}</div>
 {snapshot.operatingModel?.results&&<section className="workspace-panel"><h4>Operating scenarios · saved with R{snapshot.revision}</h4><p>{snapshot.operatingModel.version} · FY{snapshot.operatingModel.targetYear} · analyst-entered inputs, not a forecast or verified consensus.</p><div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th>Scenario</th><th>Implied price ({snapshot.operatingModel.currency})</th><th>Price return</th></tr></thead><tbody>{Object.entries(snapshot.operatingModel.results).map(([name,result])=><tr key={name}><th>{name}</th><td>{result.impliedPrice}</td><td>{result.priceReturnPct}%</td></tr>)}</tbody></table></div><p>Inputs, formulas and limitations travel with this revision’s investment-map export.</p><button disabled={disabled} onClick={onModel}>Open current operating model</button></section>}
 <h4>Assumptions → evidence → next test</h4><p>Classification is investor recorded. Saved excerpts establish provenance, not truth or currentness.</p>
 {snapshot.assumptions.map(a=><article className="workspace-panel" key={a.id}><h4>{a.claim}</h4><p>{String(a.evidenceType||'interpretation').replaceAll('_',' ')}</p><dl>{[['Supports',a.support],['Challenges',a.contrary],['Next test',a.nextTest],['Manual source reference · unverified',a.sourceReference]].map(([label,text])=><React.Fragment key={label}><dt><strong>{label}</strong></dt><dd style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',margin:'4px 0 16px'}}>{text||'Not recorded'}</dd></React.Fragment>)}</dl><details><summary>{a.evidence.length?`${a.evidence.length} current saved excerpt link(s)`:'No current saved excerpt links'}</summary>{a.evidence.map((e,i)=><blockquote key={i}><strong>{e.filename||'Source name unavailable'}</strong><p style={{whiteSpace:'pre-wrap'}}>{e.excerpt}</p><small>{e.provenance}</small></blockquote>)}</details></article>)}
 <aside className="workspace-panel"><h4>Coverage still to build</h4><p>{snapshot.gaps.length?snapshot.gaps.join(' · '):'All tracked case fields have content. This does not establish completeness or verification.'}</p><p>Full business, financial and 22-section research coverage is not assessed by this saved-case Snapshot.</p></aside>
 <section className="workspace-panel"><h4>What changed between saved cases?</h4><label>Compare with an earlier revision<select value={baseline} onChange={e=>setBaseline(e.target.value)}><option value="">Choose a baseline</option>{versions.filter(v=>v.revision<snapshot.revision).map(v=><option key={v.revision} value={v.revision}>Revision {v.revision}</option>)}</select></label>{earlier&&<><p>Revision {earlier.revision} → {snapshot.revision}. Saved wording and model changes; this does not infer why the investment case changed.</p>{!changes.length&&<p>No tracked thesis, assumption or operating-model changes.</p>}{changes.map((c,i)=><article key={i}><h5>{c.label}</h5><p style={{whiteSpace:'pre-wrap'}}>Before: {c.before||'Not recorded'}</p><p style={{whiteSpace:'pre-wrap'}}>After: {c.after||'Not recorded'}</p></article>)}</>}</section>
 </>}
 </section>;
}
