import * as React from 'react';
import {researchProgress,researchDocument,researchCaseDraft} from './company-research-model.mjs';

export function CompanyResearch({api,ticker,revision,disabled,onUpdate,onDraft}) {
 const [inventory,setInventory]=React.useState(null),[error,setError]=React.useState(''),[notice,setNotice]=React.useState('');
 const [selected,setSelected]=React.useState(''),[run,setRun]=React.useState(null),[files,setFiles]=React.useState([]),[confirmed,setConfirmed]=React.useState(false),[ack,setAck]=React.useState(false),[busy,setBusy]=React.useState(false),[view,setView]=React.useState('snapshot'),[refresh,setRefresh]=React.useState(0);
 const pending=React.useRef(null),mutation=React.useRef(false),alive=React.useRef(true);
 React.useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const json=async(path,options={})=>{const res=await fetch(api+path,{...options,signal:AbortSignal.timeout(30000)});const data=await res.json();if(!res.ok)throw Error(data.error||'Research unavailable');return data;};
 React.useEffect(()=>{let live=true,inflight=false;const load=async()=>{if(inflight)return;inflight=true;try{const d=await json('/api/research/company/'+encodeURIComponent(ticker));if(live){setInventory(d);setError('');setSelected(old=>old||d.runs[0]?.id||'');}}catch(e){if(live)setError(e.message);}finally{inflight=false;}};load();const timer=setInterval(load,15000);return()=>{live=false;clearInterval(timer);};},[api,ticker,refresh]);
 React.useEffect(()=>{let live=true,inflight=false;setRun(null);setAck(false);if(!selected)return;const load=async()=>{if(inflight)return;inflight=true;try{const d=await json('/api/research/company-run/'+encodeURIComponent(selected));if(live)setRun(d);}catch(e){if(live)setNotice(e.message);}finally{inflight=false;}};load();const timer=setInterval(load,5000);return()=>{live=false;clearInterval(timer);};},[api,selected,refresh]);
 const key=()=>{try{return localStorage.getItem('equity_analyzer_api_key')||'';}catch{return '';}};
 const mutate=async(path,payload,success)=>{if(mutation.current)return;mutation.current=true;setBusy(true);setNotice('Submitting…');try{const d=await json(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,apiKey:key()})});if(alive.current){success?.(d);setRefresh(x=>x+1);setNotice('Request saved. Progress and partial work appear below.');}}catch(e){if(alive.current)setNotice(e.message+' Check saved runs before retrying; unchanged submissions reuse the same request.');}finally{mutation.current=false;if(alive.current)setBusy(false);}};
 const start=()=>{const input={filenames:[...files].sort(),revision,confirmed};const signature=JSON.stringify(input);if(pending.current?.signature!==signature)pending.current={signature,payload:{...input,requestId:crypto.randomUUID()}};mutate('/api/research/company/'+ticker,pending.current.payload,d=>{setSelected(d.id);pending.current=null;});};
 const stats=researchProgress(run),sourceById=new Map((run?.sources||[]).map(s=>[s.id,s]));
 const download=compact=>{const url=URL.createObjectURL(new Blob([researchDocument(run,compact)],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${ticker}-research-${run.id}${compact?'-map':''}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const active=inventory?.runs.some(r=>['queued','running','attention'].includes(r.status));
 return <section className="company-research" aria-label="Source-backed company research"><style>{`.company-research{font-family:Calibri,sans-serif;background:#fff;color:#000;padding:24px;border-radius:12px}.company-research *{color:#000!important;overflow-wrap:anywhere}.company-research button,.company-research select{background:#f4f4ef!important;border:1px solid #aaa;border-radius:6px;padding:10px;max-width:100%}.company-research button:disabled{opacity:.5}.company-research h3{font-size:26px;margin:12px 0}.company-research h4{font-size:20px;font-weight:bold;margin:16px 0}.company-research p{margin:12px 0;white-space:pre-wrap}.company-research label{display:block;margin:12px 0}.company-research select{width:100%}.company-research article{padding:18px;border:1px solid #ccc;border-radius:8px;margin:16px 0}.company-research blockquote{padding:12px;border-left:3px solid #aaa}.company-research nav{display:flex;flex-wrap:wrap;gap:10px;margin:16px 0}.company-research input{margin-right:10px}.company-research summary{cursor:pointer;font-weight:700;margin:16px 0}`}</style>
 <p className="workspace-eyebrow">{ticker} / SOURCE-BACKED RESEARCH</p><h3>Build the research. Preserve the evidence.</h3><p>Deep Research uses selected originals already stored in Charlie. Each revision freezes its sources and case baseline, covers 22 sections, and reviews generated claims. It does not search the web or collect new documents.</p>
 {error&&<p role="alert">{error} <button onClick={()=>setRefresh(x=>x+1)}>Reload research</button></p>}
 <details open={!inventory?.runs.length}><summary>Prepare a new Deep Research revision</summary><p>Baseline: saved case R{revision}{!revision?' · initiation, no saved case yet':''}. Confirm the issuer in the originals; filing under a ticker alone does not establish identity.</p>
 <fieldset disabled={disabled||busy||!!error||!inventory||active}>
 <div style={{maxHeight:300,overflowY:'auto'}}>{inventory?.documents.map(d=><label key={d.filename}><input type="checkbox" checked={files.includes(d.filename)} disabled={!d.eligible||(!files.includes(d.filename)&&files.length>=8)} onChange={e=>{setFiles(old=>e.target.checked?[...old,d.filename]:old.filter(n=>n!==d.filename));setConfirmed(false);}}/>{d.filename}{!d.eligible?' · restricted for AI use':''}</label>)}</div>
 {!inventory?.documents.length&&<p>No stored originals found. Import permitted sources through Charlie’s collection workflow.</p>}
 <p>{files.length} / 8 sources selected · combined readable text limit: 160,000 characters. Missing coverage is recorded explicitly.</p>
 <label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked that these originals concern {ticker} and permit AI research.</label>
 <button disabled={!files.length||!confirmed||files.some(f=>!inventory?.documents.some(d=>d.filename===f&&d.eligible))} onClick={start}>Start Deep Research</button><p>Uses model credits: up to six research calls and six review calls, plus explicitly acknowledged retries. Monthly budget checks apply before each call. No automatic thesis changes.</p></fieldset>
 {disabled&&<p>Save your case edits before starting research.</p>}{active&&<p>An unfinished research revision already exists. Inspect it below, then resume or stop it before starting another.</p>}</details>
 <p role="status">{notice}</p>
 <label>Saved research revision<select aria-label="Saved research revision" value={selected} onChange={e=>{setSelected(e.target.value);setNotice('');}}><option value="">Choose research</option>{inventory?.runs.map(r=><option key={r.id} value={r.id}>{new Date(r.created_at).toLocaleString()} · {r.status} · case R{r.baseline.revision}</option>)}</select></label>
 {run&&<><p><strong>{run.status.replaceAll('_',' ')}</strong> · {stats.sections}/22 sections saved · {stats.stages}/12 stages · {stats.supported} claims passed excerpt and model checks · {stats.unresolved} unresolved</p><p>Research ID {run.id} · {run.model} · case baseline R{run.baseline.revision}</p>{run.error&&<p role="alert">{run.error}</p>}{run.baselineStale&&<p role="alert">Your case has changed to R{run.currentRevision}. This research retains baseline R{run.baseline.revision}; review the differences before using it.</p>}
 {run.status!=='complete'&&<><p>After an interruption, resume uses saved stages. A worker still processing a call will reject a second worker. Stopping takes effect after the current call; its usage may still be charged.</p>{run.state?.inFlight&&<label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>I checked provider usage and accept that retrying the interrupted call may incur another charge.</label>}<nav><button disabled={busy||!!run.state?.inFlight&&!ack} onClick={()=>mutate('/api/research/company-run/'+run.id+'/resume',{acknowledgeRetry:ack})}>Resume saved work</button><button disabled={busy||run.cancel_requested} onClick={()=>mutate('/api/research/company-run/'+run.id+'/stop',{})}>{run.cancel_requested?'Stop requested':'Stop research'}</button></nav></>}
 <nav aria-label="Research views">{[['snapshot','Snapshot'],['full','Full research'],['sources','Sources & baseline']].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}<button disabled={!stats.sections} onClick={()=>download(false)}>Download research</button><button disabled={run.status!=='complete'} onClick={()=>download(true)}>Download investment map</button><button disabled={disabled||!revision||run.status!=='complete'||run.baselineStale} onClick={()=>onUpdate({id:run.id,filenames:run.input.filenames})}>Update thesis · select evidence</button>{!revision&&run.status==='complete'&&!run.baseline.revision&&<button disabled={disabled||!stats.supported} onClick={()=>onDraft(researchCaseDraft(run,()=>crypto.randomUUID()))}>Prepare initial thesis draft · review before saving</button>}</nav>
 {view==='sources'?<><h4>Frozen originals</h4>{run.sources.map(s=><article key={s.id}><strong>{s.filename}</strong><p>Original hash: {s.originalHash}</p><p>Extraction hash: {s.extractionHash}</p><p>Observed URL: {s.sourceUrl||'Not recorded'}</p></article>)}<h4>Case baseline R{run.baseline.revision}</h4><p>{run.baseline.body.thesis||'No thesis recorded at submission.'}</p><details><summary>Full frozen case</summary><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(run.baseline.body,null,2)}</pre></details></>:<>{(run.state?.sections||[]).filter(s=>view==='full'||['summary','business','variant','risks','monitor','synthesis'].includes(s.id)).map(s=><article key={s.id}><h4>{s.title}</h4>{!s.claims.length&&<p>No supported conclusion generated from this source pack.</p>}{s.claims.map(c=><section key={c.id}><p><strong>{c.basis.replaceAll('_',' ')} · {c.review==='supported'&&c.passageMatched?'Passage matched + model reviewed':'Needs review'}</strong></p><p>{c.statement}</p><p>{c.reviewReason||'Review pending'}</p><details><summary>Supporting excerpts · {c.evidence.length}</summary>{c.evidence.map((e,i)=><blockquote key={i}><strong>{sourceById.get(e.sourceId)?.filename||'Unknown source'} · {e.matched?'Passage matched':'Unmatched'}</strong><p>{e.excerpt}</p></blockquote>)}</details></section>)}<h5>Gaps and unresolved questions</h5>{s.gaps.map((g,i)=><p key={i}>{g}</p>)}</article>)}</>}
 <p>Model review is not investor approval. Financial calculations and consensus are not independently verified by this workflow. Investment-map exports omit unresolved claims; the full research retains them with warnings.</p>
 </>}
 </section>;
}
