import * as React from 'react';

export function CaseEvidence({api,ticker,body,disabled,onCommit}) {
 const [rows,setRows]=React.useState([]),[error,setError]=React.useState(''),[loading,setLoading]=React.useState(true),[chosen,setChosen]=React.useState(''),[assumptionId,setAssumption]=React.useState(''),[field,setField]=React.useState('support');
 React.useEffect(()=>{let live=true;setRows([]);setChosen('');setAssumption('');setError('');setLoading(true);fetch(api+'/api/research/investment-case/'+encodeURIComponent(ticker)+'/source-proposals',{signal:AbortSignal.timeout(20000)}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Sources unavailable');if(live)setRows(d.proposals||[]);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[api,ticker]);
 const options=rows.flatMap(job=>(job.result?.changes||[]).filter(c=>c.passageMatched&&c.reviewPassed).map(change=>({key:job.id+':'+change.id,job,change})));
 const selected=options.find(o=>o.key===chosen),assumption=body.assumptions.find(a=>a.id===assumptionId);
 return <details className="amendment-card"><summary>Connect reviewed research to an assumption</summary><p>Choose an existing research change and review its excerpt before adding it to your investment case. A passage match establishes provenance at generation; it does not prove the interpretation or that the source is still current.</p>
 {loading&&<p role="status">Loading source proposals…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!options.length&&<p>No eligible source proposals yet. Generate a source comparison in Evidence &amp; changes first. Only changes with a matching passage and a passed model review appear here.</p>}
 {!!options.length&&<fieldset disabled={disabled}><label>Reviewed research change<select value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Choose a source-supported change</option>{options.map(o=><option key={o.key} value={o.key}>{new Date(o.job.created_at).toLocaleDateString()} · {o.change.after.slice(0,110)}</option>)}</select></label>
 {selected&&<><p>{selected.change.reason}</p>{selected.change.evidence.filter(e=>e.status==='passage_matched').map((e,i)=><section key={i}><strong>{selected.job.result.sources.find(s=>s.id===e.sourceId)?.filename||'Source snapshot'}</strong><blockquote style={{whiteSpace:'pre-wrap'}}>{e.excerpt}</blockquote></section>)}
 <label>Investment assumption<select value={assumptionId} onChange={e=>setAssumption(e.target.value)}><option value="">Choose an assumption</option>{body.assumptions.map((a,i)=><option key={a.id} value={a.id}>{i+1}. {a.claim.slice(0,120)}</option>)}</select></label>
 <label>Update which field?<select value={field} onChange={e=>setField(e.target.value)}><option value="support">Supporting evidence</option><option value="contrary">Contrary evidence / unresolved</option><option value="nextTest">Next test and timing</option></select></label>
 {assumption&&<><h4>Before</h4><p style={{whiteSpace:'pre-wrap'}}>{assumption[field]||'Not recorded'}</p><h4>Proposed replacement</h4><p style={{whiteSpace:'pre-wrap'}}>{selected.change.after}</p><p>This replaces the selected field. Your assumption and its basis remain unchanged; the original quotation is retained separately.</p><button disabled={assumption[field]===selected.change.after} onClick={()=>onCommit({mode:'source_change',sourceChange:{jobId:selected.job.id,changeId:selected.change.id,assumptionId,field}})}>Accept into a new investment case revision</button></>}
 </>}</fieldset>}
 {!!body.evidenceLinks?.length&&<details><summary>{body.evidenceLinks.length} accepted evidence links</summary>{body.evidenceLinks.map((link,i)=>{const a=body.assumptions.find(x=>x.id===link.assumptionId);return <section key={i}><h4>{a?.claim||'Assumption removed in a later revision'}</h4><p>{a?.[link.field]===link.after?'Matches current wording':'Historical wording · subsequently edited'} · {link.field}</p><p style={{whiteSpace:'pre-wrap'}}>{link.after}</p>{link.evidence.map((e,j)=><blockquote key={j}><strong>{e.source.filename}</strong><br/>{e.excerpt}</blockquote>)}</section>;})}</details>}
 </details>;
}
