import * as React from 'react';
import {ResearchChat} from './research-chat';

export function CaseEvidence({api,ticker,body,revision,disabled,onCommit}) {
 const [rows,setRows]=React.useState([]),[error,setError]=React.useState(''),[loading,setLoading]=React.useState(true),[chosen,setChosen]=React.useState(''),[assumptionId,setAssumption]=React.useState(''),[field,setField]=React.useState('support');
 const [documents,setDocuments]=React.useState([]),[files,setFiles]=React.useState([]),[instructions,setInstructions]=React.useState(''),[working,setWorking]=React.useState(false),[notice,setNotice]=React.useState(''),[refresh,setRefresh]=React.useState(0);
 const [debate,setDebate]=React.useState(null);
 const requestRef=React.useRef(null),mutationLock=React.useRef(false),alive=React.useRef(true);
 React.useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 React.useEffect(()=>{let live=true,inflight=false;const load=async()=>{if(inflight)return;inflight=true;try{const r=await fetch(api+'/api/research/investment-case/'+encodeURIComponent(ticker)+'/source-proposals',{signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Sources unavailable');if(live){setRows(d.proposals||[]);setDocuments(d.documents||[]);setError('');}}catch(e){if(live)setError(e.message);}finally{inflight=false;if(live)setLoading(false);}};load();const timer=setInterval(load,10000);return()=>{live=false;clearInterval(timer);};},[api,ticker,refresh]);
 const mutate=async(path,payload)=>{if(mutationLock.current)return;mutationLock.current=true;setWorking(true);setNotice('Submitting…');try{let key='';try{key=localStorage.getItem('equity_analyzer_api_key')||'';}catch{}const r=await fetch(api+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,apiKey:key}),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');if(alive.current){setNotice('Request received. Progress and saved proposals appear below.');setRefresh(x=>x+1);requestRef.current=null;}}catch(e){if(alive.current)setNotice(e.message+' Your selections remain here.');}finally{mutationLock.current=false;if(alive.current)setWorking(false);}};
 const generate=()=>{const value={revision,filenames:files,instructions};const signature=JSON.stringify(value);if(requestRef.current?.signature!==signature)requestRef.current={signature,payload:{...value,requestId:crypto.randomUUID()}};mutate('/api/research/investment-case/'+encodeURIComponent(ticker)+'/proposals',requestRef.current.payload);};
 const activeJob=rows.some(j=>j.target==='investment_case'&&['queued','running','awaiting_approval'].includes(j.status));
 const options=rows.flatMap(job=>(job.result?.changes||[]).filter(c=>['awaiting_approval','applied'].includes(job.status)&&c.passageMatched&&c.reviewPassed).map(change=>({key:job.id+':'+change.id,job,change})));
 const selected=options.find(o=>o.key===chosen);const targeted=selected?.change.assumptionId;const effectiveAssumption=targeted||assumptionId,effectiveField=selected?.change.field||field;const assumption=body.assumptions.find(a=>a.id===effectiveAssumption);
 return <details open className="amendment-card"><summary>Evidence, debate and proposed changes</summary><p>Choose an existing research change and review its excerpt before adding it to your investment case. A passage match establishes provenance at generation; it does not prove the interpretation or that the source is still current.</p>
 <details open><summary>Generate proposals for this investment case</summary><p>Select up to 10 saved originals. Charlie checks new evidence against your assumptions and proposes only material changes. Model usage is incurred when you generate. Oversized source sets fail visibly rather than being silently clipped.</p><fieldset disabled={disabled||working||activeJob}><label>Focus or instructions<textarea value={instructions} maxLength={6000} onChange={e=>setInstructions(e.target.value)} placeholder="Challenge the margin recovery assumption; preserve management qualifiers."/></label><div style={{maxHeight:240,overflowY:'auto'}}>{documents.map(name=><label key={name}><input type="checkbox" checked={files.includes(name)} disabled={!files.includes(name)&&files.length>=10} onChange={e=>setFiles(e.target.checked?[...files,name]:files.filter(x=>x!==name))}/>{name}</label>)}</div>{!loading&&!documents.length&&<p>No saved originals found for this company. Import documents into Charlie first.</p>}<button disabled={!revision||!body.assumptions.length||!files.length} onClick={generate}>Generate assumption proposals · {files.length} sources</button></fieldset><p role="status">{notice}</p>
 {rows.filter(j=>j.target==='investment_case').map(j=><section key={j.id}><strong>{j.status.replaceAll('_',' ')} · {new Date(j.created_at).toLocaleString()}</strong>{j.error&&<p role="alert">{j.error}</p>}{j.status==='awaiting_approval'&&<p>{j.result?.changes?.length||0} proposed changes · {(j.result?.changes||[]).filter(c=>c.reviewPassed&&c.passageMatched).length} passed passage and model checks. Review below, then close this proposal to start another.</p>}{(j.result?.changes||[]).filter(c=>!c.reviewPassed||!c.passageMatched).map(c=><p key={c.id}>Needs review: {c.after} — {c.reviewIssue||'Supporting passage did not match.'}</p>)}{j.status==='failed'&&j.result?.checkpoint&&<button disabled={disabled||working} onClick={()=>mutate('/api/research/amendment/'+j.id+'/resume',{})}>Resume from saved checkpoint</button>}{['failed','awaiting_approval'].includes(j.status)&&<button disabled={disabled||working} onClick={()=>mutate('/api/research/amendment/'+j.id+'/decide',{action:'dismiss'})}>Close proposal · keep accepted case revisions</button>}</section>)}
 </details>
 {loading&&<p role="status">Loading source proposals…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!options.length&&<p>No eligible source proposals yet. Generate a comparison above, or use an existing thesis comparison. Only changes with a matching passage and a passed model review appear here.</p>}
 {!!options.length&&<fieldset disabled={disabled||working}><label>Reviewed research change<select value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Choose a source-supported change</option>{options.map(o=><option key={o.key} value={o.key}>{new Date(o.job.created_at).toLocaleDateString()} · {o.change.after.slice(0,110)}</option>)}</select></label>
 {selected&&<><h3>Why Charlie proposes a change</h3><p>{selected.change.reason}</p><div className="lifecycle-tabs">{[['Challenge this interpretation','Challenge this proposed interpretation. Separate what the source actually says from inference. Identify missing evidence and explain whether the current thesis should change.'],['Make the opposing case','Make the strongest evidence-based case against this proposed change. Preserve qualifiers and explain what would resolve the disagreement.'],['What would change my mind?','Identify the observable evidence that would support or invalidate this change and the next questions I should investigate.']].map(([label,prompt])=><button key={label} onClick={()=>setDebate({prompt,content:JSON.stringify({caseRevision:revision,investmentCase:body,proposalId:selected.job.id,change:selected.change,sources:selected.job.result.sources})})}>{label}</button>)}</div>{selected.change.evidence.filter(e=>e.status==='passage_matched').map((e,i)=><section key={i}><strong>{selected.job.result.sources.find(s=>s.id===e.sourceId)?.filename||'Source snapshot'}</strong><blockquote style={{whiteSpace:'pre-wrap'}}>{e.excerpt}</blockquote></section>)}
 <label>Investment assumption<select disabled={!!targeted} value={effectiveAssumption} onChange={e=>setAssumption(e.target.value)}><option value="">Choose an assumption</option>{body.assumptions.map((a,i)=><option key={a.id} value={a.id}>{i+1}. {a.claim.slice(0,120)}</option>)}</select></label>
 <label>Update which field?<select disabled={!!targeted} value={effectiveField} onChange={e=>setField(e.target.value)}><option value="support">Supporting evidence</option><option value="contrary">Contrary evidence / unresolved</option><option value="nextTest">Next test and timing</option></select></label>
 {assumption&&<><h4>Before</h4><p style={{whiteSpace:'pre-wrap'}}>{assumption[effectiveField]||'Not recorded'}</p><h4>Proposed replacement</h4><p style={{whiteSpace:'pre-wrap'}}>{selected.change.after}</p><p>This replaces the selected field. Your assumption and its basis remain unchanged; the original quotation is retained separately.</p><button disabled={assumption[effectiveField]===selected.change.after} onClick={()=>onCommit({mode:'source_change',sourceChange:{jobId:selected.job.id,changeId:selected.change.id,assumptionId:effectiveAssumption,field:effectiveField}})}>Accept into a new investment case revision</button></>}
 </>}</fieldset>}
 {!!body.evidenceLinks?.length&&<details><summary>{body.evidenceLinks.length} accepted evidence links</summary>{body.evidenceLinks.map((link,i)=>{const a=body.assumptions.find(x=>x.id===link.assumptionId);return <section key={i}><h4>{a?.claim||'Assumption removed in a later revision'}</h4><p>{a?.[link.field]===link.after?'Matches current wording':'Historical wording · subsequently edited'} · {link.field}</p><p style={{whiteSpace:'pre-wrap'}}>{link.after}</p>{link.evidence.map((e,j)=><blockquote key={j}><strong>{e.source.filename}</strong><br/>{e.excerpt}</blockquote>)}</section>;})}</details>}
 {debate&&<ResearchChat api={api} context={{ticker,type:'review',content:debate.content}} initialMessage={debate.prompt} allowEdits={false} onClose={()=>setDebate(null)}/>}
 </details>;
}
