import * as React from 'react';
import {InvestorFramework} from './investor-framework';
import {ResearchDecisions} from './research-decisions';
import {ResearchWorkbench} from './research-workbench';
import {UnderweightMonitor} from './underweight-monitor';
import {ThesisEvolution} from './thesis-evolution';
import {CaseEvidence} from './investment-case-evidence';

const empty=()=>({thesis:'',variantView:'',marketBaseline:'',changeConditions:'',assumptions:[],scenarios:{}});
const fields=[['thesis','Investment thesis'],['variantView','Where my view differs'],['marketBaseline','Market expectations · include source and date'],['changeConditions','What would change my mind']];
export function InvestmentCase({api,analyses=[],initialTicker=''}) {
 const [ticker,setTicker]=React.useState(initialTicker),[active,setActive]=React.useState(''),[body,setBody]=React.useState(empty),[revision,setRevision]=React.useState(0),[versions,setVersions]=React.useState([]),[bridge,setBridge]=React.useState({}),[busy,setBusy]=React.useState(false),[message,setMessage]=React.useState(''),[dirty,setDirty]=React.useState(false),[selectedVersion,setSelectedVersion]=React.useState('');
 const [workspaceTab,setWorkspaceTab]=React.useState('case');
 const pending=React.useRef(null),lock=React.useRef(false),alive=React.useRef(true);
 React.useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const json=async(path,options={})=>{const r=await fetch(api+path,{...options,signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Investment case unavailable');return d;};
 const load=async(selectedTicker=ticker)=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{const t=(typeof selectedTicker==='string'?selectedTicker:ticker).trim().toUpperCase();setTicker(t);const d=await json('/api/research/investment-case/'+encodeURIComponent(t));if(!alive.current)return;setActive(t);setRevision(d.revision);setBody({...empty(),...d.body});setVersions(d.versions);setBridge(d.bridge);setDirty(false);setSelectedVersion('');pending.current=null;}catch(e){if(alive.current)setMessage(e.message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
 React.useEffect(()=>{if(initialTicker)load();},[]);
 const edit=next=>{setBody(next);setDirty(true);pending.current=null;setMessage('Unsaved changes');};
 const save=async(operation={body})=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('Saving…');const signature=JSON.stringify({revision,...operation});const payload=pending.current?.signature===signature?pending.current.payload:{requestId:crypto.randomUUID(),revision,...operation};pending.current={signature,payload};
  try{const d=await json('/api/research/investment-case/'+encodeURIComponent(active),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!alive.current)return;setRevision(d.revision);setBody(d.body||payload.body);setBridge(d.bridge||{});setDirty(false);pending.current=null;setMessage(`Saved revision ${d.revision}. Your thesis documents remain separate.`);try{const fresh=await json('/api/research/investment-case/'+encodeURIComponent(active));if(alive.current){setVersions(fresh.versions);}}catch{if(alive.current)setMessage(`Revision ${d.revision} saved; history refresh unavailable.`);}}
  catch(e){if(alive.current)setMessage(`${e.message} Your edits remain here. Retrying unchanged edits uses the same save request.`);}finally{lock.current=false;if(alive.current)setBusy(false);}
 };
 const assumption=(i,key,value)=>edit({...body,assumptions:body.assumptions.map((a,j)=>i===j?{...a,[key]:value}:a)});
 const snapshot=versions.find(v=>String(v.revision)===selectedVersion);
 return <section className="workspace-panel" aria-label="Investment case"><p className="workspace-eyebrow">INVESTMENT CASE / YOUR ASSUMPTIONS</p><h2>Investment thesis workspace.</h2><p>Record what you believe, the evidence against it, and the next test. These are your working assumptions. Manual source references are unverified; accepted research links retain the original excerpt and its provenance.</p>
 <InvestorFramework api={api}/><UnderweightMonitor api={api} disabled={busy||dirty} onOpen={t=>{setWorkspaceTab('reviews');load(t);}}/>
 <div className="desk-filter"><label>Company<input list="investment-case-tickers" value={ticker} disabled={busy||dirty} onChange={e=>setTicker(e.target.value.toUpperCase())} placeholder="ABBV" maxLength={20}/></label><datalist id="investment-case-tickers">{[...new Set(analyses.map(a=>a.ticker).filter(Boolean))].sort().map(t=><option key={t} value={t}/>)}</datalist><button disabled={busy||dirty||!ticker.trim()} onClick={load}>Open investment case</button></div>
 {dirty&&<p>Save your edits before switching companies. To discard them, use <button disabled={busy} onClick={()=>{setDirty(false);setMessage('Edits remain visible until you open a company again.');}}>Allow reload without saving</button>.</p>}
 <p role="status">{message}</p>
 {active&&<><div className="workspace-section-heading"><h3>{active} · {revision?`Revision ${revision}`:'New investment case'}</h3><span>{dirty?'Unsaved changes':'Saved working assumptions'}</span></div>
 <nav className="lifecycle-tabs" aria-label="Investment thesis workspace">{[['case','Current thesis'],['evidence','Evidence & proposals'],['reviews','Decisions & underweights'],['evolution','Evolution']].map(([id,label])=><button key={id} aria-pressed={workspaceTab===id} onClick={()=>setWorkspaceTab(id)}>{label}</button>)}</nav>
 <div hidden={workspaceTab!=='case'}>{!revision&&<section className="workspace-panel"><h3>Start from your saved thesis</h3><p>Copy its summary, pillars and textual risks/signposts into an unsaved baseline for review. Original thesis documents remain unchanged.</p><button disabled={busy||dirty} onClick={async()=>{if(lock.current)return;lock.current=true;setBusy(true);try{const d=await json('/api/research/investment-case/'+active+'/saved-thesis-draft');if(alive.current){edit(d.body);setMessage(d.scope+' Review the draft below, then save the first revision.');}}catch(e){if(alive.current)setMessage(e.message);}finally{lock.current=false;if(alive.current)setBusy(false);}}}>Load saved thesis as a draft</button></section>}<fieldset disabled={busy} className="desk-form">{fields.map(([key,label])=><label key={key}>{label}<textarea rows={3} value={body[key]} onChange={e=>edit({...body,[key]:e.target.value})}/></label>)}
 <h3>Key assumptions and evidence</h3>{body.assumptions.map((a,i)=><section className="amendment-card" key={a.id}><label>Assumption {i+1}<textarea rows={2} value={a.claim} onChange={e=>assumption(i,'claim',e.target.value)}/></label><label>Basis<select value={a.evidenceType} onChange={e=>assumption(i,'evidenceType',e.target.value)}><option value="interpretation">My interpretation / assumption</option><option value="management_statement">Management statement · attributed</option><option value="reported_fact">Reported fact · verify against source</option><option value="broker_estimate">Broker estimate · attributed</option></select></label>{[['support','Supporting evidence'],['contrary','Contrary evidence / unresolved'],['nextTest','Next test and timing'],['sourceReference','Source reference · document, page, date']].map(([key,label])=><label key={key}>{label}<textarea rows={2} value={a[key]} onChange={e=>assumption(i,key,e.target.value)}/></label>)}<button onClick={()=>edit({...body,assumptions:body.assumptions.filter((_,j)=>j!==i)})}>Remove assumption from this revision</button></section>)}<button disabled={body.assumptions.length>=30} onClick={()=>edit({...body,assumptions:[...body.assumptions,{id:crypto.randomUUID(),claim:'',support:'',contrary:'',nextTest:'',sourceReference:'',evidenceType:'interpretation'}]})}>Add assumption</button>
 <details><summary>Valuation scenarios · EPS × P/E</summary><p>A simple sensitivity calculation using your inputs. It excludes dividends, FX, dilution changes and timing/discounting. It is not linked to a spreadsheet or consensus feed. Use the same currency, EPS definition and forecast period across scenarios.</p><label><input type="checkbox" checked={Object.keys(body.scenarios).length>0} onChange={e=>edit({...body,scenarios:e.target.checked?{referencePrice:'',period:'',currency:'',asOf:new Date().toISOString().slice(0,10),bearEPS:'',bearPE:'',baseEPS:'',basePE:'',bullEPS:'',bullPE:''}:{}})}/>Include valuation scenarios</label>{Object.keys(body.scenarios).length>0&&<>{[['referencePrice','Reference share price'],['period','Forecast period and EPS basis'],['currency','Currency'],['asOf','Price as of'],['bearEPS','Bear EPS'],['bearPE','Bear P/E'],['baseEPS','Base EPS'],['basePE','Base P/E'],['bullEPS','Bull EPS'],['bullPE','Bull P/E']].map(([key,label])=><label key={key}>{label}<input type={key==='asOf'?'date':'text'} inputMode={/EPS|PE|Price/.test(key)?'decimal':undefined} value={body.scenarios[key]||''} onChange={e=>edit({...body,scenarios:{...body.scenarios,[key]:e.target.value}})}/></label>)}</>}</details>
 <button className="workspace-primary" onClick={()=>save()}>{busy?'Saving…':'Save investment case revision'}</button></fieldset>
 {!dirty&&Object.keys(bridge).length>0&&<div style={{overflowX:'auto'}}><h3>Saved scenario sensitivities</h3><table><thead><tr><th>Scenario</th><th>Implied price ({body.scenarios.currency})</th><th>Price return</th></tr></thead><tbody>{Object.entries(bridge).map(([name,v])=><tr key={name}><th>{name}</th><td>{v.impliedPrice}</td><td>{v.priceReturnPct}%</td></tr>)}</tbody></table></div>}
 </div><div hidden={workspaceTab!=='reviews'}><ResearchWorkbench initialKind="underweight" key={active+'-work'} api={api} ticker={active} caseRevision={revision} assumptions={body.assumptions} disabled={busy||dirty}/>
 <ResearchDecisions key={active+'-decisions'} api={api} ticker={active}/>
 </div><div hidden={workspaceTab!=='evidence'}><CaseEvidence key={active} revision={revision} api={api} ticker={active} body={body} disabled={busy||dirty} onCommit={save}/></div>
 {workspaceTab==='evolution'&&<ThesisEvolution key={active} api={api} ticker={active} revision={revision}/>}
 <button disabled={busy||dirty||!revision} onClick={()=>{const blob=new Blob([JSON.stringify({ticker:active,revision,body},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${active}-investment-case-r${revision}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download saved case with evidence · JSON</button>
 <details><summary>Revision history · latest {versions.length}</summary><label>Read a saved revision<select value={selectedVersion} onChange={e=>setSelectedVersion(e.target.value)}><option value="">Choose revision</option>{versions.map(v=><option key={v.revision} value={v.revision}>Revision {v.revision} · {new Date(v.created_at).toLocaleString()}</option>)}</select></label>{snapshot&&<div><p>Restore makes a new revision; all intervening history is retained. Review this snapshot before restoring.</p><button disabled={busy||dirty||snapshot.revision===revision} onClick={()=>save({mode:'restore',sourceRevision:snapshot.revision})}>Restore revision {snapshot.revision} as a new revision</button><details><summary>Scenario inputs and evidence metadata</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify({scenarios:snapshot.body.scenarios,evidenceLinks:snapshot.body.evidenceLinks||[]},null,2)}</pre></details>{fields.map(([key,label])=><section key={key}><h4>{label}</h4><p style={{whiteSpace:'pre-wrap'}}>{snapshot.body[key]||'Not recorded'}</p></section>)}{snapshot.body.assumptions.map(a=><section key={a.id}><h4>{a.claim}</h4><p>{a.evidenceType.replaceAll('_',' ')}</p>{['support','contrary','nextTest','sourceReference'].map(k=><p key={k} style={{whiteSpace:'pre-wrap'}}>{k}: {a[k]||'Not recorded'}</p>)}</section>)}</div>}</details></>}
 </section>;
}
