import * as React from 'react';
export function MeetingSession({api,meetingId,questionSet}){
 const [quality,setQuality]=React.useState(null);
 const [open,setOpen]=React.useState(false),[high,setHigh]=React.useState(true),[answers,setAnswers]=React.useState([]),[versions,setVersions]=React.useState([]),[error,setError]=React.useState(''),[history,setHistory]=React.useState(false);
 React.useEffect(()=>{if(!open&&!history)return;let active=true;Promise.all(['answers','versions','quality'].map(async part=>{const r=await fetch(`${api}/api/mp/meetings/${meetingId}/${part}`,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Meeting context could not be loaded.');return r.json();})).then(([a,v,q])=>{if(active){setQuality(q);setAnswers(a.answers);setVersions(v.versions);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[api,meetingId,questionSet.id,open,history]);
 return <section className="workspace-panel mb-3"><div className="desk-filter"><button onClick={()=>setOpen(!open)}>{open?'Close meeting mode':'Open meeting mode'}</button><button onClick={()=>setHistory(!history)}>{history?'Hide version history':'Compare saved versions'}</button></div>{error&&<p role="alert">{error}</p>}{quality&&(open||history)&&<p className="desk-explainer">{quality.questions} generated items · {quality.highPriority} must-ask · {quality.withVerifiedPassages} with verified passage records · {quality.citedSources}/{quality.availableSources} sources cited · {quality.duplicateQuestions} exact duplicates. {quality.scope}</p>}{quality?.nonQuestionItems?.length>0&&(open||history)&&<p className="desk-explainer">Review items {quality.nonQuestionItems.join(', ')}: they may be coverage notes rather than management questions. Ask Charlie to revise these before using them in a meeting.</p>}{quality?.numericPremisesToReview?.length>0&&(open||history)&&<details><summary>Numeric premises to review · {quality.numericPremisesToReview.length} questions</summary><p>These values were not found verbatim in their attached passages. They may be valid periods, requested targets or calculations; check the original before treating them as established facts.</p>{quality.numericPremisesToReview.map(r=><p key={r.question}>Question {r.question}: {r.values.join(', ')}</p>)}</details>}{history&&<div><p>Previous versions remain unchanged. Review revisions before using them in a meeting.</p>{versions.map(v=><details key={v.id}><summary>Version {v.version} · {v.topics.reduce((n,t)=>n+(t.questions||[]).length,0)} questions{v.id===questionSet.id?' · Current':''}</summary>{v.topics.map((t,i)=><div key={i}><h4>{t.topic}</h4><ol>{t.questions.map((q,j)=><li key={j}>{q.question}</li>)}</ol></div>)}</details>)}</div>}{open&&<div><h3>Meeting mode · v{questionSet.version}</h3><label><input type="checkbox" checked={high} onChange={e=>setHigh(e.target.checked)}/> Must-ask questions only</label><p className="desk-explainer">Capture actual management answers here. Saving an answer marks the question answered; generating a question does not.</p>{questionSet.topics.map((t,i)=><section key={i}><h4>{t.topic}</h4>{t.questions.filter(q=>!high||q.priority==='high').map((q,j)=><article className="workspace-panel" key={q.question}><p><strong>{q.question}</strong></p><details><summary>Evidence and follow-up</summary><p>{q.context}</p><p>{q.source}</p>{q.supporting_quotes?.map((c,k)=><blockquote key={k}>{c.quote}<cite> — {c.filename}</cite></blockquote>)}<p>{q.follow_up_angle}</p></details><AnswerCapture api={api} answer={answers.find(a=>a.question===q.question)}/></article>)}</section>)}</div>}</section>;
}
function AnswerCapture({api,answer}){
 const [note,setNote]=React.useState(answer?.response_notes||''),[message,setMessage]=React.useState(''),[busy,setBusy]=React.useState(false);
 React.useEffect(()=>{setNote(answer?.response_notes||'');setMessage('');},[answer?.id]);
 if(!answer)return <p className="desk-explainer">Answer record unavailable for this question.</p>;
 return <div><label>Management answer<textarea className="w-full" value={note} maxLength={10000} onChange={e=>setNote(e.target.value)} placeholder="Capture what management actually said…"/></label><button disabled={busy||!note.trim()} onClick={async()=>{setBusy(true);try{const r=await fetch(api+'/api/mp/past-questions/'+answer.id+'/note',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({responseNotes:note.trim(),status:'answered'}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Answer could not be saved. Your text is still here.');setMessage('Answer saved to meeting history.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}}>{busy?'Saving…':'Save answer'}</button><p role="status">{message}</p></div>;
}
