import * as React from 'react';
import {AssignmentWorkspace} from './assignment-workspace';
import {workItems} from './my-work-model.mjs';
export function MyWork({api,activities,onNavigate,onSection,renderHtml}){
 const [meetings,setMeetings]=React.useState([]),[commands,setCommands]=React.useState([]),[error,setError]=React.useState(''),[filter,setFilter]=React.useState('all'),[query,setQuery]=React.useState('');
 React.useEffect(()=>{let alive=true;const load=async()=>{try{const values=await Promise.all(['/api/research/meeting-commands','/api/research/commands'].map(async path=>{const r=await fetch(api+path,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Could not refresh assignments. Last loaded results may be stale.');return r.json();}));if(alive){setMeetings(values[0].jobs||[]);setCommands(values[1].jobs||[]);setError('');}}catch(e){if(alive)setError(e.message);}};load();const timer=setInterval(()=>{if(!document.hidden)load();},15000);return()=>{alive=false;clearInterval(timer);};},[api]);
 const items=workItems(meetings,commands,activities),labels={all:'All work',needs_me:'Needs me',running:'Running / queued',ready:'Ready',failed:'Failed'};
 return <section className="workspace-panel"><div className="workspace-section-heading"><div><p className="workspace-eyebrow">MY WORK</p><h2>Assignments, answers and next actions.</h2></div><button className="workspace-primary" onClick={()=>onSection('command')}>New assignment →</button></div><p className="desk-explainer">Recent meeting packs, research commands and analyst inbox items. Saved history remains in Research history. Updates while this page is open.</p>{error&&<p role="alert" className="workspace-error">{error}</p>}
 <div className="desk-filter"><label>Find work<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ticker or task"/></label><label>Status<select value={filter} onChange={e=>setFilter(e.target.value)}>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label} · {id==='all'?items.length:items.filter(i=>i.bucket===id).length}</option>)}</select></label></div>
 <div className="meeting-pack-list">{items.filter(i=>(filter==='all'||i.bucket===filter)&&`${i.ticker} ${i.kind} ${i.activity?.input?.topic||''}`.toLowerCase().includes(query.toLowerCase())).map(i=><article key={i.kind+i.id}><div className="workspace-section-heading"><h3>{i.ticker} · {i.kind}</h3><span className="desk-status">{labels[i.bucket]}</span></div><p>{i.status}</p>{i.activity?.input?.topic&&<p>{i.activity.input.topic}</p>}{i.error&&<p className="workspace-error">{i.error}</p>}
 {i.job?.options?.meetingPrep&&<p>{i.job.options.meetingPrep.format?.replaceAll('_',' ')||'Conference'} · {i.job.options.meetingPrep.meetingDate}</p>}
 {i.job&&<AssignmentWorkspace api={api} id={i.id} onNavigate={onNavigate} onSection={onSection}/>}
 {i.job?.meeting_id&&<button onClick={()=>{window.dispatchEvent(new CustomEvent('charlie-open-meeting',{detail:{id:Number(i.job.meeting_id)}}));onNavigate('meetingprep');}}>Open question pack →</button>}
 {i.activity&&<><details><summary>Read recap and evidence</summary>{i.activity.output?.synthesisMarkdown?(renderHtml?<div className="desk-report-prose" dangerouslySetInnerHTML={{__html:renderHtml(i.activity.output.synthesisMarkdown)}}/>:<pre style={{whiteSpace:'pre-wrap'}}>{i.activity.output.synthesisMarkdown}</pre>):<p>No completed recap is attached yet. Open Analyst inbox for this item’s full details.</p>}</details><button onClick={()=>onNavigate('analysts')}>Review in Analyst inbox →</button></>}
 {(i.bucket==='failed'||i.bucket==='needs_me')&&i.job&&<button onClick={()=>onSection(i.kind==='Meeting pack'?'command':'collection')}>Resolve / retry →</button>}
 </article>)}</div>{!items.length&&!error&&<p>No recent assignments or inbox items loaded.</p>}</section>;
}
