import * as React from 'react';
import {RevenueObservation} from './revenue-observation';

const names=['bear','base','bull'];
const numeric=[['growthPct','Revenue CAGR (%)'],['marginPct','Target EBITDA margin (%)'],['multiple','Target EV / EBITDA (×)'],['netDebt','Target net debt (millions; negative = net cash)'],['otherClaims','Other senior claims (millions)'],['nonOperatingAssets','Nonoperating assets (millions)'],['shares','Target diluted shares (millions)']];
export const newOperatingModel=()=>({version:'ev-ebitda-v1',method:'ev_ebitda',units:'millions',suitable:false,currency:'',baseYear:'',targetYear:'',asOf:'',baseRevenue:'',referencePrice:'',revenueReference:'',priceReference:'',ebitdaBasis:'',scenarios:Object.fromEntries(names.map(n=>[n,{...Object.fromEntries(numeric.map(([k])=>[k,''])),rationale:''}]))});

export function OperatingModel({api,ticker,body,revision,busy,dirty,onChange,onSave,onResearch}) {
 const model=body.operatingModel,signature=JSON.stringify(model);
 const [preview,setPreview]=React.useState(null),[error,setError]=React.useState(''),[calculating,setCalculating]=React.useState(false);
 const latest=React.useRef(signature),sequence=React.useRef(0);latest.current=signature;
 React.useEffect(()=>()=>{sequence.current++;},[]);
 const edit=m=>{setError('');onChange({...body,operatingModel:m});};
 const set=(key,value)=>edit({...model,[key]:value});
 const scenario=(name,key,value)=>edit({...model,scenarios:{...model.scenarios,[name]:{...model.scenarios[name],[key]:value}}});
 const calculate=async()=>{const mine=++sequence.current,captured=signature;setCalculating(true);setError('');try{const r=await fetch(api+'/api/research/operating-model/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...model,ticker}),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Calculation unavailable');if(mine===sequence.current&&latest.current===captured)setPreview({signature:captured,model:d.model});}catch(e){if(mine===sequence.current)setError(e.message);}finally{if(mine===sequence.current)setCalculating(false);}};
 const output=preview && preview.signature===signature?preview.model:!dirty?model:null;
 return <section className="operating-model"><style>{`.operating-model{font-family:Calibri,sans-serif;color:#000;background:#fff;border-radius:12px;padding:24px}.operating-model *{color:#000!important}.operating-model p{margin:12px 0}.operating-model h3{font-size:24px}.operating-model h4{font-size:20px;font-weight:bold;margin:16px 0}.operating-model label{display:block;margin:12px 0}.operating-model input:not([type=checkbox]),.operating-model textarea{display:block;background:#fff!important;border:1px solid #888;border-radius:4px;padding:10px;width:100%;min-width:0}.operating-model textarea{min-height:90px}.operating-model button{background:#eee!important;border:1px solid #999;border-radius:5px;padding:10px;margin:8px 8px 8px 0}.operating-model button:disabled{opacity:.5}.operating-model article{border:1px solid #ccc;padding:16px;border-radius:8px;margin:12px 0}.operating-model-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.operating-model td,.operating-model th{padding:10px;border-bottom:1px solid #ddd;text-align:left}.operating-model small{display:block}.operating-model table{width:100%}@media(max-width:850px){.operating-model-grid{grid-template-columns:1fr}.operating-model{padding:16px}}`}</style>
 <h3>{ticker} · Operating scenarios</h3><p>Translate explicit assumptions into revenue, EBITDA and equity value. All calculations run in code and use no model credits. Inputs are your assumptions; source references remain unverified.</p>
 {!model?<><p>The first template uses EV/EBITDA for businesses where positive EBITDA is an appropriate valuation basis. It is not a bank, insurer, REIT, loss-making or recovery model. Existing EPS/P-E sensitivities remain in Current thesis.</p><button disabled={busy} onClick={()=>edit(newOperatingModel())}>Add EV/EBITDA model</button></>:<>
 <p>{dirty?'Unsaved model / case edits':`Saved with case R${revision}`} · {model.version}. Money and shares must both be in millions, in the same currency and forecast period. Share prices are per share.</p>
 <fieldset disabled={busy}>
 <label><input type="checkbox" checked={model.suitable} onChange={e=>set('suitable',e.target.checked)}/>I consider positive-EBITDA valuation appropriate for this company and scenario horizon.</label>
 <div className="operating-model-grid">{[['currency','Currency (three-letter code)'],['baseYear','Base fiscal year'],['targetYear','Target fiscal year · 1–5 years later'],['baseRevenue','Base-year revenue (millions)'],['referencePrice','Reference share price'],['asOf','Reference-price date']].map(([key,label])=><label key={key}>{label}<input type={key==='asOf'?'date':'text'} value={model[key]} inputMode={['baseYear','targetYear','baseRevenue','referencePrice'].includes(key)?'decimal':undefined} onChange={e=>set(key,e.target.value)}/></label>)}</div>
 { [['revenueReference','Base revenue · source, period and definition'],['priceReference','Reference price · source and date'],['ebitdaBasis','EBITDA basis · reported/adjusted definition and adjustments']].map(([key,label])=><label key={key}>{label}<textarea value={model[key]} maxLength={1800} onChange={e=>set(key,e.target.value)}/></label>)}
 <RevenueObservation api={api} ticker={ticker} model={model} onChange={edit} onResearch={onResearch}/><div className="operating-model-grid">{names.map(name=><article key={name}><h4>{name[0].toUpperCase()+name.slice(1)}</h4>{numeric.map(([key,label])=><label key={key}>{label}<input inputMode="decimal" value={model.scenarios[name][key]} onChange={e=>scenario(name,key,e.target.value)}/></label>)}<label>Assumptions, evidence and source references<textarea value={model.scenarios[name].rationale} maxLength={1800} onChange={e=>scenario(name,'rationale',e.target.value)}/></label></article>)}</div>
 <p>Revenue = base revenue × (1 + CAGR) ^ fiscal-year interval. EBITDA = target revenue × target margin. Enterprise value = EBITDA × multiple. Equity value = max(0, enterprise value − net debt − other senior claims + nonoperating assets). Per-share value = equity value ÷ diluted shares.</p>
 <button disabled={calculating} onClick={calculate}>{calculating?'Calculating…':'Calculate draft'}</button><button disabled={calculating||!dirty||preview?.signature!==signature} onClick={()=>onSave({body})}>Save case with these model inputs</button><button onClick={()=>{const next={...body};delete next.operatingModel;onChange(next);setPreview(null);}}>Remove model from draft</button>
 </fieldset><p role="alert">{error}</p>
 {output?.results?<><h4>{dirty?'Draft calculations · not saved':`Calculated from saved case R${revision}`}</h4><div style={{overflowX:'auto'}}><table><thead><tr><th>Scenario</th><th>Revenue (m)</th><th>EBITDA (m)</th><th>EV (m)</th><th>Equity (m)</th><th>Price ({output.currency})</th><th>Price return</th></tr></thead><tbody>{names.map(name=>{const r=output.results[name];return <tr key={name}><th>{name}</th>{['revenue','ebitda','enterpriseValue','equityValue','impliedPrice'].map(k=><td key={k}>{r[k]}</td>)}<td>{r.priceReturnPct}%</td></tr>;})}</tbody></table></div>
 <h4>Conditional reverse valuation</h4><p>At the reference price, base-case EBITDA required is {output.results.base.reverseValid?`${output.results.base.impliedEbitdaAtReferencePrice} million ${output.currency}`:'not interpretable (nonpositive implied EBITDA)'}. This holds the base multiple, net debt, other claims, nonoperating assets and shares fixed. It is not a consensus estimate or a unique market-implied forecast.</p>
 <details><summary>Base-case EBITDA / multiple sensitivity</summary><div style={{overflowX:'auto'}}><table><thead><tr><th>EBITDA change</th><th>EV/EBITDA</th><th>Implied price ({output.currency})</th></tr></thead><tbody>{output.sensitivity.map((s,i)=><tr key={i}><td>{s.ebitdaChangePct}%</td><td>{s.multiple}×</td><td>{s.impliedPrice}</td></tr>)}</tbody></table></div></details>{output.warnings.map(w=><p key={w}>{w}</p>)}</>:<p>Calculate after changing inputs. Earlier results are hidden until they match the current inputs.</p>}
 </>}
 </section>;
}
