import * as React from 'react';
import {prioritizedResearch} from './research-priorities.mjs';
export function PortfolioPriorities({api,analyses,activities,onCompany,onPlan}) {
  const [profile,setProfile]=React.useState(null),[positions,setPositions]=React.useState([]),[asOf,setAsOf]=React.useState(new Date().toISOString().slice(0,10)),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[loaded,setLoaded]=React.useState(false);
  const alive=React.useRef(true),lock=React.useRef(false);
  React.useEffect(()=>{alive.current=true;const c=new AbortController(),timer=setTimeout(()=>c.abort(),20000);fetch(`${api}/api/research/priorities`,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load portfolio priorities');if(alive.current){setProfile(d.profile);setPositions(d.profile?.positions||[]);if(d.profile?.asOf)setAsOf(d.profile.asOf);setLoaded(true);}}).catch(e=>{if(alive.current)setError(e.message);}).finally(()=>clearTimeout(timer));return()=>{alive.current=false;c.abort();};},[api]);
  const save=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const r=await fetch(`${api}/api/research/priorities`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asOf,positions:positions.map(p=>({...p,weightPct:p.weightPct===''?null:Number(p.weightPct)}))}),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Save failed');if(alive.current)setProfile(d.profile);}catch(e){if(alive.current)setError(e.message+' Refresh this view to check saved settings before editing again.');}finally{lock.current=false;if(alive.current)setBusy(false);}};
  const result=prioritizedResearch(analyses,activities,profile);
  return <section className="workspace-panel"><p className="workspace-eyebrow">PORTFOLIO / RESEARCH ATTENTION</p><h2>Put research effort where it matters.</h2><p className="desk-explainer">A transparent research queue using user-reported exposure, thesis age and pending or failed analyst activities. This score is a workflow heuristic, not a return forecast or position-sizing recommendation.</p>
    {error&&<p className="workspace-error" role="alert">{error}</p>}
    <details><summary>Configure portfolio weights · {profile?.positions?.length||0} positions</summary><p className="desk-explainer">Enter signed portfolio weights: positive for long, negative for short. These are not connected to a broker or independently verified. Weights older than 30 days are excluded from ordering.</p><fieldset className="desk-form" disabled={busy||!loaded}><label>Holdings as of<input type="date" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label>{positions.map((p,i)=><div className="desk-filter" key={i}><label>Ticker<input value={p.ticker} maxLength={20} onChange={e=>setPositions(positions.map((p,j)=>j===i?{...p,ticker:e.target.value.toUpperCase().trim()}:p))}/></label><label>Signed weight %<input type="number" min="-100" max="100" step="any" value={p.weightPct} onChange={e=>setPositions(positions.map((p,j)=>j===i?{...p,weightPct:e.target.value}:p))}/></label><button onClick={()=>setPositions(positions.filter((_,j)=>j!==i))}>Remove</button></div>)}<button disabled={positions.length>=200} onClick={()=>setPositions([...positions,{ticker:'',weightPct:''}])}>Add position</button><button className="workspace-primary" onClick={save}>Save weights</button></fieldset></details>
    <p role="status">{!profile?'No holdings profile. Ordering uses research age and activity counts.':result.fresh?`Using reported weights as of ${profile.asOf}.`:`Holdings dated ${profile.asOf} are stale; weights are excluded.`}</p>
    <p className="desk-explainer">Score = 10 × absolute weight (%) + thesis age (capped at 180 days) ÷ 6 + 5 × activity count (capped at 5). Missing thesis dates receive the 180-day age value. No research is started automatically.</p>
    {result.rows.map(r=><div className="desk-row" key={r.ticker}><button onClick={()=>onCompany(r.ticker,'portfolio')}><strong>{r.ticker}</strong><span>{r.reasons.join(' · ')}</span></button><small>Priority {r.score.toFixed(1)}</small><button onClick={()=>onPlan([r.ticker])}>Plan research →</button></div>)}
  </section>;
}
