import * as React from 'react';
const fields={support:'Supporting evidence',contrary:'Risks & contrary evidence',nextTest:'Next test'};
const ready=c=>c.passageMatched&&c.reviewPassed;
export function ProposalReview({job,body,revision,disabled,onCommit,onDebate,onRepair}){
 const changes=job.result?.changes||[];
 const [repairBusy,setRepairBusy]=React.useState(false),[repairNotice,setRepairNotice]=React.useState('');
 React.useEffect(()=>{if(['queued','running'].includes(job.status))setRepairNotice('');},[job.status]);
 const repairLock=React.useRef(false);
 const requestRepair=async()=>{if(repairLock.current)return;repairLock.current=true;setRepairBusy(true);setRepairNotice('Submitting revision request…');try{const result=await onRepair(repairCount);setRepairNotice(result?.ok?'Revision queued. Charlie is re-reading the originals; results refresh automatically.':result?.error||'The request could not be confirmed. Reload the results before retrying.');}catch(e){setRepairNotice(e.message||'Revision request failed. Please retry.');}finally{repairLock.current=false;setRepairBusy(false);}};
 const repairCount=job.result?.repairHistory?.length||0;
 const needsRepair=changes.filter(c=>!ready(c)).length;
 const [filter,setFilter]=React.useState('ready'),[selectedId,setSelectedId]=React.useState(null),[assumptionId,setAssumptionId]=React.useState(''),[field,setField]=React.useState('support');
 const available=changes.filter(c=>filter==='ready'?ready(c):!ready(c));
 const selected=available.find(c=>c.id===selectedId)||available[0];
 const assumption=body.assumptions.find(a=>a.id===(selected?.assumptionId||assumptionId));
 const effectiveField=selected?.field||field;
 const applied=!!selected&&!!assumption&&assumption[effectiveField]===selected.after;
 const canAccept=selected&&ready(selected)&&['awaiting_approval','applied'].includes(job.status)&&assumption&&!applied;
 const title=c=>body.assumptions.find(a=>a.id===c.assumptionId)?.claim||'Research change';
 return <div className="proposal-review"><div className="proposal-review-filters" aria-label="Filter proposed changes">{[['ready','Ready to review',changes.filter(ready).length],['flagged','Charlie needs to revise',changes.filter(c=>!ready(c)).length]].map(([id,label,count])=><button key={id} aria-pressed={filter===id} onClick={()=>{setFilter(id);setSelectedId(null);}}>{label}<strong>{count}</strong></button>)}</div>
 <p className="proposal-review-intro">{filter==='ready'?'These changes passed source-passage and model checks. Read each proposal before accepting it.':'Charlie could not substantiate these drafts. You do not need to verify them manually. Ask Charlie to re-read the originals and revise; your saved case stays unchanged.'}</p>
 {!available.length?<p className="case-evidence-banner">{filter==='ready'?'No changes are ready for acceptance. Open Charlie needs to revise to request a supported revision.':'No drafts need revision.'}</p>:<div className="proposal-review-layout"><nav className="proposal-change-list" aria-label="Proposed changes">{available.map((c,i)=><button key={c.id} aria-pressed={selected?.id===c.id} onClick={()=>{setSelectedId(c.id);setAssumptionId('');setField('support');}}><small>CHANGE {changes.indexOf(c)+1} · {fields[c.field]||'Research wording'}</small><span>{title(c)}</span><em>{body.assumptions.some(a=>a.id===c.assumptionId&&a[c.field]===c.after)?'Already reflected in case':ready(c)?'Open for review →':'Unsupported draft →'}</em></button>)}</nav>
 {selected&&<article className="proposal-change-reader" aria-label="Selected change"><header><p className="workspace-eyebrow">CHANGE {changes.indexOf(selected)+1} / {fields[effectiveField]||'PROPOSED WORDING'}</p><h3>{title(selected)}</h3><span className="proposal-status">{applied?'Already reflected in current case':ready(selected)?'Ready for your review':'Draft failed Charlie’s evidence checks'}</span></header>
 {!ready(selected)&&<section className="proposal-verification"><h4>Charlie needs to fix its draft</h4><p>{selected.repairOutcome==='no_supported_change'?'After re-reading the originals, Charlie could not produce a supported replacement. Your current wording has been retained.':!selected.passageMatched?'Charlie could not locate its quoted passage in the saved original. This draft is not ready for an investment decision.':'The quotation matched, but the reviewer found claims it does not adequately support.'}</p>
 {['queued','running'].includes(job.status)?<p role="status">Charlie is re-reading the originals and checking revised drafts. This view refreshes automatically; your saved case is unchanged.</p>:onRepair&&job.status==='awaiting_approval'&&repairCount<2?<><button className="workspace-primary" disabled={disabled||repairBusy} onClick={requestRepair}>{repairBusy?'Submitting…':`Re-read sources & revise ${needsRepair} draft${needsRepair===1?'':'s'}`}</button><p className="proposal-footnote">Charlie will shorten unsupported drafts, check quotations and run an independent review. Other proposals are preserved. Uses model credits; nothing is accepted automatically.</p></>:<p>Close this review with your conclusion below, then assess additional source documents if needed.</p>}
 {repairCount>0&&<p>{repairCount} revision attempt{repairCount===1?'':'s'} recorded. If evidence is still insufficient, you can leave your thesis unchanged using “Finish this review” below.</p>}
 {job.error&&<p role="alert">Revision could not complete: {job.error}</p>}
 {repairNotice&&!job.error&&<p role="status" aria-live="polite">{repairNotice}</p>}
 <details><summary>What failed the checks?</summary><p>{selected.reviewIssue||'The supporting quotation did not match the saved original.'}</p></details></section>}
 {ready(selected)?<><section><h4>What changes and why</h4><p>{selected.reason||'No rationale recorded.'}</p></section><section className="proposal-wording"><h4>Proposed wording for your case</h4><p>{selected.after}</p></section></>:<details className="proposal-wording"><summary>Rejected draft · not applied</summary><h4>Charlie’s original rationale · unverified</h4><p>{selected.reason}</p><h4>Rejected replacement</h4><p>{selected.after}</p></details>}
 <details className="proposal-before"><summary>Current wording · unchanged until you accept</summary><p>{assumption?.[effectiveField]||selected.before||'Not recorded'}</p></details>
 <details className="proposal-source"><summary>Read supporting source passages · {selected.evidence?.length||0}</summary>{selected.evidence?.map((e,i)=><section key={i}><h4>{job.result.sources?.find(s=>s.id===e.sourceId)?.filename||'Source reference unavailable'}</h4><small>{e.status==='passage_matched'?'Passage matched at generation':'Unmatched quotation — do not rely on this as source text'}</small><blockquote>{e.excerpt||'No excerpt available'}</blockquote></section>)}</details>
 <div className="proposal-actions"><button onClick={()=>onDebate({prompt:'Challenge this proposed interpretation. Separate what the source actually says from inference, address verification findings, and identify missing evidence. Do not claim any edits were applied.',content:JSON.stringify({caseRevision:revision,investmentCase:body,proposalId:job.id,change:selected,sources:job.result.sources})})}>Discuss with Charlie</button>
 {ready(selected)&&!selected.assumptionId&&<><label>Investment assumption<select value={assumptionId} onChange={e=>setAssumptionId(e.target.value)}><option value="">Choose an assumption</option>{body.assumptions.map(a=><option key={a.id} value={a.id}>{a.claim}</option>)}</select></label><label>Destination<select value={field} onChange={e=>setField(e.target.value)}>{Object.entries(fields).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></>}
 {ready(selected)?<button className="workspace-primary" disabled={disabled||!canAccept} onClick={()=>onCommit({mode:'source_change',sourceChange:{jobId:job.id,changeId:selected.id,assumptionId:assumption.id,field:effectiveField}})}>{applied?'Already reflected in case':'Accept this change'}</button>:<p>This draft cannot be accepted. Use the revision action above, or finish this review with no thesis change.</p>}</div>
 <p className="proposal-footnote">Accepting saves a new case revision. Discussion and opening a card do not change your research.</p>
 </article>}</div>}
 </div>;
}
