import * as React from 'react';
export function ResearchEdits({api,ticker,instruction,analystId,onApplied}) {
  const [data,setData]=React.useState({targets:[],filenames:[],jobs:[]}),[target,setTarget]=React.useState(''),[sources,setSources]=React.useState([]),[jobId,setJobId]=React.useState(''),[selected,setSelected]=React.useState([]);
  const [error,setError]=React.useState(''),[loadError,setLoadError]=React.useState(''),[busy,setBusy]=React.useState(false),[uncertain,setUncertain]=React.useState(false),[loading,setLoading]=React.useState(true);
  const alive=React.useRef(true),lock=React.useRef(false),pending=React.useRef(null);
  const fetchJson=async(path,options={})=>{const c=new AbortController(),timer=setTimeout(()=>c.abort(),20000);try{const r=await fetch(`${api}${path}`,{...options,signal:c.signal});const d=await r.json();if(!r.ok){const e=Error(d.error||`Request failed (${r.status})`);e.status=r.status;throw e;}return d;}finally{clearTimeout(timer);}};
  const refresh=async()=>{try{const d=await fetchJson(`/api/research/edit-targets/${encodeURIComponent(ticker)}`);if(alive.current){setData(d);setLoadError('');setLoading(false);if(pending.current&&d.jobs.some(j=>j.id===pending.current.requestId)){setJobId(pending.current.requestId);pending.current=null;setUncertain(false);}}}catch(e){if(alive.current){setLoading(false);setLoadError(e.message);}}};
  React.useEffect(()=>{alive.current=true;refresh();const timer=setInterval(()=>{if(!document.hidden)refresh();},5000);return()=>{alive.current=false;clearInterval(timer);};},[api,ticker]);
  const chosen=data.targets.find(t=>`${t.kind}:${t.id}`===target),job=data.jobs.find(j=>j.id===jobId),changes=job?.result?.changes||[];
  const active=data.jobs.some(j=>j.targetId===chosen?.id&&['queued','running','awaiting_approval'].includes(j.status));
  React.useEffect(()=>setSelected([]),[jobId]);
  const launch=async()=>{if(lock.current||(!pending.current&&(!chosen||!sources.length||!instruction.trim())))return;lock.current=true;setBusy(true);setError('');let key='';try{key=localStorage.getItem('equity_analyzer_api_key')||'';}catch{}
    const body=pending.current||{requestId:crypto.randomUUID(),targetId:chosen.id,kind:chosen.kind,filenames:sources,instruction,analystId,apiKey:key};pending.current=body;
    try{const d=await fetchJson(`/api/research/edits/${encodeURIComponent(ticker)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(alive.current){setJobId(d.jobId);pending.current=null;setUncertain(false);await refresh();}}
    catch(e){if(alive.current){setError(e.message);if(e.status)pending.current=null;else setUncertain(true);await refresh();}}
    finally{lock.current=false;if(alive.current)setBusy(false);}
  };
  const decide=async action=>{if(lock.current||!job)return;lock.current=true;setBusy(true);setError('');try{await fetchJson(`/api/research/edits/${job.id}/decide`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,acceptedIds:selected})});await refresh();}catch(e){if(alive.current){setError(e.message+' Check proposal status before retrying.');await refresh();}}finally{lock.current=false;if(alive.current)setBusy(false);}};
  return <details className="research-edit-panel"><summary>Turn your instruction into source-backed edits</summary><p>Choose the exact saved document and the sources supporting your instruction above. The analyst proposes narrative changes; numeric investment-model fields remain unchanged. A separate review checks proposed wording against source quotations.</p>
    {(error||loadError)&&<p className="workspace-error" role="alert">{error||loadError}</p>}
    {loading?<p role="status">Loading saved documents…</p>:<><fieldset disabled={busy||uncertain} className="desk-form"><label>Saved document to revise<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Select a saved document</option>{data.targets.map(t=><option key={`${t.kind}:${t.id}`} value={`${t.kind}:${t.id}`}>{t.kind==='note'?`Note ${t.version} · ${t.status}`:`Investment review · ${t.mode}`} · {String(t.created_at).slice(0,25)}</option>)}</select></label>
    <details><summary>Supporting documents · {sources.length}/10 selected</summary><div className="research-edit-sources">{data.filenames.map(f=><label key={f}><input type="checkbox" checked={sources.includes(f)} disabled={!sources.includes(f)&&sources.length>=10} onChange={()=>setSources(sources.includes(f)?sources.filter(v=>v!==f):[...sources,f])}/><span>{f}</span></label>)}</div>{!data.filenames.length&&<p>Import readable source documents into Charlie before requesting edits.</p>}</details>
    <button className="workspace-primary" disabled={!chosen||!sources.length||!instruction.trim()||active} onClick={launch}>Prepare edits from my instruction</button>{active&&<p>An active proposal already exists for this document. Select it below to review its status.</p>}</fieldset></>}
    {uncertain&&<button disabled={busy} onClick={launch}>Retry same revision request</button>}
    <div className="research-chat-controls"><label>Revision history<select value={jobId} onChange={e=>setJobId(e.target.value)} disabled={busy}><option value="">Select a proposal</option>{data.jobs.map(j=><option key={j.id} value={j.id}>{j.kind} · {j.status.replaceAll('_',' ')} · {j.instruction?.slice(0,75)}</option>)}</select></label><button disabled={busy} onClick={refresh}>Refresh proposals</button></div>
    {job&&<><p role="status"><strong>{job.status.replaceAll('_',' ')}</strong> · {job.instruction}{job.error?` · ${job.error}`:''}</p>{['queued','running','awaiting_approval'].includes(job.status)&&<button disabled={busy} onClick={()=>decide('dismiss')}>Dismiss proposal</button>}
    {changes.map(c=><article className="amendment-card" key={c.id}><label><input type="checkbox" checked={job.status==='applied'?(job.result.acceptedIds||[]).includes(c.id):selected.includes(c.id)} disabled={busy||job.status!=='awaiting_approval'||!c.passageMatched||!c.reviewPassed} onChange={()=>setSelected(selected.includes(c.id)?selected.filter(v=>v!==c.id):[...selected,c.id])}/><strong>{c.path.startsWith('blocks.')?`Note paragraph ${Number(c.path.split('.')[1])+1}`:c.path.replaceAll('.',' › ')}</strong></label><p>{c.reason}</p><div className="evidence-compare"><div><h4>Before</h4><p>{c.before}</p></div><div><h4>Proposed</h4><p>{c.after}</p></div></div><p>{c.passageMatched?'Source passage matched.':'Source quotation needs review.'} {c.reviewPassed?'Model review passed; your judgment is still required.':c.reviewIssue||'Independent review required.'}</p>{(c.evidence||[]).map((e,i)=><details key={i}><summary>Source: {job.result.sources?.find(s=>s.id===e.sourceId)?.filename||'Unavailable'}</summary><blockquote>{e.excerpt}</blockquote></details>)}</article>)}
    {job.status==='awaiting_approval'&&!changes.length&&<p>No supported edits were proposed from these documents.</p>}
    {job.status==='awaiting_approval'&&!!changes.length&&<><p>{job.kind==='note'?'Applying creates a new note draft. The published note stays unchanged until you accept the draft. Review any inherited charts before publishing.':'Applying saves a new review version and regenerates its memo and PDF. The original remains in history.'}</p><button className="workspace-primary" disabled={busy||!selected.length} onClick={()=>decide('apply')}>Apply {selected.length} selected edits</button></>}
    {job.status==='applied'&&<p>{job.kind==='note'?'A new note draft is ready in Research Pipeline.':'A new investment review version is saved.'} {onApplied&&<button onClick={()=>onApplied({kind:job.kind,id:job.result.createdId})}>Refresh saved research</button>}</p>}</>}
  </details>;
}
