import * as React from 'react';
import {downloadText} from './stock-analysis-model.mjs';
const outputs=[['summary_note','Summary note'],['stock_summary','Stock summary'],['thesis','Thesis draft / update'],['visual','Visual one-pager draft']];
const date=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export function ResearchAssignment({api,ticker,onReport,disabled}){
 const [since,setSince]=React.useState(()=>{const d=new Date();d.setDate(d.getDate()-69);return date(d);}),[until,setUntil]=React.useState(()=>date(new Date())),[chosen,setChosen]=React.useState(outputs.map(x=>x[0])),[horizon,setHorizon]=React.useState('12–24 months'),[instruction,setInstruction]=React.useState('');
 const [jobs,setJobs]=React.useState([]),[busy,setBusy]=React.useState(false),[message,setMessage]=React.useState(''),[error,setError]=React.useState(''),[ack,setAck]=React.useState(false);
 const locked=React.useRef(false),pending=React.useRef(null),generation=React.useRef(0);
 const request=async(path,body,method='POST')=>{const r=await fetch(api+'/api/research/'+path,{...(body?{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});let d;try{d=await r.json();}catch{throw Error('Response unavailable. Your request identity is retained; check saved assignments before retrying.');}if(!r.ok)throw Error(d.error||'Research assignment unavailable');return d;};
 React.useEffect(()=>{let live=true;request('assignment-defaults').then(d=>{if(live){setChosen(d.outputs);setHorizon(d.horizon);}}).catch(()=>{});return()=>{live=false;};},[api]);
 React.useEffect(()=>{let live=true,inflight=false;generation.current++;setJobs([]);setAck(false);const load=async()=>{if(inflight)return;inflight=true;try{const d=await request('assignments?ticker='+encodeURIComponent(ticker));if(live){setJobs(d.assignments);setError('');}}catch(e){if(live)setError(e.message);}finally{inflight=false;}};load();const timer=setInterval(load,6000);return()=>{live=false;generation.current++;clearInterval(timer);};},[api,ticker]);
 const mutate=async fn=>{if(locked.current)return;const g=generation.current;locked.current=true;setBusy(true);setMessage('');try{const msg=await fn();if(g===generation.current){const d=await request('assignments?ticker='+encodeURIComponent(ticker));if(g===generation.current){setJobs(d.assignments);setMessage(msg);}}}catch(e){if(g===generation.current)setMessage(e.message);}finally{locked.current=false;setBusy(false);}};
 const start=()=>mutate(async()=>{const p={ticker,since,until,outputs:[...chosen].sort(),horizon,instruction};const signature=JSON.stringify(p);if(pending.current?.signature!==signature)pending.current={signature,body:{...p,requestId:crypto.randomUUID()}};await request('assignments',pending.current.body);pending.current=null;return 'Assignment saved. Charlie will collect originals and prepare your requested drafts. You can close this page.';});
 const unfinished=jobs.some(j=>['queued','running','attention'].includes(j.status));
 return <section className="sa-prepare" aria-label="End-to-end research"><h4>One research assignment</h4><p>For <strong>{ticker}</strong>, collect new originals and prepare the outputs you choose.</p>
 <fieldset disabled={disabled||busy||unfinished||!!error}><div className="sa-form-grid"><label>From<input aria-label="Research from" type="date" value={since} max={until} onChange={e=>setSince(e.target.value)}/></label><label>Through<input aria-label="Research through" type="date" value={until} min={since} max={date(new Date())} onChange={e=>setUntil(e.target.value)}/></label></div>
 <div className="sa-form-grid">{outputs.map(([id,title])=><label className="sa-check" key={id}><input type="checkbox" checked={chosen.includes(id)} onChange={e=>setChosen(p=>e.target.checked?[...p,id]:p.filter(x=>x!==id))}/>{title}</label>)}</div>
 <details><summary>Research focus and defaults</summary><label>Investment horizon<input value={horizon} maxLength={100} onChange={e=>setHorizon(e.target.value)}/></label><label>Focus or questions (optional)<textarea value={instruction} maxLength={1800} onChange={e=>setInstruction(e.target.value)} rows={3}/></label><button disabled={!chosen.length} onClick={()=>mutate(async()=>{await request('assignment-defaults',{outputs:chosen,horizon},'PUT');return 'Output choices and horizon saved for your next assignment.';})}>Save my defaults</button></details>
 <button className="sa-primary" disabled={!chosen.length||!since||!until||!horizon.trim()} onClick={start}>Start research for {ticker}</button></fieldset>
 <p><small>One shared research run: up to eight selected originals and twelve model calls within your configured budget. Starting authorizes these calls. Draft outputs need investor review; a thesis update is never applied automatically.</small></p>
 <details><summary>How automatic collection works</summary><p>Charlie queues collection → Codex searches AlphaSense → originals are saved in iCloud STOCKS → your Mac imports and verifies them → Charlie researches and prepares the selected drafts. Keep your Mac awake, online, the agent running, and Codex with signed-in Chrome available. Collection starts on an available scheduled worker, usually the next 15-minute wake. Source restrictions, sign-in, source choices and uncertain paid-call outcomes can require your attention. The research uses the selected source pack; missing prices, consensus or financial periods remain gaps.</p></details>
 {error&&<p role="alert">{error}</p>}<p role="status">{message}</p>
 {jobs.map(j=><article key={j.id} style={{borderTop:'1px solid #d8dedd',paddingTop:12,marginTop:12}}><strong>{j.input.since}–{j.input.until} · {j.status}</strong><p>{j.result.step}</p>{j.result.delayWarning&&<p role="alert">{j.result.delayWarning}</p>}<small>Saved update: {new Date(j.updated_at).toLocaleString()}{j.result.macReportedAt?' · Mac report: '+new Date(j.result.macReportedAt).toLocaleString():''}</small>{j.result.sources&&<p>{j.result.sources.length} originals verified · {j.result.researchStages||0}/12 research stages</p>}{j.error&&<p role="alert">{j.error}</p>}
 <div className="sa-actions">{j.result.reportId&&<button onClick={()=>onReport(j.result.reportId)}>Open research report</button>}{j.result.artifacts?.map(a=><button key={a.kind} disabled={busy} onClick={()=>mutate(async()=>{const r=await fetch(api+a.url,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('Output could not be loaded. Saved output remains in the assignment.');downloadText(await r.text(),`${ticker}-${a.kind}-${j.id.slice(0,8)}.html`);return 'Draft exported as printable HTML.';})}>Export {outputs.find(x=>x[0]===a.kind)?.[1]}</button>)}{j.result.thesisDraftId&&<a href={`?thesisDraft=${j.result.thesisDraftId}#view=thesisimports&ticker=${encodeURIComponent(ticker)}`}>Review thesis proposal</a>}</div>
 {j.status==='attention'&&<><label className="sa-check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>If a paid call is uncertain, I checked usage and accept that retry may charge again.</label><button disabled={busy} onClick={()=>mutate(async()=>{await request(`assignments/${j.id}/resume`,{acknowledgeRetry:ack});return 'Resume requested; saved stages are retained.';})}>Resume assignment</button><a href="#view=desk">Collection and source choices</a></>}
 {['queued','running','attention'].includes(j.status)&&<button disabled={busy} onClick={()=>mutate(async()=>{await request(`assignments/${j.id}/stop`,{});return 'Stopped. Originals and saved drafts are retained; a call already running may finish.';})}>Stop assignment</button>}
 </article>)}
 </section>;
}
