import {ResearchHistory} from './research-history';
import {PortfolioPriorities} from './portfolio-priorities';
import {CollectionCloud} from './collection-cloud';
import {EarningsWorkspace} from './earnings-workspace';
import {EvidenceWorkspace} from './evidence-workspace';
import * as React from 'react';
import {parseTickers,researchQueue,runCounts,runsNeedingStatusCheck,PLAYBOOKS} from './research-desk-model.mjs';
import {parseTimestamp} from './workspace-model.mjs';
const {useState,useEffect,useRef}=React;
const stamp=v=>parseTimestamp(v)?.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})||'Date unavailable';
function Status({value}) {return <span className={`desk-status desk-status-${value}`}>{String(value||'unknown').replaceAll('_',' ')}</span>;}
function ReportContent({value,renderHtml,depth=0}) {
  if(value==null)return <p className="desk-explainer">No report attached yet.</p>;
  if(typeof value==='object'&&depth<4)return Array.isArray(value)?<div>{value.map((v,i)=><ReportContent key={i} value={v} renderHtml={renderHtml} depth={depth+1}/>)}</div>:<div>{Object.entries(value).filter(([,v])=>v!=null).map(([key,v])=><section className="desk-report-section" key={key}><h3>{key.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ')}</h3><ReportContent value={v} renderHtml={renderHtml} depth={depth+1}/></section>)}</div>;
  const text=typeof value==='object'?JSON.stringify(value,null,2):String(value);
  return renderHtml?<div className="desk-report-prose" dangerouslySetInnerHTML={{__html:renderHtml(text)}}/>:<pre>{text}</pre>;
}
export function ResearchDesk({api,analyses,onCompany,onNavigate,renderHtml,renderRecapHtml}) {
  const [data,setData]=useState({runs:[],activities:[],failed:[],analysts:[],providers:{},capabilities:{maxConcurrency:1,maxBatchSize:12}});
  const [errors,setErrors]=useState([]),[loading,setLoading]=useState(true),[updated,setUpdated]=useState(null);
  const [section,setSection]=useState('overview'),[days,setDays]=useState(90),[query,setQuery]=useState('');
  const [tickers,setTickers]=useState(''),[provider,setProvider]=useState('anthropic'),[model,setModel]=useState('');
  const [date,setDate]=useState(new Date().toLocaleDateString('en-CA')),[concurrency,setConcurrency]=useState(1);
  const [review,setReview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[detailError,setDetailError]=useState('');
  const [saved,setSaved]=useState(()=>{try {const v=JSON.parse(localStorage.getItem('charlie.desk.plans')||'[]');return Array.isArray(v)?v:[];}catch{return [];}});
  const [planName,setPlanName]=useState('');
  const alive=useRef(true),request=useRef(0),launchLock=useRef(false);
  const fetchJson=async path=>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const res=await fetch(`${api}${path}`,{signal:controller.signal});if(!res.ok)throw new Error(res.status===401?'Sign in to load this data.':`Request failed (${res.status})`);const result=await res.json();if(result.error)throw new Error(result.error);return result;}finally{clearTimeout(timer);}};
  const refresh=async()=>{
    const id=++request.current;
    const sources=[['runs','/api/agents/results?limit=100','runs'],['activities','/api/analyst-activities/pending','activities'],['failed','/api/analyst-activities/failed?limit=100','activities'],['analysts','/api/analysts','analysts'],['providers','/api/agents/providers',null],['capabilities','/api/agents/capabilities',null]];
    const results=await Promise.allSettled(sources.map(([,path])=>fetchJson(path)));
    if(!alive.current||id!==request.current)return;
    const next={},failed=[];
    results.forEach((r,i)=>{const [key,,field]=sources[i];if(r.status==='fulfilled')next[key]=field?r.value[field]||[]:r.value;else if(key!=='capabilities')failed.push(`${key}: ${r.reason.message}`);});
    setData(old=>({...old,...next}));setErrors(failed);setLoading(false);setUpdated(new Date());
  };
  useEffect(()=>{alive.current=true;refresh();const timer=setInterval(()=>{if(!document.hidden)refresh();},30000);return()=>{alive.current=false;clearInterval(timer);request.current++;};},[api]);
  useEffect(()=>{const models=data.providers[provider]||[];if(!models.includes(model))setModel(models[0]||'');},[provider,data.providers]);
  useEffect(()=>{if(!selected)return;let current=true;setDetail(null);setDetailError('');fetchJson(`/api/agents/status/${encodeURIComponent(selected.id)}`).then(d=>{if(current)setDetail(d);}).catch(e=>{if(current)setDetailError(e.message);});return()=>{current=false;};},[selected]);
  const parsed=parseTickers(tickers),counts=runCounts(data.runs),statusChecks=runsNeedingStatusCheck(data.runs),queue=researchQueue(analyses,days),pending=data.activities.filter(a=>a.status==='pending_review');
  const max=Math.min(12,data.capabilities.maxBatchSize||12),valid=parsed.tickers.length>0&&parsed.tickers.length<=max&&!parsed.invalid.length&&!!model&&!!date;
  const prepare=values=>{setTickers(values.join(', '));setSection('launch');setReview(false);setMessage('');};
  const savePlan=()=>{if(!planName.trim()||!valid)return;const plan={name:planName.trim().slice(0,60),tickers,provider,model,concurrency};const next=[plan,...saved.filter(p=>p.name!==plan.name)].slice(0,12);try{localStorage.setItem('charlie.desk.plans',JSON.stringify(next));setSaved(next);setPlanName('');setMessage('Plan saved in this browser.');}catch{setMessage('This browser could not save the plan.');}};
  const launch=async()=>{
    if(!valid||launchLock.current)return;launchLock.current=true;setBusy(true);setMessage('');
    try {const res=await fetch(`${api}/api/agents/batch-run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tickers:parsed.tickers,date,provider,model,concurrency})});const result=await res.json();if(!res.ok)throw new Error(result.error||'Could not start batch');setMessage(`Submitted ${result.count} company teams. Track their progress in Runs.`);setReview(false);setSection('runs');await refresh();}
    catch(e){setMessage(`Submission could not be confirmed: ${e.message}. Check Runs before trying again.`);setSection('runs');await refresh();}
    finally{setBusy(false);launchLock.current=false;}
  };
  return <div className="workspace-page research-desk">
    <div className="desk-heading"><div><p className="workspace-eyebrow">CHARLIE / RESEARCH OPERATIONS</p><h1>Your research desk.</h1><p className="workspace-lead">Prioritize the next question. Coordinate the team. Review the evidence.</p></div><button className="workspace-primary" onClick={()=>setSection('launch')}>Prepare a research batch ↗</button></div>
    <div className="desk-toolbar"><nav aria-label="Research desk sections">{[['overview','Overview'],['collection','Collection'],['history','Research history'],['priorities','Portfolio priorities'],['earnings','Earnings & evidence'],['evidence','Evidence & changes'],['inbox','Review inbox'],['queue','Coverage queue'],['launch','Batch planner'],['runs','Runs'],['playbooks','Playbooks']].map(([id,label])=><button key={id} aria-current={section===id?'page':undefined} onClick={()=>setSection(id)}>{label}</button>)}</nav><button onClick={refresh} disabled={loading}>{loading?'Loading…':'Refresh'}{updated&&<small>Updated {updated.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small>}</button></div>
    {errors.length>0&&<div className="workspace-error" role="alert">Some live data could not be refreshed. Previously loaded records may be out of date.<details><summary>Connection details</summary>{errors.map(e=><p key={e}>{e}</p>)}</details><button onClick={refresh}>Retry</button></div>}
    {message&&<p className="workspace-notice" role="status">{message}</p>}
    {section==='overview'&&['127.0.0.1','localhost'].includes(window.location.hostname)&&<section className="workspace-panel"><div className="workspace-section-heading"><div><p className="workspace-eyebrow">SOURCE OPERATIONS</p><h2>AlphaSense collection</h2></div><a className="workspace-link-row" href="http://127.0.0.1:8766/" target="_blank" rel="noopener noreferrer">Open collection monitor ↗</a></div><p className="desk-explainer">Manage ticker refresh schedules, verified originals, iCloud handoffs, and source restrictions. The monitor runs on this Mac.</p></section>}
    {loading?<p className="workspace-empty" role="status">Loading research activity…</p>:<>
    {section==='history'&&<ResearchHistory api={api} onSection={setSection} onNavigate={onNavigate}/>}
    {section==='earnings'&&<EarningsWorkspace api={api} onRefresh={refresh} activities={[...data.activities,...data.failed]} onNavigate={onNavigate} onCompany={onCompany} renderHtml={renderRecapHtml||renderHtml}/>}
    {section==='evidence'&&<EvidenceWorkspace api={api} analyses={analyses} onCompany={onCompany}/>}
    {section==='overview'&&<>
      <div className="desk-metrics">{[[counts.active,'Active in latest 100 runs','runs'],[pending.length,'Awaiting your review','inbox'],[queue.length,`Theses ${days}+ days old or undated`,'queue'],[data.analysts.length,'Sector analysts','playbooks']].map(([n,label,id])=><button key={label} onClick={()=>setSection(id)}><strong>{n}</strong><span>{label}</span><small>Open →</small></button>)}</div>
      {statusChecks.length>0&&<p className="workspace-notice">{statusChecks.length} run(s) have been marked active for more than two hours. Their status may be stale. <button className="underline" onClick={()=>setSection('runs')}>Inspect runs →</button></p>}
      <div className="desk-columns"><section className="workspace-panel"><div className="workspace-section-heading"><h2>The next research pass</h2><button onClick={()=>setSection('queue')}>View queue ↗</button></div><p className="desk-explainer">Prioritized by thesis age. This identifies research maintenance, not investment attractiveness.</p>{queue.slice(0,5).map(a=><div className="desk-row" key={a.ticker}><button onClick={()=>onCompany(a.ticker,'portfolio')}><strong>{a.ticker}</strong><span>{a.companyName||a.company||'Investment thesis'}</span></button><small>{a.age===null?'Undated':`${a.age} days`}</small><button onClick={()=>prepare([a.ticker])}>Research →</button></div>)}{!queue.length&&<p className="workspace-empty">No theses meet this age threshold.</p>}</section>
      <section className="workspace-panel desk-team-flow"><p className="workspace-eyebrow">HOW THE TEAM WORKS</p><h2>Independent research. A challenged conclusion.</h2><ol><li><b>01</b><div><strong>Gather evidence</strong><p>Market, fundamentals, news and sentiment analysts contribute specialized reports.</p></div></li><li><b>02</b><div><strong>Debate the case</strong><p>Bull and bear researchers challenge the conclusions before risk review.</p></div></li><li><b>03</b><div><strong>Review the decision</strong><p>Read the combined output and compare it with your saved thesis.</p></div></li></ol><button className="workspace-link-row" onClick={()=>setSection('launch')}>Coordinate a batch →</button></section></div>
      <section className="workspace-panel"><div className="workspace-section-heading"><h2>Analyst review inbox</h2><button onClick={()=>onNavigate('analysts')}>Open analyst team ↗</button></div>{pending.slice(0,6).map(a=><div className="desk-row" key={a.id}><div><strong>{a.ticker||a.analystName||'Research activity'}</strong><p>{a.activityType?.replaceAll('_',' ')} · {a.analystName}</p></div><Status value={a.status}/><button onClick={()=>onNavigate('analysts')}>Review in inbox →</button></div>)}{!pending.length&&<p className="workspace-empty">No analyst output is waiting for review.</p>}</section>
    </>}
    {section==='inbox'&&<section className="workspace-panel"><div className="workspace-section-heading"><h2>Analyst review inbox</h2><button onClick={()=>onNavigate('analysts')}>Open analyst controls ↗</button></div><p className="desk-explainer">Read the proposed research before approving or revising it in Analyst team.</p>{pending.map(a=><details className="desk-inbox-item" key={a.id}><summary><strong>{a.ticker||a.analystName}</strong><span>{a.activityType?.replaceAll('_',' ')} · {a.analystName}</span><small>{stamp(a.createdAt)}</small></summary><div className="desk-inbox-report"><h3>{a.output ? 'Research output' : 'Proposed work'}</h3>{a.output?.synthesisMarkdown ? <><p className="desk-explainer">Draft ready · {a.output.fileCount || a.output.sourceFiles?.length || 0} sources · Completed {stamp(a.output.completedAt)}</p><ReportContent value={a.output.synthesisMarkdown} renderHtml={renderRecapHtml || renderHtml}/><details><summary>Source documents and provenance</summary><ReportContent value={{sources:a.output.sourceFiles,provenance:a.output.sourceProvenance}} renderHtml={renderHtml}/></details></> : <ReportContent value={a.output || a.input} renderHtml={renderHtml}/>}</div><button className="workspace-link-row" onClick={()=>onNavigate('analysts')}>Review in analyst team →</button></details>)}{!pending.length&&<p className="workspace-empty">No analyst output is awaiting review.</p>}</section>}
    {section==='priorities'&&<PortfolioPriorities api={api} analyses={analyses} activities={[...data.activities,...data.failed]} onCompany={onCompany} onPlan={prepare}/>}
    {section==='collection'&&<CollectionCloud api={api} coverage={analyses}/>}
    {section==='queue'&&<section className="workspace-panel"><div className="workspace-section-heading"><h2>Coverage maintenance</h2><button onClick={()=>prepare(queue.slice(0,max).map(a=>a.ticker))} disabled={!queue.length}>Plan oldest {Math.min(queue.length,max)} →</button></div><div className="desk-filter"><label>Review threshold<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[30,60,90,180].map(d=><option key={d} value={d}>{d} days</option>)}</select></label><label>Find a company<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ticker or company"/></label></div><p className="desk-explainer">Age is based on the saved thesis timestamp. Undated theses also appear here. Starting a batch creates new research; it does not overwrite the thesis.</p>{queue.filter(a=>`${a.ticker} ${a.companyName||a.company||''}`.toLowerCase().includes(query.toLowerCase())).map(a=><div className="desk-row" key={a.ticker}><button onClick={()=>onCompany(a.ticker,'portfolio')}><strong>{a.ticker}</strong><span>{a.companyName||a.company}</span></button><small>{a.age===null?'Undated':`${a.age} days old`}</small><button onClick={()=>prepare([a.ticker])}>Plan research →</button></div>)}{!queue.length&&<p className="workspace-empty">No theses meet this review threshold.</p>}</section>}
    {section==='launch'&&<div className="desk-columns"><section className="workspace-panel"><p className="workspace-eyebrow">RESEARCH BATCH</p><h2>One brief. Multiple company teams.</h2><p className="desk-explainer">Each company receives the existing multi-agent analysis. Results are saved as agent runs for your review.</p><fieldset disabled={busy} className="desk-form"><label>Companies<textarea aria-label="Batch tickers" value={tickers} onChange={e=>{setTickers(e.target.value);setReview(false);}} placeholder="DE, CAT, ETN" rows={3}/></label><small>{parsed.tickers.length} / {max} companies · comma or space separated</small>{parsed.invalid.length>0&&<p role="alert">Unrecognized symbols: {parsed.invalid.join(', ')}</p>}{parsed.tickers.length>max&&<p role="alert">Limit this batch to {max} companies.</p>}<div className="desk-filter"><label>Provider<select value={provider} onChange={e=>{setProvider(e.target.value);setReview(false);}}>{Object.keys(data.providers).map(p=><option key={p}>{p}</option>)}</select></label><label>Analysis date<input type="date" value={date} onChange={e=>{setDate(e.target.value);setReview(false);}}/></label></div><label>Model<select value={model} onChange={e=>{setModel(e.target.value);setReview(false);}}>{(data.providers[provider]||[]).map(m=><option key={m}>{m}</option>)}</select></label><label>Simultaneous company teams<select value={concurrency} onChange={e=>{setConcurrency(Number(e.target.value));setReview(false);}}>{Array.from({length:Math.min(3,data.capabilities.maxConcurrency||1)},(_,i)=><option key={i+1} value={i+1}>{i+1}{i===0?' · sequential':''}</option>)}</select></label>{data.capabilities.maxConcurrency===1&&<p className="desk-explainer">This backend currently supports sequential batches. The parallel-execution backend update unlocks up to three simultaneous teams.</p>}<button className="workspace-primary" disabled={!valid} onClick={()=>setReview(true)}>Review batch →</button></fieldset>
      {review&&<section className="desk-confirm" aria-label="Batch confirmation"><h3>Ready to start {parsed.tickers.length} company teams?</h3><p>{parsed.tickers.join(' · ')}</p><p>{provider} / {model}<br/>{date} · {concurrency} at a time</p><p>Uses paid model APIs. Total cost varies by model and research depth. Outputs remain separate from your saved theses.</p><button className="workspace-primary" disabled={busy||!valid} onClick={launch}>{busy?'Submitting…':'Start research batch'}</button><button disabled={busy} onClick={()=>setReview(false)}>Keep editing</button></section>}
    </section><div><section className="workspace-panel"><h2>Reusable plans</h2><p className="desk-explainer">Save company groups and model preferences in this browser. Loading a plan never starts a run.</p><div className="desk-form"><label>Plan name<input value={planName} onChange={e=>setPlanName(e.target.value)} placeholder="Industrial coverage review"/></label><button className="workspace-secondary" disabled={!valid||!planName.trim()} onClick={savePlan}>Save current plan</button></div>{saved.map(p=><button key={p.name} className="desk-plan" onClick={()=>{setTickers(p.tickers);setProvider(p.provider);setModel(p.model);setConcurrency(Math.min(p.concurrency||1,data.capabilities.maxConcurrency||1));setReview(false);}}><strong>{p.name}</strong><small>{p.tickers}</small></button>)}</section><section className="workspace-panel"><h2>Execution contract</h2><ul className="desk-contract"><li>One company per research team.</li><li>Independent teams may run concurrently when supported by the backend.</li><li>A failed team does not stop sibling teams.</li><li>These are background jobs, not recurring schedules.</li><li>Backend restarts can interrupt work; review run status before retrying.</li></ul></section></div></div>}
    {section==='runs'&&<section className="workspace-panel"><div className="workspace-section-heading"><h2>Research runs</h2><span>Latest 100 · updates every 30 seconds while visible</span></div>{data.runs.map(r=><button className="desk-run" key={r.id} onClick={()=>setSelected(r)}><strong>{r.ticker}</strong><span>{r.model}<small>{stamp(r.createdAt)}</small></span><Status value={r.status}/><span>Inspect →</span></button>)}{!data.runs.length&&<p className="workspace-empty">No agent runs have been recorded. Prepare your first batch when you are ready.</p>}</section>}
    {section==='playbooks'&&<><div className="workspace-create-grid">{PLAYBOOKS.map(p=><section className="workspace-panel" key={p.id}><p className="workspace-eyebrow">{p.tag}</p><h2>{p.name}</h2><p className="desk-explainer">{p.description}</p><ol className="desk-contract">{p.steps.map(s=><li key={s}>{s}</li>)}</ol><button className="workspace-link-row" onClick={()=>p.id==='refresh'?setSection('launch'):onNavigate(p.view)}>Open workflow →</button></section>)}</div><section className="workspace-panel"><h2>Your sector analysts</h2><p className="desk-explainer">Specialized coverage and research instructions are managed in Analyst team.</p><div className="desk-roster">{data.analysts.map(a=><button key={a.id} onClick={()=>onNavigate('analysts')}><strong>{a.name}</strong><span>{a.sector} · {a.coverageTickers?.length||0} companies</span><small>{a.pendingCount||0} awaiting review · {a.autoMode?.enabled?'Auto mode enabled':'Manual review'}</small></button>)}</div>{!data.analysts.length&&<button className="workspace-link-row" onClick={()=>onNavigate('analysts')}>Configure your analyst team →</button>}</section></>}
    </>}
    {selected&&<section className="desk-detail" role="region" aria-label={`${selected.ticker} run details`}><div className="workspace-section-heading"><h2>{selected.ticker} research run</h2><button autoFocus onClick={()=>setSelected(null)}>Close</button></div><Status value={detail?.status||selected.status}/><p className="desk-explainer">Saved {stamp(selected.createdAt)} · Analysis date {selected.analysisDate} · {selected.model}</p>{detailError?<p role="alert">{detailError}</p>:!detail?<p role="status">Loading run…</p>:<><h3>Decision</h3><ReportContent value={detail.decision||'No decision yet.'} renderHtml={renderHtml}/><details><summary>Research reports</summary><ReportContent value={detail.report} renderHtml={renderHtml}/></details><details><summary>Execution log</summary><pre>{(detail.newLogs||[]).map(l=>typeof l==='string'?l:JSON.stringify(l)).join('\n')||'No log entries.'}</pre></details><button className="workspace-link-row" onClick={()=>{setSelected(null);onCompany(selected.ticker,'portfolio');}}>Compare with saved thesis →</button></>}</section>}
  </div>;
}
