import * as React from 'react';
import {ResearchRestore} from './research-restore';
import {parseTimestamp} from './workspace-model.mjs';
const stamp=v=>parseTimestamp(v)?.toLocaleString()||'Date unavailable';
const labels={source:'Source imported',note:'Note version',review:'Review version',activity:'Analyst activity',job:'Research / control request',collection:'Browser collection'};
export function ResearchHistory({api,onSection,onNavigate}) {
  const [restoreRecord,setRestoreRecord]=React.useState(null);
  const [input,setInput]=React.useState(''),[ticker,setTicker]=React.useState(''),[kind,setKind]=React.useState('all'),[data,setData]=React.useState(null),[error,setError]=React.useState(''),[refresh,setRefresh]=React.useState(0);
  React.useEffect(()=>{let active=true;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);setData(null);setError('');
    fetch(`${api}/api/research/workspace-history${ticker?`?ticker=${encodeURIComponent(ticker)}`:''}`,{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||`History unavailable (${r.status})`);if(active)setData(d);}).catch(e=>{if(active)setError(e.message);}).finally(()=>clearTimeout(timer));return()=>{active=false;controller.abort();clearTimeout(timer);};
  },[api,ticker,refresh]);
  const rows=(data?.records||[]).filter(r=>kind==='all'||r.kind===kind);
  const open=r=>r.kind==='collection'||(r.kind==='job'&&r.title==='collection_control')?onSection('collection'):r.kind==='activity'?onNavigate('analysts'):r.kind==='note'?onNavigate('pipeline'):onSection('evidence');
  return <section className="workspace-panel"><p className="workspace-eyebrow">RESEARCH HISTORY</p><h2>From source intake to saved research.</h2><p className="desk-explainer">Browse imports, collection requests, analyst activities and saved document versions together. Each row shows a real stored record and its current status.</p>
    <form className="desk-filter" onSubmit={e=>{e.preventDefault();setTicker(input.trim().toUpperCase());setRefresh(n=>n+1);}}><label>Ticker<input value={input} onChange={e=>setInput(e.target.value)} maxLength={20} placeholder="All companies"/></label><label>Record type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All records</option>{Object.entries(labels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><button type="submit">Load history</button></form>
    {restoreRecord&&<ResearchRestore key={restoreRecord.recordId} api={api} record={restoreRecord} onClose={()=>setRestoreRecord(null)} onRestored={()=>setRefresh(n=>n+1)}/>}
    {error?<p className="workspace-error" role="alert">{error} <button onClick={()=>setRefresh(n=>n+1)}>Retry</button></p>:!data?<p role="status">Loading saved history…</p>:<><p className="desk-explainer">{data.scope}</p><p>{rows.length} shown · Mac collection snapshot: {stamp(data.collectionReportedAt)}</p>{!rows.length&&<p>No records match this view. Broaden the record filter or select a ticker to search its latest history.</p>}
    <ol className="research-history-list">{rows.map(r=><li key={r.id}><article><div className="workspace-section-heading"><div><small>{labels[r.kind]} · {r.ticker||'Coverage group'}</small><h3>{r.title.replaceAll('_',' ')}</h3></div><span className="desk-status">{r.status.replaceAll('_',' ')}</span></div><p>Created {stamp(r.createdAt)}{r.updatedAt&&r.updatedAt!==r.createdAt?` · Updated ${stamp(r.updatedAt)}`:''}</p>{(r.parentId||r.proposalId)&&<details><summary>Recorded version links</summary>{r.parentId&&<p>Parent / target document: {r.parentId}</p>}{r.proposalId&&<p>Revision proposal: {r.proposalId}</p>}</details>}<details><summary>Record identifier</summary><code>{r.recordId}</code></details>{['note','review'].includes(r.kind)&&<button onClick={()=>setRestoreRecord(r)}>Preview restoration</button>}<button onClick={()=>open(r)}>Open {r.kind==='collection'?'collection controls':r.kind==='activity'?'Analyst team':r.kind==='note'?'Research Pipeline':'related workspace'} →</button></article></li>)}</ol></>}
  </section>;
}
