import * as React from 'react';
import {ResearchChat} from './research-chat';
const today=()=>new Date().toLocaleDateString('en-CA');
const inputs={revenueMillions:'',sharesMillions:'',beforeMarginPct:'',afterMarginPct:'',taxPct:'',baselineEPS:'',multiple:'',referencePrice:'',currency:'USD',period:'',basis:'Adjusted diluted EPS',asOf:today()};
const blank=()=>({kind:'model',title:'',owner:'Me',rationale:'',nextAction:'',dueDate:today(),status:'open',assumptionId:'',inputs:{...inputs},sourceId:'',sourceHash:'',passage:'',answerId:'',answerHash:'',resolution:'unresolved',mandate:'',benchmark:'',asOf:today(),holdingPct:'0',benchmarkPct:'',reason:'valuation',valuationAssessment:'',outcome:'',reviewConditions:[],reviewDecision:'pending'});
async function json(api,path,options={}){const r=await fetch(api+path,{...options,signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok){const e=Error(d.error||'Work unavailable');e.status=r.status;throw e;}return d;}
export function ResearchWorkbench({api,ticker,caseRevision,assumptions=[],disabled=false,initialKind='model'}){
 const [data,setData]=React.useState({records:[],sources:[],answers:[]}),[draft,setDraft]=React.useState(()=>({...blank(),kind:initialKind})),[record,setRecord]=React.useState(null),[busy,setBusy]=React.useState(false),[message,setMessage]=React.useState(''),[history,setHistory]=React.useState(null);
 const [debate,setDebate]=React.useState(null);
 const pending=React.useRef(null),lock=React.useRef(false),alive=React.useRef(true),sequence=React.useRef(0);
 const load=async()=>{const seq=++sequence.current;try{const d=await json(api,'/api/research/workbench/'+ticker);if(alive.current&&seq===sequence.current)setData(d);}catch(e){if(alive.current)setMessage(e.message);}};
 React.useEffect(()=>{alive.current=true;load();return()=>{alive.current=false;};},[]);
 const edit=(key,v)=>{pending.current=null;setDraft(d=>({...d,[key]:v}));};
 const save=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('Saving reviewed work…');const p=pending.current||{requestId:crypto.randomUUID(),id:record?.id||crypto.randomUUID(),revision:record?.revision||0,body:{...draft,caseRevision}};pending.current=p;
 try{const r=await json(api,'/api/research/workbench/'+ticker,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});if(alive.current){setRecord({id:r.id,revision:r.revision});pending.current=null;setMessage('Saved a work revision. Investment case and portfolio positions were not changed.');await load();}}
 catch(e){if(e.status===409)pending.current=null;if(alive.current)setMessage(e.message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
 const input=(key,label,type='text')=><label>{label}<input type={type} value={draft[key]??''} onChange={e=>edit(key,e.target.value)}/></label>;
 return <details open className="research-decision-log"><summary>Research workbench · {data.records.length} records</summary><p className="desk-explainer">Connect an assumption to a calculation, meeting follow-up or underweight review. Reviewed records preserve your reasoning; they do not execute trades or update a spreadsheet.</p>
 {(!caseRevision||!assumptions.length)&&<p>Save an investment case with at least one assumption to start connected work.</p>}<fieldset disabled={busy||disabled||!caseRevision||!assumptions.length}><label>Work type<select aria-label="Work type" disabled={!!record} value={draft.kind} onChange={e=>edit('kind',e.target.value)}><option value="model">Source → model sensitivity</option><option value="followup">Meeting answer → follow-up</option><option value="underweight">Underweight / nonownership review</option></select></label>
 {input('title','Research question / title')}{input('owner','Owner')}{input('dueDate','Next action due','date')}
 <label>Investment assumption<select aria-label="Investment assumption" value={draft.assumptionId} onChange={e=>edit('assumptionId',e.target.value)}><option value="">Choose a saved assumption</option>{assumptions.map(a=><option value={a.id} key={a.id}>{a.claim}</option>)}</select></label>
 {draft.kind==='model'&&<><p>Single operating-margin change. Enter revenue and diluted shares in millions, consistent currency and period. Baseline EPS is your model input; all other drivers stay constant.</p><label>Supporting original<select aria-label="Supporting original" value={draft.sourceId} onChange={e=>{const s=data.sources.find(x=>x.id===Number(e.target.value));edit('sourceId',s?.id||'');edit('sourceHash',s?.hash||'');}}><option value="">Choose saved original</option>{data.sources.map(s=><option key={s.id} value={s.id}>{s.filename}</option>)}</select></label><label>Exact supporting passage<textarea value={draft.passage} onChange={e=>edit('passage',e.target.value)}/></label><p className="desk-explainer">Passage matching establishes provenance. Your numerical interpretation still requires review.</p>
 <div className="workbench-grid">{Object.entries({revenueMillions:'Revenue · millions',sharesMillions:'Diluted shares · millions',beforeMarginPct:'Baseline operating margin %',afterMarginPct:'Proposed operating margin %',taxPct:'Marginal tax rate %',baselineEPS:'Baseline EPS',multiple:'Valuation P/E',referencePrice:'Reference share price',currency:'Currency',period:'Fiscal forecast period',basis:'Accounting / EPS basis',asOf:'Reference date'}).map(([key,label])=><label key={key}>{label}<input type={key==='asOf'?'date':'text'} value={draft.inputs[key]||''} onChange={e=>edit('inputs',{...draft.inputs,[key]:e.target.value})}/></label>)}</div></>}
 {draft.kind==='followup'&&<><label>Recorded meeting answer<select aria-label="Recorded meeting answer" value={draft.answerId} onChange={e=>{const a=data.answers.find(x=>x.id===Number(e.target.value));edit('answerId',a?.id||'');edit('answerHash',a?.hash||'');}}><option value="">Choose an actual answer</option>{data.answers.map(a=><option key={a.id} value={a.id}>{a.question}</option>)}</select></label><blockquote>{data.answers.find(a=>a.id===draft.answerId)?.response_notes}</blockquote><label>Does it resolve the issue?<select aria-label="Does it resolve the issue?" value={draft.resolution} onChange={e=>edit('resolution',e.target.value)}><option value="unresolved">Unresolved</option><option value="partial">Partly resolved</option><option value="resolved">Resolved in my assessment</option></select></label><p>Keep management's recorded answer separate from your interpretation below.</p></>}
 {draft.kind==='underweight'&&<>{input('mandate','Portfolio / mandate')}{input('benchmark','Benchmark')}{input('asOf','Holdings and benchmark as of','date')}{input('holdingPct','Portfolio weight %')}{input('benchmarkPct','Benchmark weight %')}<label>Reason for nonownership / underweight<select aria-label="Reason for nonownership / underweight" value={draft.reason} onChange={e=>edit('reason',e.target.value)}>{['valuation','quality','recovery','constraint','research_gap'].map(k=><option key={k} value={k}>{k.replace('_',' ')}</option>)}</select></label><label>Current valuation assessment<textarea value={draft.valuationAssessment} onChange={e=>edit('valuationAssessment',e.target.value)}/></label><p>User-reported point-in-time inputs. Business improvement alone does not establish investment attractiveness.</p><h3>What would make us reconsider?</h3><p className="desk-explainer">Separate business performance, valuation and portfolio constraints. Assessments below are yours; conditions are not automatically monitored yet. Source references are manually recorded.</p>
 {draft.reviewConditions.map((c,i)=><section className="workspace-panel" key={c.id}><label>Condition type<select value={c.category} onChange={e=>edit('reviewConditions',draft.reviewConditions.map((v,j)=>j===i?{...v,category:e.target.value}:v))}>{['fundamental','valuation','constraint','research_gap'].map(k=><option key={k} value={k}>{k.replaceAll('_',' ')}</option>)}</select></label><label>Observable condition<textarea value={c.trigger} onChange={e=>edit('reviewConditions',draft.reviewConditions.map((v,j)=>j===i?{...v,trigger:e.target.value}:v))}/></label><label>My assessment<select value={c.state} onChange={e=>edit('reviewConditions',draft.reviewConditions.map((v,j)=>j===i?{...v,state:e.target.value}:v))}>{['unassessed','not_met','partly_met','met'].map(k=><option key={k} value={k}>{k.replaceAll('_',' ')}</option>)}</select></label>{[['evidence','Evidence and interpretation behind my assessment'],['sourceReference','Source, publication date and passage / page · manual reference']].map(([key,label])=><label key={key}>{label}<textarea value={c[key]} onChange={e=>edit('reviewConditions',draft.reviewConditions.map((v,j)=>j===i?{...v,[key]:e.target.value}:v))}/></label>)}<button onClick={()=>edit('reviewConditions',draft.reviewConditions.filter(v=>v.id!==c.id))}>Remove condition from draft</button></section>)}
 <button disabled={draft.reviewConditions.length>=12} onClick={()=>edit('reviewConditions',[...draft.reviewConditions,{id:crypto.randomUUID(),category:'fundamental',trigger:'',state:'unassessed',evidence:'',sourceReference:''}])}>Add reconsideration condition</button>
 <label>My underweight decision<select value={draft.reviewDecision} onChange={e=>edit('reviewDecision',e.target.value)}><option value="pending">Pending review</option><option value="maintain">Maintain underweight</option><option value="investigate">Investigate further</option><option value="propose_change">Propose portfolio change for consideration</option></select></label></>}
 <label>My interpretation and rationale<textarea value={draft.rationale} onChange={e=>edit('rationale',e.target.value)}/></label><label>Next action / evidence that would change my view<textarea value={draft.nextAction} onChange={e=>edit('nextAction',e.target.value)}/></label><label>State<select aria-label="State" value={draft.status} onChange={e=>edit('status',e.target.value)}><option value="open">Open work</option><option value="reviewed">Reviewed · conclusion recorded</option><option value="closed">Closed · outcome recorded</option></select></label>{draft.status!=='open'&&<label>Review outcome<textarea value={draft.outcome} onChange={e=>edit('outcome',e.target.value)}/></label>}
 {record&&<p>Editing work revision {record.revision}. Saving binds it to current case revision {caseRevision}; recheck changed assumptions.</p>}<button className="workspace-primary" onClick={save}>{busy?'Saving…':draft.kind==='model'?'Save work and calculate':'Save review revision'}</button><button onClick={()=>{setRecord(null);setDraft({...blank(),kind:initialKind});pending.current=null;}}>New work record</button><button onClick={load}>Reload source and answer choices</button></fieldset><p role="status">{message}</p>
 {data.records.map(r=><article className="workspace-panel" key={r.id}><h4>{r.body.title} · {r.body.status}</h4><p>{r.body.owner} · due {r.body.dueDate} · case r{r.body.caseRevision}{r.body.caseRevision!==caseRevision?' · Case has changed; review baseline':''}</p>{r.evidenceState&&<p className="desk-explainer">Evidence snapshot: {r.evidenceState.replaceAll('_',' ')}. Saved text matching does not establish currentness of the original disclosure.</p>}<p>{r.body.rationale}</p><p>Next: {r.body.nextAction}</p>{r.body.outcome&&<p><strong>Review outcome: </strong>{r.body.outcome}</p>}{r.body.resolution&&<p>Answer resolution · analyst assessment: {r.body.resolution}</p>}{r.body.calculation&&<><table><thead><tr><th>Metric</th><th>Before</th><th>After</th></tr></thead><tbody><tr><th>EPS</th><td>{r.body.calculation.beforeEPS}</td><td>{r.body.calculation.afterEPS}</td></tr><tr><th>Implied price · {r.body.inputs.currency}</th><td>{r.body.calculation.beforeValue??'Not applicable'}</td><td>{r.body.calculation.afterValue??'Not applicable'}</td></tr></tbody></table><p>Operating profit change: {r.body.calculation.operatingProfitDeltaMillions}m · EPS change: {r.body.calculation.epsDelta}</p><p className="desk-explainer">{r.body.calculation.scope}</p><blockquote>{r.body.passage}<cite> — {r.body.sourceFilename}</cite></blockquote></>}{r.body.answerSnapshot&&<blockquote>{r.body.answerSnapshot.response_notes}</blockquote>}{r.body.kind==='underweight'&&<p>Active weight: {r.body.activeWeightPct}% · {r.body.mandate} vs {r.body.benchmark} · as of {r.body.asOf}{(Date.now()-Date.parse(r.body.asOf))/86400000>30?' · Inputs older than 30 days':''}</p>}
 {r.body.kind==='underweight'&&<><button onClick={()=>setDebate(r)}>Challenge my underweight rationale</button><p>Review decision: {(r.body.reviewDecision||'pending').replaceAll('_',' ')}</p>{r.body.reviewConditions?.map(c=><p key={c.id}><strong>{c.category} · {c.state.replaceAll('_',' ')}</strong>: {c.trigger}<br/>{c.evidence}<br/><small>{c.sourceReference}</small></p>)}</>}
 <button disabled={busy} onClick={()=>{setRecord(r);setDraft({...blank(),...r.body});pending.current=null;}}>Review / update</button><button onClick={async()=>{try{setHistory({...await json(api,`/api/research/workbench/${ticker}/${r.id}/history`),id:r.id});}catch(e){setMessage(e.message);}}}>Version history</button><button onClick={()=>{const text=[r.body.title,`Owner: ${r.body.owner} | Due: ${r.body.dueDate}`,`Interpretation: ${r.body.rationale}`,`Next action: ${r.body.nextAction}`,`Assumption: ${r.body.assumptionSnapshot?.claim||'See saved case'} (case revision ${r.body.caseRevision})`,r.body.outcome?`Reviewed outcome: ${r.body.outcome}`:'',r.body.kind==='underweight'?`Portfolio context: ${r.body.mandate} versus ${r.body.benchmark}; holding ${r.body.holdingPct}%, benchmark ${r.body.benchmarkPct}%, active weight ${r.body.activeWeightPct}%, as of ${r.body.asOf}.\nReason: ${r.body.reason}. Valuation assessment: ${r.body.valuationAssessment}`:'',r.body.resolution?`Answer resolution (analyst assessment): ${r.body.resolution}`:'',r.body.calculation?`Sensitivity: EPS ${r.body.calculation.beforeEPS} → ${r.body.calculation.afterEPS}; implied price ${r.body.calculation.beforeValue??'N/A'} → ${r.body.calculation.afterValue??'N/A'} ${r.body.inputs.currency}.\n${r.body.calculation.scope}`:'',r.body.answerSnapshot?`Recorded answer: ${r.body.answerSnapshot.response_notes}`:'',r.body.passage?`Source: ${r.body.sourceFilename}\n${r.body.passage}`:''].filter(Boolean).join('\n\n');navigator.clipboard.writeText(text).then(()=>setMessage('Research brief copied.'),()=>setMessage('Clipboard unavailable.'));}}>Copy research brief</button></article>)}
 {history&&<details open><summary>Immutable work history</summary>{history.versions.map(v=><details key={v.revision}><summary>Revision {v.revision} · {v.body.status}</summary><button disabled={busy} onClick={()=>{setRecord(data.records.find(r=>r.id===history.id));setDraft({...blank(),...v.body,status:'open'});pending.current=null;setMessage('Historical version loaded as an unsaved draft. Review the current case, source and answer before saving a new revision.');}}>Use this version as a new draft</button><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(v.body,null,2)}</pre></details>)}<button onClick={()=>setHistory(null)}>Close history</button></details>}{debate&&<ResearchChat api={api} context={{ticker,type:'review',content:JSON.stringify({workId:debate.id,workRevision:debate.revision,review:debate.body})}} initialMessage="Challenge my underweight rationale using the recorded assumption and reconsideration conditions. Distinguish fundamental improvement, valuation, constraints and research gaps. Present the strongest opposing case and what additional evidence is needed. Do not claim a condition has been automatically verified or a portfolio change executed." allowEdits={false} onClose={()=>setDebate(null)}/>}</details>;
}
export function ResearchDueQueue({api,onOpen}){
 const [data,setData]=React.useState(null),[error,setError]=React.useState('');
 const sequence=React.useRef(0),alive=React.useRef(true);
 const load=async()=>{const seq=++sequence.current;try{const result=await json(api,'/api/research/workbench-queue');if(alive.current&&seq===sequence.current){setData(result);setError('');}}catch(e){if(alive.current&&seq===sequence.current)setError(e.message);}};
 React.useEffect(()=>{alive.current=true;load();const timer=setInterval(load,60000);return()=>{alive.current=false;clearInterval(timer);};},[]);
 return <section className="workspace-panel"><h2>Research follow-through</h2><p>Due issue reviews, meeting follow-ups, model work and underweight reviews.</p><button onClick={load}>Refresh due work</button>{error&&<p role="alert">{error}</p>}{data&&<><p>{data.items.filter(r=>r.due).length} due · as of {data.asOf}</p>{!data.items.length&&<p>No dated work is queued. Add a work record inside an investment case.</p>}<details open={data.items.some(r=>r.due)}><summary>{data.items.length} open or scheduled reviews</summary>{data.items.map(r=><p key={r.kind+r.id}><button onClick={()=>onOpen(r.ticker)}>{r.ticker} · {r.title}</button> · {r.due?'Due':'Upcoming'} {r.dueDate} · {r.body.owner||'Issue review'}</p>)}</details><p className="desk-explainer">{data.scope}</p></>}</section>;
}
