import * as React from 'react';

export function RevenueObservation({api,ticker,model,onChange,onResearch,metric="revenue"}) {
 const isEbitda=metric==='ebitda',isBalance=['cash','debt'].includes(metric),label=isEbitda?'EBITDA':metric,field={revenue:'baseRevenue',ebitda:'baseEbitda',cash:'baseCash',debt:'baseDebt'}[metric];
 const [runs,setRuns]=React.useState(null),[runId,setRunId]=React.useState(''),[options,setOptions]=React.useState([]),[choice,setChoice]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
 const [form,setForm]=React.useState({token:'',unit:'',fiscalYear:'',currency:'',basis:'',locator:'',confirmed:false});
 const sequence=React.useRef(0),latest=React.useRef(model);latest.current=model;
 React.useEffect(()=>()=>{sequence.current++;},[]);
 const json=async(path,init={})=>{const r=await fetch(api+path,{...init,signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Evidence unavailable');return d;};
 const load=async()=>{const seq=++sequence.current;setBusy(true);setError('');setOptions([]);setChoice('');setRunId('');try{const d=await json('/api/research/company/'+encodeURIComponent(ticker));if(seq===sequence.current)setRuns(d.runs.filter(r=>r.status==='complete'));}catch(e){if(seq===sequence.current)setError(e.message);}finally{if(seq===sequence.current)setBusy(false);}};
 const chooseRun=async(id)=>{const seq=++sequence.current;setRunId(id);setOptions([]);setChoice('');setError('');setForm(f=>({...f,token:'',confirmed:false}));if(!id)return;setBusy(true);try{const d=await json('/api/research/operating-model/'+encodeURIComponent(ticker)+'/'+metric+'-observation?runId='+encodeURIComponent(id));if(seq===sequence.current)setOptions(d.candidates);}catch(e){if(seq===sequence.current)setError(e.message);}finally{if(seq===sequence.current)setBusy(false);}};
 const selected=options[Number(choice)];
 const link=async()=>{const seq=++sequence.current,captured=JSON.stringify(model);setBusy(true);setError('');try{const d=await json('/api/research/operating-model/'+encodeURIComponent(ticker)+'/'+metric+'-observation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...selected,...form})});if(seq!==sequence.current)return;if(JSON.stringify(latest.current)!==captured)throw Error('Model inputs changed during the check. Review them, then link again.');const o=d.observation;if((isEbitda||isBalance)&&(Number(model.baseYear)!==o.fiscalYear||model.currency!==o.currency))throw Error('Historical input must match the model base fiscal year and currency. Update those inputs first.');onChange({...model,baseEbitdaComparable:false,balanceSheetComparable:false,[field]:o.valueMillions,...(isBalance?{[field+'Basis']:o.basis}:isEbitda?{ebitdaBasis:o.basis,baseEbitdaComparable:false}:{baseYear:o.fiscalYear,currency:o.currency}),[isBalance?field+'Reference':isEbitda?'baseEbitdaReference':'revenueReference']:`${o.filename} · ${o.locator} · FY${o.fiscalYear} · ${o.basis}`,[field+'Observation']:o});}catch(e){if(seq===sequence.current)setError(e.message);}finally{if(seq===sequence.current)setBusy(false);}};
 const observation=model[field+'Observation'];
 return <section aria-label={"Base "+label+" evidence"} className="revenue-observation"><style>{`.revenue-observation{border:1px solid #b8c5ce;border-left:4px solid #667f90;padding:18px;margin:20px 0;background:#f6f8fa}.revenue-observation select{display:block;width:100%;max-width:100%;padding:10px;background:white;color:black;border:1px solid #888}.revenue-observation blockquote{white-space:pre-wrap;overflow-wrap:anywhere;margin:12px 0;border-left:2px solid #aaa;padding:12px}.revenue-observation code{overflow-wrap:anywhere;font-size:12px}`}</style>
 <h4>Base {label} · source observation</h4><p>Choose a printed number from a reviewed research passage. Charlie checks the passage, number and conversion; you confirm what that number means. Future growth, margins and the equity bridge remain your assumptions.</p>
 {observation?<><p><strong>Passage and printed number matched · analyst meaning confirmed</strong></p><p>{observation.token} {observation.unit} {observation.currency} → {observation.valueMillions} million · FY{observation.fiscalYear}</p><p>{observation.filename} · {observation.locator} · {observation.basis}</p><blockquote>{observation.excerpt}</blockquote><details><summary>Frozen evidence receipt</summary><p>Research: <code>{observation.researchRunId}</code></p><p>Original SHA-256: <code>{observation.originalHash}</code></p><p>Extracted text SHA-256: <code>{observation.extractionHash}</code></p><p>{observation.interpretation}</p></details><p>Changing the base {label}, fiscal year, currency or linked definition requires relinking or unlinking. Every calculation and new save rechecks the original. Historical revisions retain their original receipt.</p><button onClick={()=>{const next={...model};delete next[field+'Observation'];onChange(next);}}>Unlink {label} evidence · keep the number</button></>:<>
 <button disabled={busy} onClick={load}>{busy?'Checking sources…':'Find '+label+' in completed research'}</button>{onResearch&&<button onClick={onResearch}>Open Deep Research</button>}
 {runs&&runs.length===0&&<p>No completed research runs for {ticker}. Save your draft, then select permitted originals in Deep Research. You can keep using a manual {label} reference meanwhile.</p>}
 {runs?.length>0&&<fieldset disabled={busy}><label>Completed research<select value={runId} onChange={e=>chooseRun(e.target.value)}><option value="">Choose a run</option>{runs.map(r=><option key={r.id} value={r.id}>{r.created_at?new Date(r.created_at).toLocaleString():'Date unavailable'} · {r.id.slice(0,8)} · case baseline R{r.baseline.revision}</option>)}</select></label>
 {runId&&options.length===0&&!busy&&<p>No eligible numeric passages. Claims must be reported facts with matched passages and supported review. Missing {label} stays manual; guidance, estimates and unresolved claims cannot be linked here.</p>}
 {options.length>0&&<><label>Reported passage · verify it is consolidated {isBalance?'fiscal-year-end':'annual'} {label}<select value={choice} onChange={e=>{setChoice(e.target.value);setForm(f=>({...f,token:'',confirmed:false}));}}><option value="">Choose a passage</option>{options.map((o,i)=><option key={i} value={i}>{o.filename} · {o.statement.slice(0,160)}</option>)}</select></label>
 {choice!==''&&selected&&<><blockquote>{selected.excerpt}</blockquote><label>Exact printed {label} number<select value={form.token} onChange={e=>setForm({...form,token:e.target.value,confirmed:false})}><option value="">Choose the {label} figure, not a year or other metric</option>{selected.numbers.map(n=><option key={n} value={n}>{n}</option>)}</select></label>
 <label>Units printed in source<select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value,confirmed:false})}><option value="">Choose source units</option>{['units','thousands','millions','billions'].map(u=><option key={u}>{u}</option>)}</select></label>
 {[['fiscalYear',label+' fiscal year'],['currency',label+' currency · three-letter code'],['basis',label+' accounting basis and definition'],['locator','Original page or section']].map(([k,label])=><label key={k}>{label}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value,confirmed:false})}/></label>)}
 <label><input type="checkbox" checked={form.confirmed} onChange={e=>setForm({...form,confirmed:e.target.checked})}/>I inspected the original and confirm this is {ticker} consolidated {isBalance?'fiscal-year-end':'annual'} {isEbitda?'positive EBITDA':label}, with the stated year, currency, units and accounting basis. It is not a forecast, segment figure or a different issuer.</label>
 <button disabled={!form.confirmed||!form.token||!form.unit} onClick={link}>Check and use {label} in draft</button><p>{isBalance?'This sets a historical balance-sheet input only; target-period debt remains a separate assumption.':isEbitda?'This sets positive base EBITDA and its definition in the draft. Confirm comparability with forecast margins before calculating.':'This changes base revenue, base fiscal year and currency in your draft.'} It does not save a case or launch research.</p></>}
 </>}
 </fieldset>}
 </>}
 <p role="alert">{error}</p></section>;
}
