import * as React from 'react';
export function SourcePreferences({api,onChange}) {
  const [saved,setSaved]=React.useState(null),[draft,setDraft]=React.useState(null),[error,setError]=React.useState(''),[message,setMessage]=React.useState(''),[busy,setBusy]=React.useState(false),[lists,setLists]=React.useState([]);
  const call=async(path,body,method='PUT')=>{const r=await fetch(api+path,{...(body?{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Source preferences unavailable');return d;};
  const reload=async()=>{try{const d=await call('/api/research/source-preferences');setSaved(d);setDraft(d.policy);onChange(d.policy);setError('');}catch(e){setError(e.message);}};
  React.useEffect(()=>{let active=true;call('/api/research/source-preferences').then(d=>{if(active){setSaved(d);setDraft(d.policy);onChange(d.policy);}}).catch(e=>{if(active)setError(e.message);});const poll=()=>call('/api/research/source-shortlists').then(d=>{if(active)setLists(d.shortlists);}).catch(e=>{if(active)setError(e.message);});poll();const timer=setInterval(poll,15000);return()=>{active=false;clearInterval(timer);};},[api]);
  const edit=p=>{setDraft(p);onChange(p);setMessage('Assignment override · save to reuse across devices.');};
  const save=async()=>{setBusy(true);try{const d=await call('/api/research/source-preferences',{revision:saved.revision,policy:draft});setSaved(d);setDraft(d.policy);onChange(d.policy);setMessage('Defaults saved across devices. Existing assignments keep their original policy.');setError('');}catch(e){setError(e.message);}finally{setBusy(false);}};
  const choose=async(list,url,choice)=>{setBusy(true);try{await call(`/api/research/commands/${list.commandId}/source-shortlist`,{revision:list.revision,choices:{[url]:choice}});setLists((await call('/api/research/source-shortlists')).shortlists);setMessage('Choice saved. Resume the paused request in Collection and recovery controls when your selection is complete.');setError('');}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <section className="workspace-panel source-preferences"><p className="workspace-eyebrow">RESEARCH STANDARDS</p><h2>Your sources. Your judgment.</h2><p>Primary disclosures anchor facts. Broker research adds interpretation. Set your preferences once, or adjust them for this assignment.</p>
    {draft&&<fieldset disabled={busy}><label>Who chooses broker research?<select value={draft.mode} onChange={e=>edit({...draft,mode:e.target.value})}><option value="auto">Charlie decides · respect my preferences</option><option value="preferred">Preferred sources only · ask before exceptions</option><option value="review">Let me select · review the document shortlist</option></select></label>
    <details><summary>Broker preferences & company overrides ({draft.rules.length})</summary><p>Use the publisher name exactly as shown in AlphaSense. Add alternate spellings as separate rules. A company/task rule overrides the general rule. Reference-only sources stay outside AI analysis.</p>
    {draft.rules.map((r,i)=><div className="source-rule" key={i}><label>Broker / source<input maxLength={120} value={r.name} onChange={e=>edit({...draft,rules:draft.rules.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/></label><label>Preference<select value={r.disposition} onChange={e=>edit({...draft,rules:draft.rules.map((x,j)=>j===i?{...x,disposition:e.target.value}:x)})}>{['preferred','standard','excluded','reference_only'].map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select></label><label>Ticker · optional<input maxLength={20} placeholder="All companies" value={r.ticker} onChange={e=>edit({...draft,rules:draft.rules.map((x,j)=>j===i?{...x,ticker:e.target.value.toUpperCase()}:x)})}/></label><label>Task<select value={r.task} onChange={e=>edit({...draft,rules:draft.rules.map((x,j)=>j===i?{...x,task:e.target.value}:x)})}>{['','meeting','filing','earnings','event'].map(x=><option key={x} value={x}>{x||'All tasks'}</option>)}</select></label><button type="button" aria-label={`Remove source rule ${i+1}`} onClick={()=>edit({...draft,rules:draft.rules.filter((_,j)=>j!==i)})}>Remove</button></div>)}
    <button type="button" disabled={draft.rules.length>=80} onClick={()=>edit({...draft,rules:[...draft.rules,{name:'',disposition:'preferred',ticker:'',task:''}]})}>Add a source preference</button></details>
    <p className="desk-explainer">Charlie should prioritize expertise, original analysis, relevance, freshness and credible disagreement—not brand prestige or the number of similar notes. Provider usage restrictions always apply. These defaults apply to new Command Charlie assignments; existing scheduled ticker policies are separate.</p><button type="button" onClick={save}>Save as my defaults</button><button type="button" onClick={reload}>Reload saved preferences</button></fieldset>}
    {error&&<p role="alert" className="workspace-error">{error} <button onClick={reload}>Reload</button></p>}{message&&<p role="status">{message}</p>}
    {lists.map(list=><details key={list.commandId}><summary>{list.ticker} · source shortlist · {list.candidates.filter(x=>x.decision==='pending').length} awaiting selection</summary><p>Decisions apply to these specific documents. Exclusions and provider restrictions still override an include choice.</p>{list.candidates.map(c=><article className="amendment-card" key={c.url}><strong>{c.title}</strong><p>{c.publisher} · {c.decision}</p><p>{c.reason}</p><a href={c.url} target="_blank" rel="noreferrer">Inspect in AlphaSense ↗</a><button disabled={busy||c.decision==='include'} onClick={()=>choose(list,c.url,'include')}>Include</button><button disabled={busy||c.decision==='exclude'} onClick={()=>choose(list,c.url,'exclude')}>Exclude</button></article>)}</details>)}
  </section>;
}
