import * as React from 'react';
export function SourcePreferences({api,onChange}) {
  const [mapTicker,setMapTicker]=React.useState(''),[mapSector,setMapSector]=React.useState(''),[previewTicker,setPreviewTicker]=React.useState(''),[previewBroker,setPreviewBroker]=React.useState(''),[previewTask,setPreviewTask]=React.useState('meeting'),[resolved,setResolved]=React.useState(null);

  const [saved,setSaved]=React.useState(null),[draft,setDraft]=React.useState(null),[error,setError]=React.useState(''),[message,setMessage]=React.useState(''),[busy,setBusy]=React.useState(false),[lists,setLists]=React.useState([]);
  const call=async(path,body,method='PUT')=>{const r=await fetch(api+path,{...(body?{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Source preferences unavailable');return d;};
  const reload=async()=>{setResolved(null);setMessage('');try{const d=await call('/api/research/source-preferences');setSaved(d);setDraft(d.policy);onChange(d.policy);setError('');}catch(e){setError(e.message);}};
  React.useEffect(()=>{let active=true;call('/api/research/source-preferences').then(d=>{if(active){setSaved(d);setDraft(d.policy);onChange(d.policy);}}).catch(e=>{if(active)setError(e.message);});const poll=()=>call('/api/research/source-shortlists').then(d=>{if(active)setLists(d.shortlists);}).catch(e=>{if(active)setError(e.message);});poll();const timer=setInterval(poll,15000);return()=>{active=false;clearInterval(timer);};},[api]);
  const edit=p=>{setResolved(null);setDraft(p);onChange(p);setMessage('Assignment override · save to reuse across devices.');};
  const save=async()=>{setBusy(true);try{const d=await call('/api/research/source-preferences',{revision:saved.revision,policy:draft});setSaved(d);setDraft(d.policy);onChange(d.policy);setMessage('Defaults saved across devices. Existing assignments keep their original policy.');setError('');}catch(e){setError(e.message);}finally{setBusy(false);}};
  const choose=async(list,url,choice)=>{setBusy(true);try{await call(`/api/research/commands/${list.commandId}/source-shortlist`,{revision:list.revision,choices:{[url]:choice}});setLists((await call('/api/research/source-shortlists')).shortlists);setMessage('Choice saved. Once the complete shortlist has no pending choices, the Mac agent queues a source-selection pause to resume automatically.');setError('');}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <section className="workspace-panel source-preferences"><p className="workspace-eyebrow">RESEARCH STANDARDS</p><h2>Your sources. Your judgment.</h2><p>Primary disclosures anchor facts. Broker research adds interpretation. Set your preferences once, or adjust them for this assignment.</p>
    {draft&&<fieldset disabled={busy}><label>Who chooses broker research?<select value={draft.mode} onChange={e=>edit({...draft,mode:e.target.value})}><option value="auto">Charlie decides · respect my preferences</option><option value="preferred">Preferred sources only · ask before exceptions</option><option value="review">Let me select · review the document shortlist</option></select></label>
    <details><summary>Broker preferences & company overrides ({draft.rules.length})</summary><p>Use the publisher name exactly as shown in AlphaSense. Add alternate spellings as separate rules. Stock rules override subsector rules; within a scope, named analysts override broker-wide rules. Task-specific rules break ties. Author identity must be observed on the report, never inferred from a firm or previous coverage. Reference-only sources stay outside AI analysis.</p>
    {draft.rules.map((r,i)=><div className="source-rule" key={i}><label>Broker / source<input maxLength={120} value={r.name} onChange={e=>edit({...draft,rules:draft.rules.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/></label><label>Preference<select value={r.disposition} onChange={e=>edit({...draft,rules:draft.rules.map((x,j)=>j===i?{...x,disposition:e.target.value}:x)})}>{['preferred','standard','excluded','reference_only'].map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select></label><label>Ticker · optional<input maxLength={20} placeholder="All companies" value={r.ticker} onChange={e=>edit({...draft,rules:draft.rules.map((x,j)=>j===i?{...x,ticker:e.target.value.toUpperCase(),subsector:''}:x)})}/></label><label>Subsector · optional<input disabled={!!r.ticker} maxLength={100} value={r.subsector||''} placeholder="All subsectors" onChange={e=>edit({...draft,rules:draft.rules.map((x,j)=>j===i?{...x,subsector:e.target.value}:x)})}/></label><label>Named analyst · optional<input maxLength={120} value={r.analyst||''} placeholder="Any analyst at this broker" onChange={e=>edit({...draft,rules:draft.rules.map((x,j)=>j===i?{...x,analyst:e.target.value}:x)})}/></label><label>Task<select value={r.task} onChange={e=>edit({...draft,rules:draft.rules.map((x,j)=>j===i?{...x,task:e.target.value}:x)})}>{['','meeting','filing','earnings','event'].map(x=><option key={x} value={x}>{x||'All tasks'}</option>)}</select></label><button type="button" aria-label={`Remove source rule ${i+1}`} onClick={()=>edit({...draft,rules:draft.rules.filter((_,j)=>j!==i)})}>Remove</button></div>)}
    <button type="button" disabled={draft.rules.length>=80} onClick={()=>edit({...draft,rules:[...draft.rules,{name:'',disposition:'preferred',ticker:'',task:''}]})}>Add a source preference</button></details>
    <details><summary>Company subsectors & effective preferences</summary><p>Use your own coverage classifications. Subsector rules apply only to companies mapped here. No classification is inferred.</p><div className="source-rule"><label>Ticker<input value={mapTicker} maxLength={20} onChange={e=>setMapTicker(e.target.value.toUpperCase())} placeholder="UNH"/></label><label>Subsector<input value={mapSector} maxLength={100} onChange={e=>setMapSector(e.target.value)} placeholder="Healthcare services"/></label><button type="button" disabled={!mapTicker.trim()||!mapSector.trim()} onClick={()=>{edit({...draft,subsectors:{...draft.subsectors,[mapTicker.trim()]:mapSector.trim()}});setMapTicker('');setMapSector('');}}>Assign subsector</button></div>{Object.entries(draft.subsectors||{}).map(([tk,sector])=><p key={tk}><strong>{tk}</strong> · {sector} <button type="button" onClick={()=>{const next={...draft.subsectors};delete next[tk];edit({...draft,subsectors:next});}}>Remove {tk} classification</button></p>)}
    <h3>Which rule will Charlie use?</h3><div className="source-rule"><label>Check ticker<input value={previewTicker} onChange={e=>{setPreviewTicker(e.target.value.toUpperCase());setResolved(null);}}/></label><label>Check broker<input value={previewBroker} onChange={e=>{setPreviewBroker(e.target.value);setResolved(null);}}/></label><label>Check task<select value={previewTask} onChange={e=>{setPreviewTask(e.target.value);setResolved(null);}}>{['meeting','filing','earnings','event'].map(x=><option key={x}>{x}</option>)}</select></label><button type="button" onClick={async()=>{try{setError('');setResolved(await call('/api/research/source-preferences/resolve',{policy:draft,ticker:previewTicker,publisher:previewBroker,task:previewTask},'POST'));}catch(e){setError(e.message);}}}>Explain preference</button></div>{resolved&&<div role="status"><strong>{resolved.decision} · {resolved.disposition}</strong><p>{resolved.reason} Subsector: {resolved.subsector||'not assigned'}.</p>{resolved.rule&&<p>Applied rule: {resolved.rule.name} · {resolved.rule.ticker||resolved.rule.subsector||'all companies'} · {resolved.rule.analyst||'all analysts'} · {resolved.rule.task||'all tasks'}.</p>}<p>Preview assumes the report author is not yet verified. Named-analyst rules are checked against observed authorship during collection.</p></div>}</details>
    <p className="desk-explainer">Charlie should prioritize expertise, original analysis, relevance, freshness and credible disagreement—not brand prestige or the number of similar notes. Provider usage restrictions always apply. Defaults apply to new commands and scheduled refreshes after the Mac syncs. Existing requests retain their frozen policy.</p><button type="button" onClick={save}>Save as my defaults</button><button type="button" onClick={reload}>Reload saved preferences</button></fieldset>}
    {error&&<p role="alert" className="workspace-error">{error} <button onClick={reload}>Reload</button></p>}{message&&<p role="status">{message}</p>}
    {lists.map(list=><details key={list.commandId}><summary>{list.ticker} · source shortlist · {list.candidates.filter(x=>x.decision==='pending').length} awaiting selection</summary><p>Decisions apply to these specific documents. Exclusions and provider restrictions still override an include choice.</p>{list.candidates.map(c=><article className="amendment-card" key={c.url}><strong>{c.title}</strong><p>{c.publisher} · {c.analyst||'Author not verified'} · {c.decision}</p>{c.authorEvidence&&<p>Observed authorship: {c.authorEvidence}</p>}<p>{c.reason}</p><a href={c.url} target="_blank" rel="noreferrer">Inspect in AlphaSense ↗</a><button disabled={busy||c.decision==='include'} onClick={()=>choose(list,c.url,'include')}>Include</button><button disabled={busy||c.decision==='exclude'} onClick={()=>choose(list,c.url,'exclude')}>Exclude</button></article>)}</details>)}
  </section>;
}
