import React,{useEffect,useState} from 'react';
const SECTIONS=[['brief','Brief','brief'],['takeaways','Key Takeaways','summary'],['meeting','Meeting Summary','meeting_summary'],['questions','Follow-up Questions','questions'],['assessment','Overall Assessment','assessment']];
export function SummaryLab({api,getKey,renderHtml,pickFromICloud}){
 const [sources,setSources]=useState([]),[runs,setRuns]=useState([]),[id,setId]=useState(''),[row,setRow]=useState(null),[sid,setSid]=useState(''),[source,setSource]=useState(''),[title,setTitle]=useState(''),[focus,setFocus]=useState(''),[section,setSection]=useState('brief'),[compare,setCompare]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[notice,setNotice]=useState(''),[importing,setImporting]=useState(false),[importStatus,setImportStatus]=useState('');
 async function req(path='',body){const r=await fetch(`${api}/api/summary-lab${path}`,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
 useEffect(()=>{let active=true;async function load(){try{const [a,b]=await Promise.all([req('/sources'),req()]);if(active){setSources(a.sources);setRuns(b.experiments);}}catch(e){if(active)setError(e.message);}}load();const t=setInterval(load,12000);return()=>{active=false;clearInterval(t);};},[api]);
 useEffect(()=>{if(!id){setRow(null);return;}let active=true;setRow(null);async function load(){try{const d=await req('/'+id);if(active)setRow(d);}catch(e){if(active)setError(e.message);}}load();const t=setInterval(load,6000);return()=>{active=false;clearInterval(t);};},[id,api]);
 useEffect(()=>{setFeedback(row?.feedback||'');},[row?.id]);
 async function start(){setBusy(true);setError('');setNotice('');try{const d=await req('',{summaryId:sid||undefined,source,title:title.trim()||'Untitled experiment',focus,apiKey:getKey()});setId(d.id);setRuns((await req()).experiments);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function importCloud(){
  setImporting(true);setError('');setImportStatus('Choose documents from iCloud…');
  try{
   const files=await pickFromICloud({mode:'bytes',title:'Summary Lab · choose iCloud documents'});
   if(!files?.length){setImportStatus('');return;}
   const records=[];
   for(let i=0;i<files.length;i++){
    const file=files[i];setImportStatus(`Reading ${i+1} of ${files.length}: ${file.name}`);
    if(!/\.(pdf|docx|txt|md|csv|png|jpe?g|webp)$/i.test(file.name))throw Error(`${file.name}: choose PDF, DOCX, text or image documents. For audio, select its saved Summary transcript.`);
    const form=new FormData();form.append('files',file);form.append('apiKey',getKey()||'');
    const response=await fetch(`${api}/api/extract-summary-text`,{method:'POST',body:form,signal:AbortSignal.timeout(120000)});
    const data=await response.json();
    if(!response.ok||!data.text?.trim()||/^\[(Error processing|Unsupported file type|Image file:)/.test(data.text.trim()))throw Error(`${file.name}: ${data.error||'No readable text was extracted. Try a text-searchable PDF or paste the text.'}`);
    records.push(`=== SOURCE: ${file.name} ===\n${data.text}`);
   }
   setSid('');setSource(records.join('\n\n'));if(!title.trim())setTitle(files[0].name.replace(/\.[^.]+$/,'').slice(0,300));
   setImportStatus(`Imported ${files.length} document${files.length===1?'':'s'}. Review the source text below, then generate.`);
  }catch(e){setError(`${e.message} No imported documents were applied; your previous source is preserved.`);setImportStatus('Import did not finish.');}
  finally{setImporting(false);}
 }
 async function retry(){setBusy(true);setError('');try{await req('/'+id+'/retry',{apiKey:getKey()});setRow(await req('/'+id));}catch(e){setError(e.message);}finally{setBusy(false);}}
 const state=row?.state||{},text=state.sections?.[section]||'',baseline=SECTIONS.find(s=>s[0]===section)?.[2];
 async function copy(all=false){try{await navigator.clipboard.writeText(all?SECTIONS.map(([k,l])=>l+'\n\n'+(state.sections?.[k]||'')).join('\n\n---\n\n'):text);setNotice('Copied experimental notes.');}catch{setError('Clipboard unavailable. Select the note text to copy.');}}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(row,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`Summary-Lab-${id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <main className="summary-lab">
 <style>{`.summary-lab{box-sizing:border-box;--lab-border:rgba(153,142,119,.35);max-width:1500px;margin:auto;padding:32px;color:var(--text-primary,#e9e2d3);width:100%;min-width:0}.summary-lab *{box-sizing:border-box}.summary-lab h1,.summary-lab h2{font-family:Georgia,serif;line-height:1.2}.summary-lab h1{font-size:38px;margin:8px 0 14px}.summary-lab h2{font-size:24px;margin:0 0 18px}.summary-lab p{line-height:1.65}.summary-lab .muted{opacity:.72;font-size:13px}.summary-lab .eyebrow{color:#c9a857;letter-spacing:.13em;text-transform:uppercase;font-size:11px}.summary-lab .layout{display:grid;grid-template-columns:300px minmax(0,1fr);gap:24px;margin-top:28px}.summary-lab .panel{border:1px solid var(--lab-border);border-radius:14px;padding:24px;background:rgba(127,115,89,.045);min-width:0}.summary-lab label{display:block;font-size:13px;margin:16px 0 6px}.summary-lab input,.summary-lab select,.summary-lab textarea{width:100%;padding:11px;border:1px solid var(--lab-border);border-radius:7px;background:var(--bg-secondary,#211e18);color:inherit;font:inherit;min-width:0}.summary-lab select option{background:#211e18;color:#eee}.summary-lab button{padding:10px 14px;min-height:44px;border:1px solid var(--lab-border);border-radius:7px;font:inherit;cursor:pointer;background:transparent;color:inherit}.summary-lab button:focus-visible,.summary-lab input:focus-visible,.summary-lab textarea:focus-visible,.summary-lab select:focus-visible{outline:2px solid #c9a857;outline-offset:3px}.summary-lab button:disabled{opacity:.45;cursor:default}.summary-lab button.primary,.summary-lab button[aria-pressed=true]{background:#c9a857;color:#18150f}.summary-lab .controls{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.summary-lab .experiment{display:block;width:100%;text-align:left;margin:10px 0;overflow-wrap:anywhere}.summary-lab .reader{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.8;font-size:15px;max-width:78ch}.summary-lab .pair{display:grid;gap:24px;grid-template-columns:repeat(2,minmax(0,1fr))}.summary-lab .status{padding:14px;border-left:3px solid #c9a857;background:rgba(201,168,87,.08);margin:16px 0;overflow-wrap:anywhere}.summary-lab details{border-top:1px solid var(--lab-border);padding:16px 0;margin-top:16px}.summary-lab summary{cursor:pointer;min-height:32px}.summary-lab pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit;line-height:1.7}.summary-lab .original{overflow-wrap:anywhere;line-height:1.8}.summary-lab .original table{display:block;overflow:auto;max-width:100%}@media(max-width:900px){.summary-lab{padding:18px}.summary-lab .layout,.summary-lab .pair{grid-template-columns:1fr}.summary-lab h1{font-size:30px}.summary-lab .panel{padding:18px}}`}</style>
 <div className="eyebrow">Charlie / Research experiments</div><h1>Summary Lab</h1><p>Read thoroughly. Preserve what was said. Separate what it means.</p><p className="muted">An independent trial with five familiar sections. Original summaries and automatic workflows are unchanged.</p>
 {error&&<div role="alert" className="status">{error}<button onClick={()=>setError('')} aria-label="Dismiss error">Dismiss</button></div>}
 <div className="layout"><aside><section className="panel"><h2>New experiment</h2><button disabled={busy||importing} onClick={importCloud}>{importing?'Importing…':'Browse iCloud documents'}</button><p className="muted">STOCKS and CATALYSTS · the same connected folders as Summary</p>{importStatus&&<p role="status" className="muted">{importStatus}</p>}<label htmlFor="lab-source">Saved transcript or document</label><select id="lab-source" value={sid} onChange={e=>setSid(e.target.value)}><option value="">Paste source text instead</option>{sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select>
 {!sid&&<><label htmlFor="lab-text">Complete source text</label><textarea id="lab-text" rows={8} value={source} onChange={e=>setSource(e.target.value)} placeholder="Paste a transcript or extracted document text…"/><p className="muted">{source.length.toLocaleString()} characters · no silent character cutoff</p></>}
 <label htmlFor="lab-title">Experiment name</label><input id="lab-title" value={title} maxLength={300} onChange={e=>setTitle(e.target.value)} placeholder="MMM conference · first trial"/>
 <label htmlFor="lab-focus">Optional emphasis</label><textarea id="lab-focus" rows={3} maxLength={4000} value={focus} onChange={e=>setFocus(e.target.value)} placeholder="Preserve the segment detail and management’s margin explanation."/>
 <p className="muted">Uses model credits. Thorough review makes several passes over the source; long transcripts take longer. Experiments remain saved when you leave.</p><button className="primary" disabled={busy||importing||(!sid&&!source.trim())} onClick={start}>{busy?'Starting…':'Generate all five sections'}</button></section>
 <section className="panel" style={{marginTop:20}}><h2>Experiments</h2>{!runs.length&&<p className="muted">Your experiments will appear here.</p>}{runs.map(r=><button className="experiment" aria-pressed={id===r.id} key={r.id} onClick={()=>{setId(r.id);setNotice('');}}>{r.title}<div className="muted">{r.status==='complete'?'Ready to compare':r.status} · {new Date(r.created_at).toLocaleDateString()}</div></button>)}</section></aside>
 <section className="panel">{!row?<><div className="eyebrow">Independent source review</div><h2 style={{marginTop:12}}>{id?'Loading experiment…':'Your next research note starts here'}</h2><p>Choose an existing Summary to compare against a frozen copy of its original output, or paste a new source. One action generates Brief, Key Takeaways, Meeting Summary, Follow-up Questions and Assessment.</p><p className="muted">This version reviews saved text. It cannot re-listen to audio or verify OCR against page images; material ambiguities remain visible.</p></>:<>
 <div className="eyebrow">{row.version} · {row.model}</div><h2 style={{marginTop:12}}>{row.title}</h2><div className="status" role="status">{row.error||state.progress||'Queued'}<div className="muted">{Object.keys(state.parts||{}).length} / {state.totalParts||'—'} source parts reviewed · {row.status}</div></div>
 {(row.status==='failed'||(row.status!=='complete'&&Date.now()-new Date(row.updated_at).getTime()>180000))&&<button disabled={busy} onClick={retry}>Resume saved experiment</button>}
 <div className="controls" aria-label="Experimental sections">{SECTIONS.map(([k,l])=><button key={k} aria-pressed={section===k} onClick={()=>setSection(k)}>{l}</button>)}</div>
 <div className="controls"><button disabled={!Object.keys(row.baseline||{}).length} aria-pressed={compare} onClick={()=>setCompare(!compare)}>Compare with original</button><button disabled={!text} onClick={()=>copy()}>Copy section</button><button disabled={row.status!=='complete'} onClick={()=>copy(true)}>Copy all</button><button onClick={download}>Download experiment</button></div>{notice&&<p role="status">{notice}</p>}
 {row.status!=='complete'&&text&&<p className="muted">Draft in progress. Source checks and revisions may still change this text.</p>}
 <div className={compare?'pair':''}>{compare&&<article><h3>Original · frozen at experiment start</h3><div className="original" dangerouslySetInnerHTML={{__html:renderHtml(row.baseline?.[baseline]||'<p>No original section saved.</p>')}}/></article>}<article><h3>Experimental</h3><div className="reader">{text||'This section will appear after source review and generation.'}</div></article></div>
 <details><summary>Reviewer notes and limitations</summary><pre>{state.finalReview||'Final cross-section review has not finished.'}</pre><p className="muted">Model review is not independent factual verification. Exact supporting passages are checked against saved source text. The reviewed record may still contain omissions or interpretation errors.</p>{state.hierarchicalSynthesis&&<p>Long-source synthesis used consolidated records; complete part records remain below.</p>}<details><summary>Initial checks for this section</summary><pre>{state.checks?.[section]||'Not yet available.'}</pre></details></details>
 <details><summary>Source record and supporting passages · {Object.keys(state.parts||{}).length} parts</summary>{Object.values(state.parts||{}).map(p=><details key={p.id}><summary>{p.id} · characters {p.start}–{p.end}</summary><pre>{p.record}</pre><h4>Exact original passages</h4>{p.passages.map((v,i)=><blockquote key={i} className="reader">{v}</blockquote>)}<h4>Ambiguities / proposed corrections</h4><pre>{JSON.stringify(p.issues,null,2)}</pre></details>)}<details><summary>Immutable original source</summary><pre>{row.source}</pre></details></details>
 <label htmlFor="lab-feedback">Your evaluation</label><textarea id="lab-feedback" rows={4} value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="What improved? What was lost, overstated, or harder to read?"/><button style={{marginTop:10}} onClick={async()=>{try{await req('/'+id+'/feedback',{feedback});setNotice('Evaluation saved.');}catch(e){setError(e.message);}}}>Save evaluation</button>
 </>}</section></div></main>;
}
