import * as React from 'react';
export function ThesisMonitor({api,ticker,disabled}){
 const [data,setData]=React.useState(null),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false);
 const live=React.useRef(true),sequence=React.useRef(0),lock=React.useRef(false);
 async function load(){const n=++sequence.current;try{const r=await fetch(`${api}/api/research/investment-case/${ticker}/monitor`,{signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Monitoring unavailable');if(live.current&&n===sequence.current){setData(d);setError('');}}catch(e){if(live.current&&n===sequence.current)setError(e.message);}}
 React.useEffect(()=>{live.current=true;load();const timer=setInterval(load,20000);return()=>{live.current=false;clearInterval(timer);};},[api,ticker]);
 async function save(enabled,resetPending=false){if(lock.current)return;lock.current=true;setBusy(true);try{const r=await fetch(`${api}/api/research/investment-case/${ticker}/monitor`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled,revision:data.revision,resetPending}),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not save monitoring');if(live.current){setData(d);setError('');}}catch(e){if(live.current)setError(e.message+' Reload status before retrying.');}finally{lock.current=false;if(live.current)setBusy(false);}}
 return <section className="workspace-panel thesis-monitor"><p className="workspace-eyebrow">NEW EVIDENCE → THESIS REVIEW</p><h3>Monitor newly imported sources.</h3><p>Once enabled, the connected Mac agent checks for new or changed originals in Charlie and queues an evidence comparison. Your saved underweight conditions inform that review. Changes still require your acceptance.</p><p className="desk-explainer">The first enrollment records existing files as the baseline. It does not download documents or backfill old research. Up to 10 new sources are compared per batch; later batches wait for the current proposal to be closed. Uses configured server model credits. While paused, new files remain eligible when resumed.</p>{data&&<><p><strong>{data.enabled?'Monitoring enabled':'Monitoring paused'}</strong> · {data.baselineSources||0} known source files</p><button className="workspace-primary" disabled={disabled||busy} onClick={()=>save(!data.enabled)}>{busy?'Saving…':data.enabled?'Pause monitoring':'Enable prospective monitoring'}</button><button disabled={busy} onClick={load}>Refresh monitoring status</button>{data.checked_at&&<p>Last check: {new Date(data.checked_at).toLocaleString()}</p>}{data.last_result?.message&&<p role="status">{data.last_result.state}: {data.last_result.message}</p>}{data.last_result?.filenames&&<details><summary>Sources submitted in latest batch</summary>{data.last_result.filenames.map(n=><p key={n}>{n}</p>)}<p>Proposal: {data.last_result.proposalId}</p></details>}{data.pending&&<><p>A submission reservation is retained for retry. No source is marked processed until a proposal receipt is confirmed.</p><button disabled={disabled||busy} onClick={()=>save(data.enabled,true)}>Recheck reservation against latest baseline</button></>}</>}{error&&<p role="alert">{error}</p>}</section>;
}
