import * as React from 'react';
import {compareCases,pillarState,latestWork} from './thesis-evolution-model.mjs';
const stamp=x=>new Date(x).toLocaleString();
export function ThesisEvolution({api,ticker,revision}){
 const [data,setData]=React.useState(null),[asOf,setAsOf]=React.useState(''),[chosen,setChosen]=React.useState(null),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[epoch,setEpoch]=React.useState(0);
 React.useEffect(()=>{let alive=true;setBusy(true);setError('');setData(null);setChosen(null);let query='';try{if(asOf)query='?asOf='+encodeURIComponent(new Date(asOf).toISOString());}catch{setError('Choose a valid date.');setBusy(false);return;}
 fetch(`${api}/api/research/lifecycle/${encodeURIComponent(ticker)}${query}`,{signal:AbortSignal.timeout(20000)}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'History unavailable');return d;}).then(d=>{if(alive){setData(d);setChosen(d.cases[0]?.revision??null);}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setBusy(false);});return()=>{alive=false;};},[api,ticker,revision,asOf,epoch]);
 const cases=[...(data?.cases||[])].sort((a,b)=>a.revision-b.revision), index=cases.findIndex(v=>v.revision===chosen), selected=cases[index], previous=cases[index-1];
 const pillars=[...new Map(cases.flatMap(v=>(v.body.assumptions||[]).map(a=>[a.id,a.claim]))).entries()];
 const events=[...(data?.work||[]).map(r=>({...r,kind:r.body.kind})),...(data?.decisions||[]).map(r=>({...r,kind:'decision'}))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));
 return <section className="thesis-evolution" aria-label="Thesis evolution"><p className="workspace-eyebrow">THE INVESTMENT RECORD</p><h2>How our thinking evolved.</h2><p>Trace changes in the saved investment case and the decisions recorded alongside it.</p>
 <div className="evolution-controls"><label>Known to Charlie by · your local time<input type="datetime-local" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label><button onClick={()=>{setAsOf('');setEpoch(x=>x+1);}}>Return to latest / refresh</button></div>
 {busy&&<p role="status">Reconstructing saved history…</p>}{error&&<p role="alert">{error}</p>}
 {data&&<><p className="desk-explainer">Recorded through {stamp(data.asOf)}. {data.scope}</p>{Object.values(data.limited).some(Boolean)&&<p role="status">This view is limited to 100 records per category. Older history is not shown; the first displayed case is a baseline, not an inferred initial thesis.</p>}
 {!cases.length?<p>No investment case was saved by this time. Save the initial case to establish your baseline.</p>:<><div className="evolution-rail" aria-label="Saved case revisions">{cases.map(v=><button key={v.revision} aria-pressed={chosen===v.revision} onClick={()=>setChosen(v.revision)}><strong>Revision {v.revision}</strong><time>{stamp(v.created_at)}</time><span>{v.body.evidenceLinks?.length||0} retained source links</span></button>)}</div>
 <div className="evolution-matrix"><table><caption>Assumption history · “Revised” describes wording changes, not investment strength</caption><thead><tr><th>Investment pillar</th>{cases.map(v=><th key={v.revision}><button onClick={()=>setChosen(v.revision)}>R{v.revision}</button></th>)}</tr></thead><tbody>{pillars.map(([id,label])=><tr key={id}><th>{label}</th>{cases.map((v,i)=><td key={v.revision} data-state={pillarState(cases[i-1]?.body,v.body,id,i>0)}>{pillarState(cases[i-1]?.body,v.body,id,i>0)}</td>)}</tr>)}</tbody></table></div>
 {selected&&<article className="workspace-panel"><p className="workspace-eyebrow">{previous?`R${previous.revision} → R${selected.revision}`:'FIRST DISPLAYED BASELINE'}</p><h3>{ticker} · revision {selected.revision}</h3><p>{stamp(selected.created_at)}</p>{previous?compareCases(previous.body,selected.body).map((c,i)=><section className="evolution-change" key={i}><h4>{c.label}</h4><div><section><small>Before</small><p>{c.before||'Not recorded'}</p></section><section><small>After</small><p>{c.after||'Removed / cleared'}</p></section></div></section>):<p style={{whiteSpace:'pre-wrap'}}>{selected.body.thesis||'No thesis narrative recorded.'}</p>}
 {previous&&compareCases(previous.body,selected.body).length===0&&<p>No tracked thesis wording or scenario changes. This version may preserve metadata or a restoration.</p>}
 <details><summary>Accepted evidence attached to this version</summary>{!selected.body.evidenceLinks?.length&&<p>No accepted source links were recorded.</p>}{selected.body.evidenceLinks?.map((link,i)=><section key={i}><h4>{link.field} · {link.reason}</h4><p>{link.before} → {link.after}</p><p>{link.provenance}</p><div>{(link.evidence||[]).map((e,j)=><blockquote key={j}><strong>{e.source?.filename||e.sourceId||'Saved source'}</strong><p style={{whiteSpace:'pre-wrap'}}>{e.excerpt||'No excerpt recorded'}</p></blockquote>)}</div></section>)}</details></article>}</>}
 <h3>Underweight decisions at this cutoff</h3>{latestWork(data.work).filter(r=>r.body.kind==='underweight').map(r=><article className="workspace-panel" key={r.id}><h4>{r.body.title}</h4><p>{r.body.mandate} · active weight {r.body.activeWeightPct}% · inputs as of {r.body.asOf}</p><p>{r.body.rationale}</p><p>Decision: {(r.body.reviewDecision||'pending').replaceAll('_',' ')} · {r.body.outcome||'Review remains open'}</p>{r.body.reviewConditions?.map(c=><p key={c.id}><strong>{c.category} · {c.state.replaceAll('_',' ')}</strong>: {c.trigger}<br/>{c.evidence}</p>)}</article>)}
 <h3>Evidence review decisions</h3>{!(data.proposalReviews||[]).length&&<p>No proposal conclusions recorded at this cutoff.</p>}{(data.proposalReviews||[]).map(r=><article className="workspace-panel" key={r.id}><h4>{r.review.outcome.replaceAll('_',' ')}</h4><p>{r.review.rationale}</p><p>Recorded {stamp(r.review.recordedAt)} · compared with case R{r.case_revision}</p></article>)}<h3>Decision and work timeline</h3><p className="desk-explainer">These records are shown by save time. Proximity to a thesis revision does not establish that it caused the change.</p>{!events.length&&<p>No decisions or work records at this cutoff.</p>}{events.map(r=><details key={r.kind+r.id+r.revision}><summary>{stamp(r.created_at)} · {r.kind.replaceAll('_',' ')} · {r.body.title||r.body.decision}</summary><p>{r.body.rationale}</p><p>{r.body.outcome||r.body.nextAction||r.body.revisitWhen}</p><p>Recorded revision {r.revision}{r.body.caseRevision?` · case baseline R${r.body.caseRevision}`:''}</p></details>)}</>}
 </section>;
}
