import {parseTimestamp} from './workspace-model.mjs';
import * as React from 'react';
const {useState,useEffect,useRef}=React;
export function ThesisAmendments({api,ticker,context,onApplied}) {
  const [jobs,setJobs]=useState([]),[selected,setSelected]=useState([]),[accepted,setAccepted]=useState([]);
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
  const alive=useRef(true),lock=useRef(false),requestId=useRef(null),sequence=useRef(0);
  const documents=context?.documents?.uploaded||[];
  const thesisDate=parseTimestamp(context?.savedThesis?.updatedAt);
  const isNew=d=>thesisDate&&parseTimestamp(d.addedAt)>thesisDate;
  const newCount=documents.filter(isNew).length;
  const job=jobs.find(j=>['queued','running','awaiting_approval'].includes(j.status))||jobs[0];
  const changes=job?.result?.changes||[];
  const fieldLabel=path=>{if(path==='thesis.summary')return 'Thesis summary';if(path==='conclusion')return 'Conclusion';const parts=path.split('.'),i=Number(parts[0]==='thesis'?parts[2]:parts[1]);if(parts[0]==='thesis')return context?.savedThesis?.thesis?.pillars?.[i]?.title||`Pillar ${i+1}`;return `${parts[0]==='signposts'?'Signpost':'Risk'} ${i+1}`;};
  const fetchJson=async(path,options={})=>{
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);
    try{const r=await fetch(`${api}${path}`,{...options,signal:controller.signal});const d=await r.json();if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;}finally{clearTimeout(timer);}
  };
  const refresh=async()=>{const id=++sequence.current;try{const d=await fetchJson(`/api/research/amendments/${encodeURIComponent(ticker)}`);if(alive.current&&id===sequence.current){setJobs(d.jobs||[]);setLoaded(true);}}catch(e){if(alive.current&&id===sequence.current){setError(e.name==='AbortError'?'The request timed out. Refresh to check status.':e.message);setLoaded(true);}}};
  useEffect(()=>{alive.current=true;refresh();const timer=setInterval(()=>{if(!document.hidden)refresh();},5000);return()=>{alive.current=false;sequence.current++;clearInterval(timer);};},[api,ticker]);
  useEffect(()=>{setAccepted([]);if(job&&!['queued','running','awaiting_approval'].includes(job.status))requestId.current=null;},[job?.id,job?.status]);
  const mutate=async(path,body)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const d=await fetchJson(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(alive.current){await refresh();if(d.status==='applied')onApplied();}}catch(e){if(alive.current){setError(e.message+' Check the proposal status before retrying.');await refresh();}}finally{lock.current=false;if(alive.current)setBusy(false);}};
  const launch=()=>{if(!requestId.current)requestId.current=crypto.randomUUID();let key='';try{key=localStorage.getItem('equity_analyzer_api_key')||'';}catch{}return mutate(`/api/research/amendments/${encodeURIComponent(ticker)}`,{filenames:selected,requestId:requestId.current,apiKey:key});};
  const active=job&&['queued','running','awaiting_approval'].includes(job.status);
  return <section className="workspace-panel thesis-amendments"><p className="workspace-eyebrow">NEW EVIDENCE → PROPOSED THESIS EDITS</p><h3>What should change?</h3><p className="desk-explainer">Compare selected sources with your saved thesis. Charlie drafts targeted edits and checks their supporting quotations. Your thesis changes only when you apply selected edits.</p>
    {error&&<div className="workspace-error" role="alert">{error}<button onClick={()=>{setError('');refresh();}}>Refresh status</button></div>}
    {!loaded?<p role="status">Loading proposals…</p>:<>
      {active?<div className="workspace-notice"><strong>{job.status==='awaiting_approval'?'Proposal ready for your review':'Comparing sources…'}</strong>{job.status!=='awaiting_approval'&&<p>The proposal is saved as a job. If a server restart interrupts it, dismiss it and prepare a new comparison. No thesis edits have been applied.</p>}<button disabled={busy} onClick={()=>mutate(`/api/research/amendment/${job.id}/decide`,{action:'dismiss'})}>Dismiss proposal</button></div>:<>
        {job&&<p className="desk-explainer" role="status">Last proposal: {job.status.replaceAll('_',' ')}{job.error?` · ${job.error}`:''}</p>}
        {!context?.savedThesis?<p>Save an investment thesis before preparing edits.</p>:!documents.length?<p>Import source documents into Charlie first. Files listed only in the iCloud inventory must be imported before this comparison can read them.</p>:<details open><summary>Select documents to compare ({selected.length}/10)</summary><p className="desk-explainer">{newCount} document(s) were added to Charlie after the saved thesis update. This is upload timing, not publication date or proof they contain new information.</p><div className="amendment-documents">{documents.map(d=><label key={d.filename}><input type="checkbox" checked={selected.includes(d.filename)} disabled={busy||(!selected.includes(d.filename)&&selected.length>=10)} onChange={()=>{requestId.current=null;setSelected(old=>old.includes(d.filename)?old.filter(n=>n!==d.filename):[...old,d.filename]);}}/><span>{d.filename}{isNew(d)&&<small>Added after thesis update</small>}</span></label>)}</div><p className="desk-explainer">Uses your configured research model and API credits. Up to 10 saved documents per comparison; scanned or oversized sources may need preparation first.</p><button className="workspace-primary" disabled={busy||!selected.length} onClick={launch}>{busy?'Submitting…':'Find material changes →'}</button></details>}
      </>}
      {['awaiting_approval','applied'].includes(job?.status)&&<>
        {!changes.length?<p className="workspace-notice">No material edits were proposed from these sources. This is not a guarantee that the thesis is complete or correct.</p>:changes.map(c=><article className="amendment-card" key={c.id}><label><input type="checkbox" checked={job.status==='applied'?(job.result.acceptedIds||[]).includes(c.id):accepted.includes(c.id)} disabled={busy||job.status!=='awaiting_approval'||!c.passageMatched||!c.reviewPassed} onChange={()=>setAccepted(old=>old.includes(c.id)?old.filter(id=>id!==c.id):[...old,c.id])}/><strong>{fieldLabel(c.path)}{job.status==='applied'?((job.result.acceptedIds||[]).includes(c.id)?' · Applied':' · Not applied'):''}</strong></label><p>{c.reason}</p><div className="evidence-compare"><div><h4>Saved text</h4><p>{c.before}</p></div><div><h4>Proposed text</h4><p>{c.after}</p></div></div><p className="desk-explainer">{c.passageMatched?'Source quotation matched.':'Blocked: source quotation did not match.'} {c.reviewPassed?'Independent check passed; analyst judgment required.':'Blocked: independent review needs revision.'} {c.reviewIssue}</p>{c.evidence.map((e,i)=><details key={i}><summary>Inspect supporting quotation</summary><strong>{job.result.sources?.find(s=>s.id===e.sourceId)?.filename||'Unknown source'}</strong><blockquote>{e.excerpt}</blockquote></details>)}</article>)}
        {changes.length>0&&job.status==='awaiting_approval'&&<><p className="desk-explainer">Applying saves only checked fields, preserves the original thesis in the proposal history, and rejects the proposal if your saved thesis has changed since comparison.</p><button className="workspace-primary" disabled={busy||!accepted.length} onClick={()=>mutate(`/api/research/amendment/${job.id}/decide`,{action:'apply',acceptedIds:accepted})}>Apply {accepted.length} selected edit{accepted.length===1?'':'s'}</button></>}
      </>}
    </>}
  </section>;
}
