"""Verify research/catalyst email presentation without importing the app or sending mail."""
import ast
from pathlib import Path
from types import SimpleNamespace
from unittest import TestCase, main
from unittest.mock import patch


class ResearchEmailFormatTests(TestCase):
    def test_clean_calibri_document_has_no_banner_or_product_footer(self):
        source = Path(__file__).resolve().parents[2] / 'app_v3.py'
        tree = ast.parse(source.read_text())
        fn = next(node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == 'email_research')
        fn.decorator_list = []
        scope = {
            'request': SimpleNamespace(json={
                'email': 'fixture@example.com',
                'subject': 'MRK Catalyst Note',
                'content': '# My takeaway\n\nThe readout matters.',
                'minimal': True,
                'smtpConfig': {
                    'use_gmail': True,
                    'gmail_user': 'fixture@example.com',
                    'gmail_app_password': 'mock-only',
                },
            }),
            'jsonify': lambda *args, **kwargs: args[0] if args else kwargs,
        }
        exec(compile(ast.Module(body=[fn], type_ignores=[]), 'research-email-function', 'exec'), scope)
        with patch('smtplib.SMTP_SSL') as smtp:
            result = scope['email_research']()
            message = smtp.return_value.__enter__.return_value.send_message.call_args.args[0]
        html = message.get_payload()[1].get_payload(decode=True).decode()
        self.assertIn('font-family: Calibri', html)
        self.assertIn('font-size: 11pt', html)
        self.assertIn('color: #000000', html)
        self.assertNotIn('linear-gradient', html)
        self.assertNotIn('Generated by TDL Equity Analyzer', html)
        self.assertTrue(result['success'])


if __name__ == '__main__':
    main()
